### ISSUE TITLE
Remove one contact information on "edit submisssion page"

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#104]
On peut pas supprimer un contact de la page de soumission d'unes avec un bouton e ontologie. 
Si on efface le champ, il revient peuplé avec la même info que précédement. 

On vient de voir ca sur Agrovoc. 

Qu'en est-il des autres propriétés qui sont ajoutées avec un bouton "Add .."

**Comment by syphax-bouazzouni** [comment]
It seems to be resolved,
I tested it, with http://testportal.lirmm.fr/ontologies/E-PHY/submissions/1/edit and I can : 

- update the contact information 
- remove a contact (if it exists one more user for the submission)
