### ISSUE TITLE
Adding new visualization to landscape and other enhancement

### ISSUE THREAD

**Issue by vemonet** [agroportal/project-management#106]
Idées de nouvelles visualisation pour la page Landscape : 

* Afficher un Word Cloud des mots les plus utilisés dans les gros champs textes (description, notes, knownUsage)

Pour ça on peut utiliser le Gem https://github.com/abitdodgy/words_counted
```ruby
# In the Gemfile
gem 'words_counted'

# To exclude common words
WordsCounted.count(post, exclude: ->(word) { word.length > 5 })
WordsCounted.count(post, exclude: %w[ a the to I in of ])
```

**Comment by syphax-bouazzouni** [comment]
@jonquet  to close ?

**Comment by jonquet** [comment]
Oui je pense qu'on peut fermer cet issue ;) 
C'etait la premiere phase de la page Landscape. On fera une 2eme iteration bientot.
