### ISSUE TITLE
Better browse page for metadata

### ISSUE THREAD

**Issue by vemonet** [agroportal/project-management#107]
Changer la browse page pour avoir un meilleur affichage des nouvelles metadata : 

* Utiliser des button qui renvoient vers des URL quand ce sont des données attendues (data in catalog, lien vers des ontologies du portail...)
* Drapeau pour les naturalLanguage
* Afficher la pullLocation ?
* Eviter les champs vides...
* Récupérer et afficher l'image si lien direct vers logo ou depiction
* Cacher data dump et open search description

**Comment by syphax-bouazzouni** [comment]
@jonquet  to close ?

**Comment by jonquet** [comment]
Yep, most enhancements have been added when his issue was addressed.
