### ISSUE TITLE
Better handling of organization name for landscape

### ISSUE THREAD

**Issue by vemonet** [agroportal/project-management#113]
Organization name are formatted as : 
ACRONYM (http://URL.org)

Dans l'UI ajouter un petit texte pour expliquer comment remplir les champs organisation (publisher, fundedBy, endorsedBy)

**Comment by syphax-bouazzouni** [comment]
still relevant, like shown in the screenshot below : 
![image](https://user-images.githubusercontent.com/29259906/160511252-491f99a2-be89-4abd-b251-aefb24421bd7.png)

**Comment by jonquet** [comment]
Still relevant and not only for the "fundedBy" metadata property. Several are concerned: 
foaf:fundedBy
omv:endorsedBy
dcterms:publisher

However, there is an new resource to rely on : https://ror.org/
(maybe: https://ror.readme.io/docs/match-organization-names-to-ror-ids)

Eventually we should have a way to enforce this by using their API to auto-complete a form and in the back end encode with a ROR identifier. 
Same philosophy must be applied to other metadata properties such as omv:naturalLanguage or creator/contributors (with ORCID lookups).

**Comment by syphax-bouazzouni** [comment]
related to https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/75

**Comment by jonquet** [comment]
We can close this old one! This is coming with he new Agent model.
