### ISSUE TITLE
Improve indexing

### ISSUE THREAD

**Issue by vemonet** [agroportal/project-management#114]
* Proper indexing of Skos XL labels

SKOS XL labels are not properly indexed in solr (the label is not retrieved)
Example: "salud animal" ("animal health") in NALT 
http://agroportal.lirmm.fr/ontologies/NALT/?p=classes&conceptid=http%3A%2F%2Flod.nal.usda.gov%2Fnalt%2F9232

* Proper indexing of prefLabel 

When 2 prefLabel of different lang, the prefLabel that is not selected to be "Preferred name" is only indexed in properties (should it be in synonyms?)

**Comment by syphax-bouazzouni** [comment]
Close as it is refined here https://github.com/agroportal/project-management/issues/241 (and having an 6 years old issue open, is embracing)
