### ISSUE TITLE
LOOM mappings don't work for Agrovoc and GACS.

### ISSUE THREAD

**Issue by vemonet** [agroportal/project-management#115]
LOOM mappings don't work for Agrovoc and GACS.

They are not defined in the 4store (we can't find <CLASS_URI> bpm:mappingLoom "mylabel" or bpm:mappingSameURI)

Trying to reprocess

**Comment by syphax-bouazzouni** [comment]
Related to #123

**Comment by jonquet** [comment]
I close here the issue as captured in #123
