### ISSUE TITLE
Get my metadata back returns "undefined" for ontologies without URI

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#116]
Check 
http://agroportal.lirmm.fr/ontologies/ONTOBIOTOPE
to reproduce

**Comment by syphax-bouazzouni** [comment]
Can't reproduce the error.

**Comment by jonquet** [comment]
It does reproduce with the .nt and .json export. The .rdf does work and do not return undefined.
<img width="149" alt="Capture d’écran 2021-10-15 à 14 36 49" src="https://user-images.githubusercontent.com/7379183/137487780-612ed4cf-e969-49ac-aec1-f8acad8db693.png">

**Comment by syphax-bouazzouni** [comment]
Seems to be fixed 
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/29259906/169917994-464acd57-e4c1-4e49-9688-93ea97fe22dc.png">

**Comment by jonquet** [comment]
En effet je n'arrive pas a reproduire l'erreur. 
On va pas se plaindre ;)
