### ISSUE TITLE
Error message for a view creation

### ISSUE THREAD

**Issue by antool** [agroportal/project-management#117]
When you create a view, you've got the traditionnal error message 'Something has going wrong…' while the creation is effective.

**Comment by syphax-bouazzouni** [comment]
@jonquet  is this still relevant? I think it's no more the case.

**Comment by jonquet** [comment]
I does not seems to be fixed. Just reproduced with OT1V in StagePortal 

<img width="487" alt="image" src="https://user-images.githubusercontent.com/7379183/163085092-76d0fc3e-f2aa-4c76-98ca-0fd1390dba14.png">

Got a error but then right after check the page: 
http://stageportal.lirmm.fr/ontologies/OT1V
Which displays fine

**Comment by syphax-bouazzouni** [comment]
# Logs (var/log/rails/appliance.log)
``` 
F, [2022-04-13T04:03:11.967309 #14775] FATAL -- :   
F, [2022-04-13T04:03:11.967576 #14775] FATAL -- : ActionView::Template::Error (undefined method `metadata_only?' for nil:NilClass):
F, [2022-04-13T04:03:11.967938 #14775] FATAL -- :     1: %div{:style => "padding: 2em;"}
    2:   %h1 Ontology Submitted Successfully
    3:   %br/
    4:   -if @ontology.metadata_only?
    5:     %p Thank you for submitting your ontology to #{$SITE}.
    6:     %p Users can now see your ontology in our ontology list but they cannot explore or search it. To enable exploring and searching, please upload a fu
ll version of your ontology.
    7:   -else
F, [2022-04-13T04:03:11.967970 #14775] FATAL -- :   
F, [2022-04-13T04:03:11.968008 #14775] FATAL -- : app/views/ontologies/submit_success.html.haml:4:in `_app_views_ontologies_submit_success_html_haml___1333696
083575004252_39939760'
app/controllers/ontologies_controller.rb:415:in `submit_success'
F, [2022-04-13T04:04:16.270704 #14775] FATAL -- :   
F, [2022-04-13T04:04:16.270836 #14775] FATAL -- : NoMethodError (undefined method `first' for nil:NilClass):
F, [2022-04-13T04:04:16.270880 #14775] FATAL -- :   
F, [2022-04-13T04:04:16.270918 #14775] FATAL -- : app/controllers/application_controller.rb:429:in `get_class'
app/controllers/concepts_controller.rb:76:in `show_tree'
F, [2022-04-13T04:04:16.373133 #14775] FATAL -- :   
```

**Comment by syphax-bouazzouni** [comment]
May be resolved by https://github.com/ncbo/bioportal_web_ui/issues/192

**Comment by jonquet** [comment]
Not sure as the other issue mention problems updating a view. 
we are here experiencing problems when updating an ontology that has a view. 
might be related though.

**Comment by syphax-bouazzouni** [comment]
Fixed after merging to the new upstream version https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/76

![image](https://user-images.githubusercontent.com/29259906/168831539-a2f8e40e-6741-4653-a94b-97b4a02ae427.png)

**Comment by syphax-bouazzouni** [comment]
The issue of "updating an ontology that has a view" mentioned above by @jonquet is tracked here https://github.com/agroportal/project-management/issues/269
