### ISSUE TITLE
Add instance view when browsing a class in OWL ontologies

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#118]
AgroPortal provides an API call to get all the instances of an ontology:
For example for  BIOREFINERY:
http://data.agroportal.lirmm.fr/ontologies/BIOREFINERY/instances 

And for a given concept: 
http://data.agroportal.lirmm.fr/ontologies/BIOREFINERY/classes/http%3A%2F%2Fopendata.inra.fr%2Fresources%2Fcore%23Singular_Unit/instances

We just need to develop a specific tab when browsing a concept that allows to display instances for the corresponding class. 
Pagination might be necessary.

**Comment by syphax-bouazzouni** [comment]
Yes, this is an important feature and relatively easy to develop (one to two weeks) since it is only a user interface. (this issue is related to #119)

**Comment by jonquet** [comment]
Yes. I would prioritize this feature request high.

#118 is about seeing the instance corresponding to a class
At in a specific tab at the right of "Class Mappings" in a tab called "Instances"
<img width="738" alt="Capture d’écran 2021-10-15 à 14 57 30" src="https://user-images.githubusercontent.com/7379183/137490475-adf8e8ee-122b-4652-807b-c83e4b5623f3.png">

#119 is about visualizing the ontology instances at the global level (typically with an iterator).

**Comment by jonquet** [comment]
This feature need to be implemented in a way that OntoPortal can take it back (pull request on NCBO GitHub planned).
FYI to @mdorf @jvendetti and @graybeal
