### ISSUE TITLE
No metadata extraction whithout the mention <owl:Ontology>

### ISSUE THREAD

**Issue by antool** [agroportal/project-management#126]
Metadata in a skos file within the part <skos:conceptScheme> are ignored. You need to change <skos:conceptScheme> for <owl:Ontology> if you want the metadata to be automatically extracted.
It should be added the possibility of extracting the metadata for any object equivalent to owl: ontology, such as omv:Ontology, skos:conceptScheme, voaf:Vocabulary, etc (refer to our document "AgroPortal Metadata List").

**Comment by jonquet** [comment]
After years several implementation related to SKOS in release 2.4 we have decide this is not a bug but a desired feature ;)

We need a owl/ontology  to distinguish the main skos:ConceptScheme (especially when multiple skos:ConceptScheme are available).
