### ISSUE TITLE
License logos must be refined

### ISSUE THREAD

**Issue by antool** [agroportal/project-management#127]
Some users pointed that logo for CC Licences were not always adapted (e.g. logo for CC BY-NC 4.0)

**Comment by syphax-bouazzouni** [comment]
@jonquet to update the requirements.

**Comment by jonquet** [comment]
Si on a pas une ressource extérieur qui fourni des logo pour TOUTES les licences qu'on a dans le formulaire (ce que je n'ai pas trouvé ... en particulier la https://rdflicense.linkeddata.es/  - ce qui sera sans doute le truc qu'on prendra
<img width="353" alt="Capture d’écran 2023-11-10 à 18 31 29" src="https://github.com/agroportal/project-management/assets/7379183/e64bb5ba-55a4-46d5-9634-82852c43879b">

ra plus tard...) alors je suggère de fermer cette issue de ce contenter de nos pseudo logo

**Comment by syphax-bouazzouni** [comment]
![image](https://github.com/agroportal/project-management/assets/29259906/f344d511-2622-45a1-a8d4-f521d3907480)
Source: https://v0.dev/t/8RUe2SDdzD3

**Comment by syphax-bouazzouni** [comment]
fixed 
![image](https://github.com/agroportal/project-management/assets/29259906/e9863d4a-de33-4ddf-9f2a-02648b82c343)
