### ISSUE TITLE
Problem with pullURL for ontologies in @Web

### ISSUE THREAD

**Issue by antool** [agroportal/project-management#129]
Lorqu'une ontologie est téléchargée sur le portail @web de l'INRA ([http://pfl.grignon.inra.fr/atWeb/](url)), le fichier est généré à la volée et la métadonnée `<owl:versionInfo>` est automatiquement complétée avec la date du jour en cours.
Ainsi, lorsqu'une pullURL pointe sur ce site (par ex. pour Biorefinery ou Transmat), un changement est détecté chaque nuit dans le fichier de l'ontologie par AgroPortal (il y a à chaque fois une nouvelle valeur dans le champ `<owl:versionInfo>`) et provoque une nouvelle soumission. Ceci explique le nombre important de soumissions pour ces ontologies alors qu'il n'y a en fait que de très rares véritables modifications dans le fichier.

**Comment by antool** [comment]
@selios La plateforme atWeb va-t-elle continuer à vivre en parallèle du nouveau Dataverse Inra ?

**Comment by syphax-bouazzouni** [comment]
@jonquet  is this still relevant?

**Comment by jonquet** [comment]
TRANSMAT, BIOREFINERY, PO2, DURUM_WHEAT have been unplugged from AgroPortal at that time.
We assumed they are manually updated by their developpers. 
Pinging @selios and Patrice Buche by email.

**Comment by syphax-bouazzouni** [comment]
@jonquet, so we close?

**Comment by jonquet** [comment]
Will check with Patrice and Stephane.
