### ISSUE TITLE
Duplicate LOOM/SAME_URI mappings generated by AgroPortal

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#133]
This is a reference to https://github.com/ncbo/bioportal_web_ui/issues/76

See: http://agroportal.lirmm.fr/ontologies/PO?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPO_0001003#mappings
for similar example.

We need to fix this in AgroPortal to. 
\cc @elcioabrahao

**Comment by syphax-bouazzouni** [comment]
close as duplicate of #284
