### ISSUE TITLE
Distinguish imported/reused classes from the one explicitly defined in an ontology

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#135]
When browsing an ontology in the UI, it would be nice to distinguish the classes (in the tree) imported or reused form another ontology from the ones defined in the name space fo the actually ontology being browse. 

For example: 
http://agroportal.lirmm.fr/ontologies/PO2/?p=classes&conceptid=http%3A%2F%2Fopendata.inra.fr%2FPO2%2Fstep
"step" is defined in PO2 and shall be in another color in the tree than 
http://agroportal.lirmm.fr/ontologies/PO2/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000015
"process" which is reused from BFO. 

It shall be easy to do by just looking at the base URI of the concept and compare it with the base URI of the ontology. 

CC: @jvendetti @graybeal as BioPortal could be interested to.

**Comment by jonquet** [comment]
Re-opening this thread after discussion with @syphax-bouazzouni . 
We recent change in the tree/list display on the left of the browse page (release 2.4 to come) with can now implement this. 
The idea would be to rely on the preferredNamespaceUri metadata property added within AgroPortal metadata model. 

http://data.agroportal.lirmm.fr/submissions?display=preferredNamespaceUri&display_context=false&display_links=false

This property tells you the URI of the names space of the ontology i.e., it does explicitly contains the string root of all the URIs defined in an ontology
For instances: 
- AGROVOC URIs are like : http://aims.fao.org/aos/agrovoc/c_38445 => preferredNamespaceUri=http://aims.fao.org/aos/agrovoc/
- AGRO URIs are like: http://purl.obolibrary.org/obo/AGRO_00000002 => preferredNamespaceUri=http://purl.obolibrary.org/obo/AGRO_

Note that the property will need curation (we will work with @hibadjebabria169 on this) as most of them are empty for the moment.

**Comment by jonquet** [comment]
The proposition is to use the current display for classes or concepts not in the preferredNamespaceUri but display in bold the classes that are defined with this prefix.

**Comment by syphax-bouazzouni** [comment]
related to https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/62

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/631

**Comment by jonquet** [comment]
That's a five year old! congrats team @Bilelkihal and @syphax-bouazzouni
