### ISSUE TITLE
Propriété version ne peut pas être un integer

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#137]
Si le numero de version d'une ontologie est declaré comme cela: 

<pav:version rdf:datatype="http://www.w3.org/2001/XMLSchema#decimal">1.0</pav:version>

Cela donne un integer pour la version chez AgroPortal…. Et ce qui fait planter l’affichage qui souhaite un string.  
Voir:
https://github.com/agroportal/agroportal_web_ui/blob/master/app/helpers/ontologies_helper.rb ligne 301

**Comment by syphax-bouazzouni** [comment]
duplicate with https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/2

**Comment by syphax-bouazzouni** [comment]
Fixed with https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/163
