### ISSUE TITLE
Update VT versions manually 

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#140]
We are several verison behind for VT because of PURL issue described here: 
https://github.com/AnimalGenome/vertebrate-trait-ontology/issues/3

We need to load each version manually from 
https://github.com/AnimalGenome/vertebrate-trait-ontology 
from 7.3 to 10.3

**Comment by syphax-bouazzouni** [comment]
it seems that it's have done http://agroportal.lirmm.fr/ontologies/VT, but it still needs to clean duplicated versions (e.g VT has 13 times the same version of 11.4)

**Comment by syphax-bouazzouni** [comment]
@jonquet any news about this?

**Comment by jonquet** [comment]
VT developper contacted by email.

**Comment by syphax-bouazzouni** [comment]
@jonquet a year after, any news?

**Comment by jonquet** [comment]
I have updated the latest version info. 
We need to curate the rest (so issue shall remain open). Can't be done right now (not working in AgroPortal 2.7).

Follow up with : 
https://github.com/AnimalGenome/vertebrate-trait-ontology/issues/10
and
https://github.com/AnimalGenome/vertebrate-trait-ontology/issues/9

**Comment by syphax-bouazzouni** [comment]
> I have updated the latest version info. We need to curate the rest (so issue shall remain open). Can't be done right now (not working in AgroPortal 2.7).
> 
> Follow up with : [AnimalGenome/vertebrate-trait-ontology#10](https://github.com/AnimalGenome/vertebrate-trait-ontology/issues/10) and [AnimalGenome/vertebrate-trait-ontology#9](https://github.com/AnimalGenome/vertebrate-trait-ontology/issues/9)

@jonquet  is it still not working in AgroProportal 2.8

**Comment by jonquet** [comment]
Seems to work now. I have removed submisison number 17.  Its a bit long but did not genertaed error. 

For the rest of the cleaning I have mentionned to @zhiliangme here: https://github.com/AnimalGenome/vertebrate-trait-ontology/issues/11

**Comment by jonquet** [comment]
Confirmed .. ok to removd duplicate and keep on ly the first ones of the series. 
Will do with eradicate script

**Comment by jonquet** [comment]
Close as done.
