### ISSUE TITLE
Think a way to distinguish in th UI historical  "ontologies"

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#148]
Source : Clement from Slack channel "inrae-ontologies"
![image](https://user-images.githubusercontent.com/29259906/145419138-0a13100b-5f55-411b-83e8-11b66870be9a.png)

**Comment by jonquet** [comment]
Two things: 

- In the "browse" page we could use the "Entry type" section on the left to add the metadata property "status" and display a check box call "retired" that by default will be at false... and if one clik it will dispaly also the ontologies with status = retired
<img width="201" alt="Capture d’écran 2022-01-13 à 11 08 43" src="https://user-images.githubusercontent.com/7379183/149310010-2bff78bd-0015-4fd2-b99b-7a898c3b3374.png">

- We can also display in the browse page the ontologies name ( with status = retired with the same color but with more brightness.

**Comment by syphax-bouazzouni** [comment]
done 


![Image](https://github.com/agroportal/project-management/assets/29259906/c2f82c18-00a4-4286-ba9e-7d6f937ca266)

And


![Image](https://github.com/agroportal/project-management/assets/29259906/cad3d9bd-a183-45c3-9832-b02c4ecd238c)
