### ISSUE TITLE
2021 - Release plan

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#150]
This issue is a description of the main contributions and changes bring by the 2021 Release, it has for purpose to list and fellow the developments progression of the features through this cycle.

# Timeline 

- **Stared:**  June , 2021
- **Ends:** january , 2022

# New features

- [x] https://github.com/ncbo/bioportal_web_ui/pull/167 
- [x] #182 
- [x] https://github.com/agroportal/documentation/issues/152
- [x] https://github.com/agroportal/documentation/issues/151
- [x] https://github.com/agroportal/documentation/issues/165
- [x] https://github.com/agroportal/documentation/issues/149
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/30
- [x] https://github.com/ontoportal-lirmm/ncbo_cron/issues/4

# Content fixes

- [ ] https://github.com/agroportal/documentation/issues/167
- [x] https://github.com/agroportal/documentation/issues/192

# Bug fixes
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/8
- [x] https://github.com/agroportal/documentation/issues/154

# Devops
- [x] https://github.com/agroportal/documentation/issues/159
- [ ] https://github.com/agroportal/documentation/issues/144
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/26
- [x] https://github.com/agroportal/documentation/issues/173

# Documentation
- [ ] https://github.com/agroportal/documentation/issues/162

# Linked pull requests (Our contributions to the ontoportal project)
- https://github.com/ncbo/bioportal_web_ui/pull/167
- https://github.com/ncbo/ontologies_linked_data/pull/123
- https://github.com/ncbo/goo/pull/115
- https://github.com/ncbo/ontologies_linked_data/pull/123
- https://github.com/ncbo/ontologies_api/pull/75
- https://github.com/ncbo/bioportal_web_ui/pull/184
- https://github.com/ncbo/bioportal_web_ui/pull/185

**Comment by jonquet** [comment]
For releases summaries I thought about using the GitHub feature e.g., for BioPortal 
 https://github.com/ncbo/bioportal_web_ui/releases/tag/v6.5.1
rather than issues. 

History of release communication is here : 
https://github.com/agroportal/documentation/wiki/Release-notes
With a GDoc behind. This could be improved for sure.

**Comment by syphax-bouazzouni** [comment]
## To be transferred  to the next release: 

- https://github.com/agroportal/documentation/issues/167
- https://github.com/agroportal/documentation/issues/192
- https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/8
- https://github.com/agroportal/documentation/issues/162

## To be abandoned : 
Nothing for this release 

## Release notes : 

- UI: https://github.com/ontoportal-lirmm/bioportal_web_ui/releases/tag/v2.2.3
- API: https://github.com/ontoportal-lirmm/ontologies_api/releases/tag/v2.1.0
- OLD: https://github.com/ontoportal-lirmm/ontologies_linked_data/releases/tag/v2.1.0
- GOO: https://github.com/ontoportal-lirmm/goo/releases/tag/v2.1.0
- NCBO CRON : https://github.com/ontoportal-lirmm/ncbo_cron/releases/tag/v2.0.2
- Configs: https://gite.lirmm.fr/bioportal/bioportal-configs/-/releases/v2.0.3
- Deploy scripts:  https://gite.lirmm.fr/ontoportal/ontoportal_deploy_scripts/-/releases/v2.0.3
