### ISSUE TITLE
Enable notifications

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#151]
## Current state
Notifications to check if working :

- [x] receive feedback (done by the UI)
- [ ] error exception (done by the UI) **(never used called in the code))**
- [ ] endlessloop exception (done by the UI) **(never used called in the code)**
- [x] Lost password (done by the **ontology_linked_data** in **ontologies_api/users_controller**)
- [x] new note (done by the **ontology_linked_data/note.rb**)
- [x] submission processed (done the **ontology_linked_data/ontology_submisssion.rb**)
- [x] remote pull failure (done by the **ontology_linked_data**)
- [x] new user created (done by the **ontology_linked_data** in **ontologies_api/users_controller**)
- [x] new ontology created (donne by the **ontology_linked_data** in **ontologies_api/ontologies_controller**)

Configuration files (exemple of stageportal) :
- ui config file : /config/bioportal_config_appliance.rb
```ruby
# Email settings
ActionMailer::Base.smtp_settings = {
  :address  => "smtp.lirmm.fr", # smtp server address, ex: smtp.example.org
  :port  => 25, # smtp server port
  :domain  => "lirmm.fr", # fqdn of rails server, ex: rails.example.org
}
# Announcements mailman mailing list REQUEST address, EX: list-request@lists.example.org
# NOTE: You must use the REQUEST address for the mailing list. ONLY WORKS WITH MAILMAN LISTS.
$ANNOUNCE_LIST = "sifrportal-support@lirmm.fr"

# Email used to send notifications
# Email addresses used for sending notifications (errors, feedback, support)
$SUPPORT_EMAIL = "sifrportal-support@lirmm.fr"
$ADMIN_EMAIL =  "sifrportal-support@lirmm.fr"
$ERROR_EMAIL = "sifrportal-support@lirmm.fr"
```

- api config file : /config/environments/appliance.rb
```ruby
# Email notifications
config.enable_notifications   = true 
config.email_sender           = "agroportal-support@lirmm.fr" # Default sender$
config.email_override         = "agroportal-support@lirmm.fr" # all email gets$
config.email_disable_override = true
config.smtp_host              = "smtp.lirmm.fr"
config.smtp_port              = 25
config.smtp_auth_type         = :none # :none, :plain, :login, :cram_md5
config.smtp_domain            = "lirmm.fr"
 config.admin_emails           = ["agroportal-support@lirmm.fr"]
```

- cron config file : /config/bioportal_config_appliance.rb
```ruby
# Email settings
ActionMailer::Base.smtp_settings = {
  :address  => "smtp.lirmm.fr", # smtp server address, ex: smtp.example.org
  :port  => 25, # smtp server port
  :domain  => "lirmm.fr", # fqdn of rails server, ex: rails.example.org
}
# Announcements mailman mailing list REQUEST address, EX: list-request@lists.example.org
# NOTE: You must use the REQUEST address for the mailing list. ONLY WORKS WITH MAILMAN LISTS.
$ANNOUNCE_LIST = "sifrportal-support@lirmm.fr"

# Email used to send notifications
# Email addresses used for sending notifications (errors, feedback, support)
$SUPPORT_EMAIL = "sifrportal-support@lirmm.fr"
$ADMIN_EMAIL =  "sifrportal-support@lirmm.fr"
$ERROR_EMAIL = "sifrportal-support@lirmm.fr"
```
## bugs (for next release)

- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/4
- [ ] https://github.com/ncbo/bioportal_web_ui/issues/183
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/8

## Deployment

- [x] on stage https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/21
- [x] on agroportal https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/21
- [x] on sifrportal
## Related issues
#141

**Comment by syphax-bouazzouni** [comment]
contact ncbo team https://github.com/ncbo/bioportal_web_ui/issues/183

**Comment by jonquet** [comment]
Side note: emails content should be updated to "AgroPortal" instead of "Agroportal" 
Multiple occurences... let's hope they all rely on the name variable.
