### ISSUE TITLE
Think and do a backup system for agroportal

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#170]
### Requirements
- [ ] Use Jonquetlab, as a backup server
- [ ] Have an automatic script to save and send the backup data to the backup server 
- [ ] Do it once a month

**Comment by jonquet** [comment]
Discussed also with STI-RX and this is addressed. 
Regular backups are scheduled and exceptionnal ones can be requested. 
@syphax-bouazzouni What do you like to do on this topic?

**Comment by syphax-bouazzouni** [comment]
Nothing that is why I closed it.
