### ISSUE TITLE
agroportal trafic analysis

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#173]
The 06/01/2022 we had this issue (see capture below) when accessing to http://agroportal.lirmm.fr/

![image](https://user-images.githubusercontent.com/29259906/148413125-2aab94ba-13d1-48be-983c-31a22df05a63.png)

## The cause
This may because we are spammed  by bot IPs (see capture below of the count of request send to Agroportal the 06/01/2022)

![image](https://user-images.githubusercontent.com/29259906/148413564-79e05fb1-d388-476d-9108-5038c882f978.png)

## Logs
And there is what we can see an the access log 

![image](https://user-images.githubusercontent.com/29259906/148413881-216589dc-4d9a-4256-b67f-9f4fceb72705.png)

We can observe that they target this two routes : 

- /feedback
- /login

**Comment by jonquet** [comment]
A noter l'existence d'un fichier robots.txt: 
http://agroportal.lirmm.fr/robots.txt
http://bioportal.lirmm.fr/robots.txt 

@syphax-bouazzouni Pourrait tu regarder si ces fichiers sont differents de ceux que j'avais customisé il y a qq mois. Me semble que j'avais mis plus de bot

**Comment by jonquet** [comment]
Ce jour de STI-RX: 
Je viens de mettre en place mod_security sur le apache de agroportal. Toutes les règles sont désactivée sauf la surveillance de feedback avec des critères un peu stricts. 

La conf du module est sous /etc/httpd/modsecurity.d  et /etc/httpd/conf.d/mod_security.conf
et pour /feedback une entrée est rajoutée dans /etc/httpd/conf.d/10-appliance.ontoportal.org_non-tls.conf

**Comment by jonquet** [comment]
Le 'bon ' (celui edité en fevrier 2021) fihier robots.txt est ici: 
https://github.com/ontoportal-lirmm/bioportal_web_ui/blob/development/config/robots/appliance.txt

**Comment by syphax-bouazzouni** [comment]
### Summary of the latest updates
## STI-RX changes :
They have added mod_security and enabled only for the /feedback
The configuration are in **/etc/httpd/conf.d/10-appliance.ontoportal.org_non-tls.conf**
![image](https://user-images.githubusercontent.com/29259906/150791545-87c7e465-c8b9-478c-95fe-82281bbbd973.png)
### Did it work ?
**it seem that no**, prouve the following screenshoot of the **/var/log/httpd/appliance.ontoportal.org_non-tls_access.log** file for the 24/Jan/2022 (got using the following command `grep "24/Jan/2022" appliance.ontoportal.org_non-tls_access.log | less` )
![image](https://user-images.githubusercontent.com/29259906/150791716-5fe05aed-2a48-4dff-a8f8-8c5993eae725.png)

### What next ?
In the above screenshot of the access we remark that they are from robots and more specifically from the AhrefsBots. 

So the next step is to disallow robots for some paths, like feedback

## Update robot.txt file

- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/57 

### Did it work ?
 yes it worked. Below the screenshoot of the **/var/log/httpd/appliance.ontoportal.org_non-tls_access.log** file for the 26/Jan/2022 and we can see that there is no more /feedback or AhrefsBots.

![image](https://user-images.githubusercontent.com/29259906/151152854-1d1e17be-ee56-48e3-a5c0-8334b97641d8.png)

But still we see that the Googlebot is still there (which is not a problem of him self) and index unwanted paths like /ajax.
So we need to :

- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/58

**Comment by jonquet** [comment]
Similar to the /ajax exclusion we can do an exclusion for /javacsripts which is also very frequent in the logs


<img width="791" alt="Capture d’écran 2022-01-26 à 16 26 22" src="https://user-images.githubusercontent.com/7379183/151192748-f2905847-0613-48d7-bf1c-83950f17df80.png">

**Comment by syphax-bouazzouni** [comment]
## 27/01/2022 update
A new bot to disalow DataForSeoBot
![image](https://user-images.githubusercontent.com/29259906/151322584-91354a2c-bccd-487c-be4c-2d0faf5b0dfb.png)
And add the disalow /javacsripts and /widgets/

- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/59

**Comment by syphax-bouazzouni** [comment]
Issue resolved, there is no more bots calling  /feedback or /login in the access logs
