### ISSUE TITLE
Issues when automatically pulling new ontologies 

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#176]
Looking at the logs fixing #172 we can notice several issues with ontologies with pullLocation. 
I report them here : 

- GEMET : no parser is found for GEMET => not sure the script "knows" it is a SKOS format and does not require OWLAPI parser. New version is available (4.2.3) but not taken by pull script. Side note : I am currently working on adding the missing version manually
- FOBI : parsing error in the OWL API parsing. Reported to FOBI GitHub : https://github.com/pcastellanoescuder/FoodBiomarkerOntology/issues/6
- CO_347 : error with latest submission reported here #175 
- BIODIVTHES : it seems the script tries to reach out something not defined (pullLocation is null)

For memory, command to check the logs.
cd /srv/ontoportal/ncbo_cron/logs/
tail -n 10000 scheduler-pull.log

**Comment by syphax-bouazzouni** [comment]
Todo : 

- [x] https://github.com/agroportal/documentation/issues/188
- [x] https://github.com/agroportal/documentation/issues/189
- [ ] https://github.com/agroportal/documentation/issues/191

**Comment by syphax-bouazzouni** [comment]
@jonquet for the GEMET case, i tested doing a manual pull in console and it's says that there is not a new version. Did you do manual update by your self ?
![image](https://user-images.githubusercontent.com/29259906/151192270-51122608-c20c-46d7-b33a-74113dd83fb1.png)

**Comment by syphax-bouazzouni** [comment]
I close this issue,  will continue the track of the remaining issue with NCBITAXON here: https://github.com/agroportal/documentation/issues/191
