### ISSUE TITLE
AGROVOC does not pull automatically and does not parse anymore

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#178]
Since July 2021 version, AGROVOC does not parse anymore.

<img width="671" alt="Capture d’écran 2022-01-11 à 17 58 51" src="https://user-images.githubusercontent.com/7379183/148987329-c0acf4fb-97a8-453c-8eba-ba8f6f221a62.png">

Plus, we have a pullLocation for AGROVOC  : 
http://data.agroportal.lirmm.fr/ontologies/AGROVOC/submissions/16?display=pullLocation
But the ontology never get updated automatically (I have to do it manually each month). 

January or February release is expected soon to make new tests.

**Comment by syphax-bouazzouni** [comment]
## AGROV issue diagnostic
### State of last submission
### See status 
![image](https://user-images.githubusercontent.com/29259906/150804374-5bdd78e3-af56-42b4-89da-13189b1b06c7.png)
### See logs
AGROV last submission log file can be found at this path :  /srv/ontoportal/data/repository/AGROVOC/16/parsing.log 
### Conclusion from logs
the error is an **java.lang.OutOfMemoryError**, like what we see in the screenshot above (where we restarted the parsing of the last submission)
![image](https://user-images.githubusercontent.com/29259906/150806440-0be1c927-018d-4a7d-bb51-f51fcaf2397d.png)

**Comment by syphax-bouazzouni** [comment]
# AGROV issue diagnostic (follow)
## The problem
AGROVOC can't be parsed because of an OutOfMemoryError
## Solutions
### 1 - it's an owl api issue so it's needs to be transfered to there repo (todo)
### 2-  i tried to change the format of the file from nd to nt and it's seems to work 
it don't work with http://agrovoc.uniroma2.it/latestAgrovoc/agrovoc_lod.nq.zip
but works with http://agrovoc.uniroma2.it/latestAgrovoc/agrovoc_lod.nt.zip
![image](https://user-images.githubusercontent.com/29259906/150820595-71646976-0607-42ee-865f-eba6e981dd50.png)

but we have a new problem 
![image](https://user-images.githubusercontent.com/29259906/150825320-fd0614e3-b159-4a8a-a016-403e4cdc5364.png)

**Comment by jonquet** [comment]
I recall we had an issue with parsing the AGROVOC files with the OWL-API (see email discussion sept 2020) because of an import of the RDFS triples. 
For sure this was fixed in the nq version that we used to parse until July 2021. I am not sure we ever parse the nt file. 

I am focusing on the OutOfMemory error for now.

**Comment by jonquet** [comment]
Relevant post about the issue: 
https://stackoverflow.com/questions/52712321/outofmemoryerror-when-joining-a-list-of-strings-in-java 

It seems the OWL-API tries to create a string too large.

**Comment by jonquet** [comment]
Error (OutofMemory) reproduced  by @jvendetti when parsing (the nq file) "outside" of AgroPortal stack. 
Note: the nt file parse.

**Comment by jonquet** [comment]
An update : 
- In Protégé the .nt version opens
- In AgroPortal the .nt version parses and a 877M owlapi.xrdf file is generated. However next parsing step fails because of next error. This situation was reproduced outside of AgroPortal too. 

````
rapper: Serializing with serializer ntriples
rapper: Error -  - XML parser error: Char 0xFFFF out of allowed range
rapper: Error -  - XML parser error: PCDATA invalid Char value 65535
rapper: Failed to parse file /srv/ncbo/repository/AGROVOC/1/owlapi.xrdf rdfxml content
rapper: Parsing returned 8673139 triples
````
When generating a RDF/XML file with Protégé and re-opening this same file with Protégé the error shows up again, but this time with a line number : 
<img width="793" alt="image" src="https://user-images.githubusercontent.com/7379183/158989017-1430359c-dbd5-406e-a80a-3137c161f234.png">

Which bring us to the URI : http://aims.fao.org/aos/agrovoc/xDef_8f48da66

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/7379183/158989472-975d5b77-77f8-4d45-afad-a3be33bf3825.png">

**Comment by jonquet** [comment]
Fixing the character allow parsing. 
We encounter then another issue described in the log : 

<img width="1598" alt="image" src="https://user-images.githubusercontent.com/7379183/159041759-5c56c0a7-de50-4e0f-a9a0-e481d42d6264.png">

Probably linked to the recent changes on indexing fields.

**Comment by syphax-bouazzouni** [comment]
indexing error fixed here https://github.com/ontoportal-lirmm/goo/commit/ba27011fd2b093ff04d522477010d146602d0b62

Agrovoc is now parsed, indexed but we had this issue in the diff process https://github.com/agroportal/documentation/issues/246

So I don't think that the automatic pull will work, to follow up in the future  releases here https://github.com/agroportal/documentation/issues/251
