### ISSUE TITLE
a view that hasn't submissions

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#184]
This http://agroportal.lirmm.fr/ontologies/CROPUSAGE_FR has no submissionsIs **is it normal ?**

**Comment by syphax-bouazzouni** [comment]
to remove https://github.com/agroportal/documentation/issues/185
May be we need to list the others that are in the same case

**Comment by jonquet** [comment]
CROPUSAGE_FR is the only concerned as of now. Closing after checking with @syphax-bouazzouni .
