### ISSUE TITLE
remove  CROPUSAGE_FR

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#185]

**Comment by jonquet** [comment]
Oui confirmé. On peut la supprimer (voir notes Cellule curation avril 2021)

**Comment by syphax-bouazzouni** [comment]
Problem : https://github.com/ncbo/ontologies_linked_data/issues/127

**Comment by syphax-bouazzouni** [comment]
https://github.com/ncbo/ontologies_linked_data/issues/127 resolved and CROPUSAGE_FR deleted

### Used Script
```
[ontoportal@agroportal ncbo_cron]$ bin/ncbo_ontology_delete -o CROPUSAGE_FR
```
### Result
```
Deleting ontology: CROPUSAGE_FR
Deletion details are logged to deletions.log 
```

In deletions.log
```
I, [2022-02-10T16:28:42.383088 #31900]  INFO -- : Ontology deleted: CROPUSAGE_FR
```
