### ISSUE TITLE
see why GEMET is not parsing

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#188]
## Problem
no parser is found for GEMET => not sure the script "knows" it is a SKOS format and does not require OWLAPI parser. New version is available (4.2.3) but not taken by pull script. Side note : I am currently working on adding the missing version manually (source: Clement)
## Do a manual pull (in console
There no new version 
![image](https://user-images.githubusercontent.com/29259906/151510324-6aaeac12-49fa-4fd7-babe-595b34e58f11.png)

## Logs

**Comment by syphax-bouazzouni** [comment]
related https://github.com/ncbo/ontologies_linked_data/issues/124

**Comment by jonquet** [comment]
I have checked in the logs also for Jan 17th (last version uploaded) and the automatic pull did not catch a new version that day. Which certainly means that we uploaded it manually. 

=> I am closing this issue for the moment and we will need to monitor what's happening in a few months when a new version will be available here https://www.eionet.europa.eu/gemet/en/changes/
