### ISSUE TITLE
"Something went wrong screen" after new submission

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#190]
The submission of a new submission (for an existing ontology or a completely new one) very very often ends up on a "Something went wrong" screen, whereas in the back end the file has been properly loaded and/or the submission has been added to the queue for processing. 

Recently experienced with uploading submission 26 of CO_347.

**Comment by syphax-bouazzouni** [comment]
Yes, it was a very annoying to receive mails, that tell us that their submission went wrong while it was well submitted.
It was yet tracked here : 

- [x]  https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/15

**Comment by jonquet** [comment]
Situation occurred today with CO_359

**Comment by syphax-bouazzouni** [comment]
For the case of CO_359, the error didn't occur in stageportal
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/29259906/153414948-b5c572f8-8846-4c41-ac16-f1ef7ba9d3b4.png">

So it's specific at Agroportal.
@jonquet is there any demo ressource in Agroportal that i can remove then add to test ?

**Comment by jonquet** [comment]
Use EFO  (#207)
We are missing all the versions since 3.3 : https://github.com/EBISPOT/efo/releases?page=5
Il y a de quoi faire des tests !

**Comment by syphax-bouazzouni** [comment]
Follow here. : https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/15

**Comment by syphax-bouazzouni** [comment]
Origin https://github.com/agroportal/documentation/issues/51
