### ISSUE TITLE
0ntologies diagnostics (January 2022)

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#192]
### CMD used
```
[ontoportal@agroportal 20220124143731]$ bin/ncbo_ontology_diagnostics.sh 
```
# Result 

- [x] #195
- [x] #196
- [x] #197
- [x] #198
- [x] #199
- [x] #200
- [x] #213

**Comment by jonquet** [comment]
Je viens de relancer le processing de
<img width="527" alt="Capture d’écran 2022-01-28 à 11 31 47" src="https://user-images.githubusercontent.com/7379183/151531688-c3939a78-769e-4287-b17b-335b363a6768.png">

**Comment by jonquet** [comment]
Today manually re-process metrics (with bin/ncbo_ontology_metrics) for: 
ATOL, CO_334, ANT, INFRARISK, CVO, THESAE, OWSD, CO_345
=> all ontologies have metrics now except NCBITAXON (which does not parse)

**Comment by jonquet** [comment]
Friday Fev 4th : 
bin/ncbo_ontology_process -o THVIANDE,THESAE,GECO,GAO,DSW,CO_360,CO_358, CO_350
=> It seems AgroPortal general bug has generated "ERROR_RDF" issues for almost all these ontologies

**Comment by jonquet** [comment]
Monday Fev 7th : 
bin/ncbo_ontology_process -o GECO,GAO,DSW,CO_360,CO_358, CO_350,CO_324,CO_327,CO_330,CO_337,CO_338,CO_339,CO_340
and 
THESAE

**Comment by syphax-bouazzouni** [comment]
follow up https://github.com/agroportal/project-management/issues/342
