### ISSUE TITLE
Enhance SKOS parsing and handling in BioPortal / AgroPortal

### ISSUE THREAD

**Issue by antool** [agroportal/project-management#20]

**Comment by jonquet** [comment]
Co-assigning @syphax-bouazzouni as we are re-opening SKOS handling questions in AgroPortal.

**Comment by syphax-bouazzouni** [comment]
current state see: https://www.bioontology.org/wiki/SKOSSupport

**Comment by jonquet** [comment]
This is related to #258 and #259

**Comment by syphax-bouazzouni** [comment]
@jonquet I let you close this issue if you think it is done. Else extract relevant information in a new issue that references this one for clarity.

**Comment by jonquet** [comment]
Most of the aspect related to SKOS are handled in the AgroPortal 2.4 release. 

I think we only need to capture the bug related to Annotator semantic expansion somewhere else (I will do), then we are good to close this. Done => https://github.com/ontoportal-lirmm/ncbo_annotator/issues/26

**Comment by jonquet** [comment]
I am
