### ISSUE TITLE
GAO has parsed but can't display 

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#205]
Parsed yesterday. in the context of addressing #192 
But can't be visualized today
http://agroportal.lirmm.fr/ontologies/GAO

**Comment by syphax-bouazzouni** [comment]
the probelem is in the value of the version property, it's an interger where it must be a string

<img width="836" alt="image" src="https://user-images.githubusercontent.com/29259906/153390755-e3b7ca78-f8b1-4107-b4c6-6aef87a4437d.png">

**Comment by syphax-bouazzouni** [comment]
Resolved using the ncbo_cron --console, by changing the submission version from 1 (integer) to "1.0" (string)
<img width="836" alt="image" src="https://user-images.githubusercontent.com/29259906/153394063-44dc74e0-22e9-46e4-bde0-0802bcc993ab.png">

**Comment by jonquet** [comment]
Yes this issue has occurred in the past. If the ontology explicitly declares the version as an Integer datatype we can't cast it as a String and then it generate this bugs. Could you @syphax-bouazzouni register that as a specific issue on the relevant repo?
