### ISSUE TITLE
Re-deploy  ncboproxy project 

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#206]
The ncboproxy project was a Java proxy created during the OpenMinTed project. It was a generalization of the Annotator proxy for all services in the OntoPortal API. 

This is about redeploying this.

**Comment by syphax-bouazzouni** [comment]
Todo : 

- [x] Do a deploy script
- [x] Deploy on Stageportal

**Comment by syphax-bouazzouni** [comment]
NCBO proxy is re-deployed at this url http://services.stageportal.lirmm.fr/ncbo_proxy/  to test (@jonquet )

**Comment by jonquet** [comment]
The following URL should be functional : 
http://services.stageportal.lirmm.fr/ontologies/?format=omtd-share&apikey=xxx

Why is the service deplyaed with _ in the name ? shall it meet the requirements?

**Comment by syphax-bouazzouni** [comment]
I did deploy it in the **/ncbo_proxy** path, because i think we should to follow our pattern of http://services.stageportal.lirmm.fr/{service_name}/ and do not do an exception for ncbo proxy.

And the _ in the name, is a requirements of URLs naming that can't have spaces

**Comment by jonquet** [comment]
Ok perfect. Closing the issue after testing positively.

**Comment by jonquet** [comment]
For memory, testing URL on AgroPortal
http://services.agroportal.lirmm.fr/ontologies?format=omtd-share

(we need to fix the time out issue) 
(and check BioPortal)

**Comment by syphax-bouazzouni** [comment]
To fix : 

- [x] Remove time out issue
- [x] Re deploy in Bioportal
