### ISSUE TITLE
Parse MEAT-T and remove THVIANDE

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#209]
### Source :
 slack from @saubin78 
## Original request:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/29259906/153828074-cc1aeb01-59e6-4804-91ba-4cd202a5a8f9.png">

## The problem
META-T contain errors in the file that don't allow parsing (**see errors.log in  /srv/ontoportal/data/repository/MEAT-T/1/errors.log**)

## Todo

- [x] Fix the errors in the MEAT-T file
- [x] remove THVIANDE

**Comment by jonquet** [comment]
@saubin78 
Voici les erreurs identifier par @syphax-bouazzouni 
``````
lineNumber: 2099; columnNumber: 3; The element type “skos:definition” must be terminated by the matching end-tag “</skos:definition>”

Encountered ” <FULLIRI> “<?xml version=\“1.0\” encoding=\“UTF-8\“?> “” at line 1, column 1. Was expecting one of:  “Ontology” ... ,  “Prefix” ...

 IRI included an unencoded space: ‘32’ [line 1]

<?xml version=“1.0” encoding=“UTF-8"?>' at line 1 column 1.  Expected either ‘Ontology:’ or ‘Prefix:’

Unexpected character (‘<’ (code 60)): expected a valid value (number, String, array, object, ‘true’, ‘false’ or ‘null’) at [Source: (BufferedReader); line: 1, column: 2]

Encountered “” at line 1, column 1.

LINENO: 1 - Could not find tag separator ‘:’ in line. LINE: <?xml version=“1.0” encoding=“UTF-8"?>

Encountered ” “>” “<?xml version=\“1.0\” encoding=\“UTF-8\“?> “” at line 1, column 1.
``````

Je confirme que le fichier ne s'ouvre pas dans Protégé (donc ne se parse pas avec l'OWL-API)

<img width="898" alt="image" src="https://user-images.githubusercontent.com/7379183/154080592-a590fe6a-ca36-418c-93a5-51b1647e9aa3.png">
****

**Comment by saubin78** [comment]
Salut
Merci pour vos retours et bons conseils. Je confirme qu'il est nécessaire de passer le thésaurus dans Protégé et d'en faire un export pour avoir le bon format (par ailleurs, il y avait des erreurs grossières dans mon fichier, j'ai dû faire une fausse manip et couper du contenu)
J'ai encore qq ajustements à faire pour charger une version définitive en prod.

**Comment by saubin78** [comment]
ca passe sur stageportal http://stageportal.lirmm.fr/ontologies/MEAT-T  mais pas en prod http://agroportal.lirmm.fr/ontologies/MEAT-T 
Le fichier n'est pas parsé http://data.agroportal.lirmm.fr/ontologies/MEAT-T/submissions/1/download?apikey=30968836-a520-4ae5-9da8-892a643349f1
Pouvez-vous regarder ce qu'il se passe ? merci

**Comment by saubin78** [comment]
Après quelques minutes, il semble que ce soit passé sur la prod aussi. Il affiche bien les classes. Par contre, sur la page Summary, il montre toujours une erreur au niveau de la soumission
![image](https://user-images.githubusercontent.com/18008698/154728603-bdffd2a0-139f-4912-b612-8b2246fab681.png)
Je complèterai les métadonnées asap

**Comment by jonquet** [comment]
De notre coté cela s'affiche bien et c'est bien parsé: 
http://agroportal.lirmm.fr/ontologies/MEAT-T/?p=summary

Il a l'air niquel ce thèsaurus ;)

Fin des logs il y a 8 mlinutes suelement :
`[2022-02-18T17:55:56.227051 #1516]  INFO -- : ["Completed caching ontology: MEAT-T (....`

@saubin78 pense a vider ton cache du navigateur si tu ne vois pas le résultat.

**Comment by saubin78** [comment]
Super ! 
Merci à tous les deux, les labels sont mieux gérés dans Agroportal :-) avec toute la hiérarchie en anglais
J'espère que ce thésaurus s'enrichira bientôt de mappings.
Bon week-end

**Comment by syphax-bouazzouni** [comment]
De rien @saubin78 , merci a vous d'utiliser Agroportal.

J'ai supprime aussi THVIANDE et ferme cette issue.
