### ISSUE TITLE
0ntologies diagnostics (January 2022) - Ontologies with DIFF ERROR

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#213]
# From the Admin UI
- [x] SMLC-TEST => fixed after reprocessing
- [x] LPT
- [x] CO_020
- [ ] AFEO => first it was an error in the previous submission that didn't had an ontology file (see https://github.com/agroportal/documentation/issues/226)   
- [x] GEMET 
- [x] CO_121
- [x] SOY => fixed after reprocessing 
- [x] OEEV => fixed after reprocessing 
- [x] SOSA => fixed after reprocessing 
- [x] AGROVOC => Problem present but another issue is pen #178 
 
# Problem diagnostic 
## See Logs of the ncbo_ontology_process script 
Using the script `bin/ncbo_ontology_process -o AFEO -t diff` (e.g with AFEO) we can see that diff process fails with no details

```
Performing diff failed.  Reason: null
```

## Using the source code of bubastis
We can found the source code here : https://github.com/EBISPOT/bubastis

And after enabling the exception printing, we can see : 

### Error type 1:  Update owlapi 

- [ ] Update  owlapi from 4.5.8 to 4.5.17

### Error type 2: Missing imports 
For the case of

- [x] #231

### Error type 3: Ziped files 

- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/12

### Error type 4: Output folder not found
For those ressources
- CO_020
- CO_121

- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/13

 
### Error type 5: Can't parse the previous versions
- [x] #232

**Comment by jonquet** [comment]
- For the problem of missing imports the suggestion is to create a complimentary/additional error status that will be triggered when the missing import is detected during parsing and that will explicitly inform the admin user of the problem.   
Up to us to know that we need to fix missing imports before addressing diff issues.  https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/14

- For the problem of zip files => we need to patch the code to test if this is a zip file before transferring to bubastis.

- For the problem of previosu version => case by case fix the previous versions if they really don't parse

**Comment by syphax-bouazzouni** [comment]
The diff errors were resolved.
It is still only AFEO, we continue its specific tracking their https://github.com/agroportal/documentation/issues/231
Same for the new feature request of https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/14
