### ISSUE TITLE
Identify ontologies with multilingual label not explicitly tagged with language tag

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#221]
Ontologies with multilingual labels (as declared by the corresponding metadata property): 

- [x] AGROVOC
- [ ] GEMET
- [ ] PO2
- [ ] E-PHY
- [x] ANAEETHES
- [ ] GACS
- [ ] CROPUSAGE
- [ ] OEPO
- [ ] BIOREFINERY
- [ ] ASCOPAIN-T
- [ ] CO_357
- [ ] LANDVOC
- [ ] GECO
- [ ] BIODIVTHES
- [ ] OWSD
- [ ] LEXEAU
- [ ] PPDO
- [ ] THESAE
- [ ] OEEV
- [ ] TRANSMAT
- [ ] GAO
- [ ] WHEAT_TAX
- [ ] SFWO
- [ ] MEAT-T / THVIANDE
- [ ] DURUM_WHEAT
- [ ] INI-RDM (spanish)

**Comment by syphax-bouazzouni** [comment]
What is next with this ? @jonquet

**Comment by jonquet** [comment]
This is a data curation issue. Once ontologies with multilingual label not explicitly tagged with language tag will be identified, we should notify their authors to modify their source file. 
This is requirement for multilingual support in AgroPortal.

**Comment by syphax-bouazzouni** [comment]
No news for 2 years, and no more required for multilingual support

**Comment by jonquet** [comment]
Indeed. Will assume this is working and up to curation team to double check the metadata values not filled in by owners. Issue is not relevant anymore I believe
