### ISSUE TITLE
ANAEETHES have errors in labels language tags 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#224]
![image](https://user-images.githubusercontent.com/29259906/155283284-9aa2c33d-33e7-4f3e-ad8d-8d5adea475a3.png)

**Comment by syphax-bouazzouni** [comment]
The admin of the ontology (christian.pichot) was notified by @jonquet.
And waiting for there response.

**Comment by syphax-bouazzouni** [comment]
@jonquet Any news about this?

**Comment by jonquet** [comment]
ANAEETHES developper re-contacted.

**Comment by jonquet** [comment]
From Christian in October : 
oui, c'est corrigé dans 'notre' Vocbench.​ Y a t il lieu (possibilité) d'effectuer la correction au sein d'AgroPortal ?

**Comment by syphax-bouazzouni** [comment]
@jonquet on fait quoi ici, de coup au final ?

**Comment by jonquet** [comment]
This issue can be closed. 
Seems AgroPortal handles it now quite well: 
<img width="527" alt="Capture d’écran 2023-12-19 à 18 31 49" src="https://github.com/agroportal/project-management/assets/7379183/23e96b3d-4d2c-41e5-a337-ad67edf3f5e2">

And in addition the next version of ANAEETHES shall have the fix as stated by Christian.
