### ISSUE TITLE
pb loading thesaurus DATA4CPLUS

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#225]
Hi, 
Julien has loaded a new version of http://agroportal.lirmm.fr/ontologies/DATA4CPLUS but the parsing has failed again.
Can you send me the logs please ?

**Comment by jonquet** [comment]
Hello. Il y pas de log significatif coté AgroPortal car le fichier ne parse pas. 
Cela n'a pas l'air d'etre du RDF/XML valide 

Voila la 1ere erreur de Protégé : 

<img width="589" alt="image" src="https://user-images.githubusercontent.com/7379183/155504974-9cbe6ba6-236a-4c7c-b319-5e249c302b97.png">

Et les lignes correspondantes:  

<img width="747" alt="image" src="https://user-images.githubusercontent.com/7379183/155504947-c01d13b2-0fa7-4e29-938b-491f884e4fbe.png">

Le dernier fichier uploadé peut être récupéré avec : 
http://data.agroportal.lirmm.fr/ontologies/DATA4CPLUS/submissions/1/download?apikey=2ae6878b-a599-4cee-8224-e8efaf6f610e

**Comment by saubin78** [comment]
Bonjour,
le fichier est chargé et on peut visualiser l'arborescence. Par contre, quand on clique sur un concept, un message d'erreur s'affiche : 
![image](https://user-images.githubusercontent.com/18008698/155958706-39bd05cc-bab4-4105-bf02-e3663fa636a5.png)
Je ne comprends pas de quoi il s'agit. 

Sophie

**Comment by syphax-bouazzouni** [comment]
Bonjour,

Merci d’avoir soulevé ce problème, c’est pas lié a votre ressource mais plus un bug chez nous.

Nous allons le corriger au plus vite,

A suivre ici https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/65

**Comment by syphax-bouazzouni** [comment]
Re bonjour @saubin78,

1.  J'ai fait un hotfix pour ne plus etre spammer par l'alert de datatables (https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/b412eba0ce456cb6b4084cdb58ebbc68f8963bac) , maintenant vous pouvez parcourir l'arborescence sans problème. 
2. Par contre j'ai toujours pas trouver la source du problème mais sûrement lié a ce que je décrit ici https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/65 (le topConcept "http://data4c-plus.net/admin/thesaurus/read/0") n'est pas défini dans votre thesaurus)
3. Améliorer notre prise en charge des ressources en SKOS fait partie de nos priorités dans les prochains mois

**Comment by saubin78** [comment]
Merci Syphax. Je pense que le topConcept /read/0 est une bonne piste. La personne qui génére le fichier est en congés cette semaine. Nous referons des tests prochainement et te tiendrons au courant pour désactiver le hotfix et vérifier que tout est bon. 
Excellente nouvelle pour l'amélioration de la prise en charge du SKOS. Vous pouvez compter sur nous pour tester :-)

**Comment by jonquet** [comment]
Apres le dernier chargement du fichier le 7 mars sans le /read/0 cela semble bien indexé et il n'y a plus  d'erreur. 

Reste juste les metrics a relancer.

**Comment by syphax-bouazzouni** [comment]
J'ai relancer les metrics manuellement  pour cette ressources.

Pour une raison que nous avons pas encore identifié dans certain cas les metrics ne sont pas calculer automatiquement ( suivre ici https://github.com/agroportal/documentation/issues/204) .
