### ISSUE TITLE
Discuss and document the changes made in our codebase from 2016

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#228]
### Our gap with NCBO codebase

- [ ] Owlapi wrapper - code gap documentation (1 file)
- [ ] Goo - code gap documentation(5 files)
- [ ] OLD - code gap documentation (16 files)
- [ ] NCBO annotator - code gap documentation
- [ ] Ontologies api - code gap documentation (19 files)
- [ ] Ruby api client - code gap documentation (4 files)
- [ ] UI - code gap documentation (~200 files)
- [ ] NCBI cron - code gap documentation (8 files)

**Comment by jonquet** [comment]
Please update based on the recent meeting discussions.

**Comment by syphax-bouazzouni** [comment]
The documentation produced: 
* Annotator works: https://doc.jonquetlab.lirmm.fr/share/eb82cfc3-53e6-40c8-9bb4-44676b3f3b57 
* Metadata: https://doc.jonquetlab.lirmm.fr/share/c705b38b-c343-421a-845d-69066aaf842b
* Mappings: https://doc.jonquetlab.lirmm.fr/share/28a6384e-60b5-4045-b988-b7f003487355

The remaining details are in the release notes from 2016 to 2020 https://doc.jonquetlab.lirmm.fr/share/d77f1b99-60fb-4fdb-982b-927204f1c1e3
