### ISSUE TITLE
AFEO Could not load imported ontology

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#231]
Can't do the diff step because could not load  an imported ontology : 
```
Could not load imported ontology: <http://www.mistea.supagro.inra.fr/ontologies/2016/v4/ontofp> Cause: www.mistea.supagro.inra.fr
```

**Comment by syphax-bouazzouni** [comment]
The missing imports is not detected in the parsing step because we have set in the **SILENT strategy for missing imports** in owlapi (see https://github.com/ncbo/owlapi_wrapper/commit/1fea316e7f1ff21937e588aef62bdeded506055d)

**Comment by syphax-bouazzouni** [comment]
A mail was sent by @jonquet for the administrator of the resource (@annetireau), waiting for here response to proceed

**Comment by jonquet** [comment]
This has been fixed by @annetireau and the new version has parsed. 
Metrics failed on the first parsing but succeed after manual script. 
Closing.
