### ISSUE TITLE
SKOS topConcept display

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#233]
Hi,
in INRAETHES (on stageportal), there is a general ConceptScheme (the thesaurus) and several microthesauri. A concept can be at the same time topConceptOf a microthesaurus and have a broader concept in the whole thesaurus. Ex:   
![image](https://user-images.githubusercontent.com/18008698/156139718-1924c44c-2365-4fef-b28b-d8062cf0d12a.png)

When uploaded in Agroportal, these concepts appear at the root while only topConceptOf the general thesaurus should
![image](https://user-images.githubusercontent.com/18008698/156140149-af864c71-0809-41c0-b5d2-b08b00d1f2a2.png)

I suspect that Agroportal considers only the existence of the hasTopConcept even if the subject is not the main Concept Scheme (i.e. the INRAE thesaurus). Could you check this please?

**Comment by jonquet** [comment]
Suggestion (by email) was : 

- Keep the micro-thesauri but create a more concise hierarchy
- Create a skos:Concept for each  65 micro-thesauri and attach each topConcept to the relevant micro-thesaurus concept
-  Get rid of the topConcept declarations to the main thesaurus 

For instance :

<rdf:Description rdf:about="http://opendata.inrae.fr/thesaurusINRAE/mt_15">
          <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#ConceptScheme"/>
(…)
          <skos:prefLabel xml:lang="fr">ENV déchets </skos:prefLabel>
          <skos:prefLabel xml:lang="en">ENV waste</skos:prefLabel>
</rdf:Description>
 
ADD
<rdf:Description rdf:about="http://opendata.inrae.fr/thesaurusINRAE/mt**c**_15">
          <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#**Concept**"/>
          <skos:prefLabel xml:lang="fr">ENV déchets</skos:prefLabel>
          <skos:prefLabel xml:lang="en">ENV waste</skos:prefLabel>
          **<skos:topConceptOf rdf:resource="http://opendata.inrae.fr/thesaurusINRAE/mt_15"/>**
</rdf:Description>
AND
<rdf:Description rdf:about="http://opendata.inrae.fr/thesaurusINRAE/mt_15">
          <skos:prefLabel xml:lang="fr">ENV déchets **micro-thesaurus** </skos:prefLabel>
          <skos:prefLabel xml:lang="en">ENV waste  **micro-thesaurus** </skos:prefLabel>
          <skos:hasTopConcept rdf:resource="http://opendata.inrae.fr/thesaurusINRAE/mt**c_15**">
</rdf:Description>
AND DELETE iltalic line
<rdf:Description rdf:about="http://opendata.inrae.fr/thesaurusINRAE/c_4616">
          _<skos:topConceptOf rdf:resource="http://opendata.inrae.fr/thesaurusINRAE/thesaurusINRAE"/>_
          <skos:topConceptOf rdf:resource="http://opendata.inrae.fr/thesaurusINRAE/mt_15"/>
</rdf:Description>

**Comment by saubin78** [comment]
Bonjour. Nous avons fait ce que tu proposais dans le mail. Notre problème n'est pas complètement résolu car Agropoportal affiche à la racine des concepts qui ne sont pas topConcept du thésaurus. Peut-on le contraindre là-dessus ?

**Comment by jonquet** [comment]
Yes the behaviour suspected is certainly true : as AgroPortal does not manage ConceptScheme it probably does not make a difference between your "main" thesaurus and the micro-ones. 
However, this is not necessarily a bug. If AgroPortal would only consider the topConcept of the main thesaurus there will be no way to display see the other micro-thesaurus in the UI. 

My suggestion from last time was to ALSO create a Concept to identify/named the ConceptScheme. 
(see first line after ADD). By doing so, AgroPortal will display at the Root all the "ConceptSchemes" : in capital one will see the topConcepts of the main concept scheme and then under (not named as chapter (ENV déchets **micro-thesaurus**) the other micro thesaurus.

**Comment by jonquet** [comment]
After discussion and considering the micro-thesaurus are "included" in the main thesaurus hiearchy, the visualization of the hierarchy of INRAETHES should not show the micro-thesauri. 

This will be addressed by fixing issue #258
