### ISSUE TITLE
Metadata "Used ontology engineering tool" : consider multiple values

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#235]
It happens that several tools are used to develop a semantic resource. 
What is important for the user ? 
- to know which tool produced the shared file ? -> only 1 value allowed  OR 
- to know all the tools that were used during the creation process? --> several allowed

**Comment by jonquet** [comment]
This is a fair remark. Many properties in AgroPortal metadata model are not list where as they should be: 
http://data.agroportal.lirmm.fr/submission_metadata

The main reason for this was that we found a quite significant bug when changing the metadata model that would make the processing time explode (cartesian product) when metadata properties are list. 
In some case we have implemented a "concatenate" approach but not in the case of **usedOntologyEngineeringTool**

Do this for usedOntologyEngineeringTool would be the short term better fix. 
It will result in : 
"Protégé, VocBench"
or "URL1, URL2" if the user has used URL to identify the tools. 
What do you think?

**Comment by syphax-bouazzouni** [comment]
Done 

![Image](https://github.com/agroportal/project-management/assets/29259906/3f4f58f6-e349-41a3-9d95-c2a48cea3bd5)
