### ISSUE TITLE
Metadata : abstract

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#236]
What would be the difference between "abstract" and "description" ?
What information is expected in each ?
I'd suggest removing "abstract" which brings confusion

**Comment by jonquet** [comment]
Strangely the 2 properties come from DCT. Dublin Core might have judge that they could be potentially useful. So I did certainly in 2016. 

Abstract | DCTERMS: A summary of the resource.

Description | DCTERMS: An account of the resource. Description may include but is not limited to: an abstract, a table of contents, a graphical representation, or a free-text account of the resource.OMV: Free text description of an ontology.

In AgroPortal, We have been using the abstract field several times: 
http://data.agroportal.lirmm.fr/submissions/?display=description,abstract&display_links=false&display_context=false

Could you revise and precise your opinion? 
I am not strongly in favour of keeping "abstract" but then what would we do for the ontologies using it.

**Comment by saubin78** [comment]
Looking at data shows that people tend to provide more detailed information in Abstract.
One way to deal with this may be to enhance the contextual help (pop up when mouse over the question mark).  "A summary of the ontology", indicate something like "Use this field to provide additional information about the ontology"
In fact, we may consider changing several contextual help to facilitate the user filling the metadata. Instructions instead of a description of the metadata element may be more useful in a number of cases. See https://github.com/agroportal/project-management/issues/113 for instance
Sophie

**Comment by jonquet** [comment]
Oui tout cela sera capturer dans le retactoring de la page Summary; https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/75

**Comment by syphax-bouazzouni** [comment]
> Oui tout cela sera capturer dans le retactoring de la page Summary; [ontoportal-lirmm/bioportal_web_ui#75](https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/75)

Is it? if no . Please refine the work to be done, in a list of requirements.

**Comment by jonquet** [comment]
I was kind of ok to remove this property (at least from AgroPortal) untill I look a @hibadjebabria169 figure: 

Values in AgroPortal: [http://data.agroportal.lirmm.fr/submissions?&display=abstract](http://data.agroportal.lirmm.fr/submissions?&display=abstract&display_links=false&display_context=false&apikey=528c4e4a-5c3e-4798-a2e2-11d96761b8ce)
Populated ratio: 37/159 => 23%

=> I would then leave it like this for now. Untill we have another set of remarks. In the new UI abstract will not be part of the main properties.
