### ISSUE TITLE
EO preferredNamespacePrefix metadata field can't be updated

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#247]
http://data.agroportal.lirmm.fr/ontologies/EO/submissions/6

"preferredNamespacePrefix": "plant_experimental_conditions_ontology",
=> "eo"

Generate a 502

**Comment by syphax-bouazzouni** [comment]
Updated the value with no issue. Close as the issues seem to no longer be there.
<img width="694" alt="image" src="https://github.com/user-attachments/assets/18f43671-b652-417b-a064-3606c9b0a3bd">
