### ISSUE TITLE
Add AgBioData group to some ontologies

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#249]
We need to assign the AGBIODATA (Consortium of Agricultural Biological Databases) to 

- [x] GO
- [x] SO
- [x] TO
- [x] PATO
- [x] PO
- [x] PR
- [x] VT

and then 

- [x]  refresh the groups and slices with http://data.agroportal.lirmm.fr/slices/synchronize_groups

Following bug prevent to do the edits: 
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/66

**Comment by syphax-bouazzouni** [comment]
Done by @syphax-bouazzouni (after fixing https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/66)

Waiting for validation of @jonquet

**Comment by jonquet** [comment]
Closing. Connectinng to AgBiodata for a refresh of the group/slice.
