### ISSUE TITLE
Some ontologies have a lot of submissions which causing big loading time

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#250]
The list below are ontologies that have a lot of submissions, causing big  loading time (and even timeout errors)

- GO (raise timeout error if caches cleared https://github.com/agroportal/documentation/issues/248)  => 200 submissions !!!!
- SO => 94 submissions

**Comment by syphax-bouazzouni** [comment]
@jonquet any thought about this?

**Comment by jonquet** [comment]
I have cleanned out ontologies from time to time, removing some submissions and keeping only "one per month" for ontologies too often updated.

**Comment by syphax-bouazzouni** [comment]
Fixed with https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/192
