### ISSUE TITLE
Mapping graphical visualization

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#252]
Hi,

It looks like http://agroportal.lirmm.fr/mappings  is not working when "Visualization" mode is chosen 👍 
![image](https://user-images.githubusercontent.com/18008698/159868512-813b5b33-5653-4e90-9885-a1a45d0234d6.png)

while "table" mode does
![image](https://user-images.githubusercontent.com/18008698/159868614-bd472af7-8b1a-4a16-b008-fc8782728f00.png)

**Comment by jonquet** [comment]
This is an old feature that need to be assess. I don't recall what was supposed to be here. 
Note: similar behaviour at NCBO BioPortal.

**Comment by syphax-bouazzouni** [comment]
The feature is dead since 2017 , see https://github.com/ncbo/biomixer/issues/3

**Comment by syphax-bouazzouni** [comment]
The old mappings visualization was hidden since 2.3.0 (2022), and [upgraded to a new UI](https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/538), coming in the next release 2.7.5 (or 2.8.0)  in the next month.
