### ISSUE TITLE
Curate the organization declaration in metadata field to harmonize landscape tag cloud

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#253]
The tag cloud on the Landscape page contains non harmonized values for e.g. INRA / INRAE  / IRSTEA etc... 

<img width="549" alt="image" src="https://user-images.githubusercontent.com/7379183/159960218-0309d4c4-00ea-41be-84ff-991bdcfdcbb0.png">

We need to curate the metadata.

**Comment by saubin78** [comment]
This is on purpose indeed. We chose to keep track of historical names (Irstea and INRA) for resources that have not been updated since 2020, January 1st. 
This can be discussed if  it's not in line with Agroportal's recommendations

**Comment by jonquet** [comment]
This will have to be addressed after #113 and harmonization of the 3 fields concerned with ROR ids.

**Comment by syphax-bouazzouni** [comment]
Fixed as now we display only the name of the organizations
![image](https://github.com/agroportal/project-management/assets/29259906/1e5fdc39-0de2-421a-98a4-51d7e65645e9)

**Comment by jonquet** [comment]
Top. Next iteration will wait for the remodeling of the landscape page. 
We will certainly take all 8 agent properties and do a cloud with orga only and do another cloud with person only.
