### ISSUE TITLE
change the name of the documentation repo to project-management 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#256]
We will change the name of this repo to "**project-management**", and its main purpose will be to store all our generic issues about the Agroportal project

In this repo, we will have three types of issues

- **Feature request issues (with the labels: bug, feature request, enhancement)**: these issues are requirements/specifications of fixes or new features to implement.
- **Support/documentation issues (with the labels: question, documentation)**: these issues will be subjects/questions to write and document in http://doc.jonquetlab.lirmm.fr/ 
- **Project management issues (with the label Project management)**: these issues are just project management artifacts/helpers, one of the main use cases is to gather a group of related **feature request issues** in a unique parent issue that represent the project of implement it. Those project issues will help us to follow the progression of the implementation.

**Comment by syphax-bouazzouni** [comment]
@jonquet do you confirm the name change?

**Comment by syphax-bouazzouni** [comment]
Validated and done

**Comment by jonquet** [comment]
OK as discussed offline. Note only that we should keep the "content" label too.
