### ISSUE TITLE
Short term hierarchy enhancement for SKOS vocabularies including multiple Concept Schemes

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#258]
## Problem 
When a SKOS vocabulary contains several skos:ConceptScheme AgroPortal build the hierarchy tree displaying at the root all the concepts with a skos:topConceptOf declaration. 

For instance INRAETHES in stageportal (see discussion #233)
<img width="344" alt="image" src="https://user-images.githubusercontent.com/7379183/161239782-4cc6c977-11e0-4a9a-b428-6a1784247c99.png">

## Requirement
We already require (for metadata extraction, but also as a good practice) that ONE skos:ConceptScheme (that would be the main one, including the other ones) be also declared owl:Ontology. This allow to consider the concept scheme as the main object and grab the metadata annotation properties.

## Proposed solution
Display in the hierarchy tree only the top concepts of the main concept scheme (i.e. the one which is alos declared owl:ontology).

**Comment by syphax-bouazzouni** [comment]
## Some context and references 

- **Adding the ontology IRI:** In the [generating RDF](https://github.com/ontoportal-lirmm/ontologies_linked_data/blob/master/lib/ontologies_linked_data/models/ontology_submission.rb#L878) step of the ontology process we add the following triple "<http://bioportal.bioontology.org/ontologies/URI> owl:versionInfo <ONTOLOGY_IRI>" (we can found in the code here https://github.com/ontoportal-lirmm/owlapi_wrapper/blob/268aad5e8831d3f83ee12ae195e52afb526d180e/src/main/java/org/stanford/ncbo/oapiwrapper/OntologyParser.java#L146). Than this ontology is used for [extracting the meta](https://github.com/ontoportal-lirmm/ontologies_linked_data/blob/master/lib/ontologies_linked_data/models/ontology_submission.rb#L1187)
- **Fetching the roots on an ontology:** for the case of SKOS we are fetching the roots concepts by fetching all the top Concepts using this [SPARQL query](https://github.com/ontoportal-lirmm/ontologies_linked_data/blob/master/lib/ontologies_linked_data/models/ontology_submission.rb#L2219)  

# Solution
Change the SPARQL query that is fetching the top Concept from 
```SQL
SELECT DISTINCT ?root WHERE {
GRAPH #{self.id.to_ntriples} {
  ?x #{RDF::SKOS[:hasTopConcept].to_ntriples} ?root .
}}
```
To 
```SQL
SELECT DISTINCT ?root WHERE {
GRAPH #{self.id.to_ntriples} {
  #{self.ontology_uri.to_ntriples} #{RDF::SKOS[:hasTopConcept].to_ntriples} ?root .
}}
```
With this new query the fetched top concepts will be only from the owl:Ontology

**Comment by syphax-bouazzouni** [comment]
Done in testportal
<img width="1569" alt="image" src="https://user-images.githubusercontent.com/29259906/161929061-9c9b6a1f-4daf-4f99-9044-6354efd65a8b.png">

**Comment by saubin78** [comment]
brilliant! Thanks a lot Syphax!

**Comment by syphax-bouazzouni** [comment]
Fixed with https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/22
