### ISSUE TITLE
Handling multiple Concept Scheme in SKOS resource

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#259]
Going further what is proposed in #258 this feature request specifies what to do when a SKOS resource contains multiple skos:ConceptScheme. 

Especially, the idea is to adapt the hierarchy tree to "preselected" concept schemes. I.e., only display in the hierarchy concepts that are included in the concept scheme preselected. This requires a new UI component, certainly nearby the "Details" tab, that will allow to display all the existing concept schemes (if any) in a SKOS resource (but maybe also available for OWL ontologies that are also using SKOS) and select the one to display in the hierarchy. 
By default, only the main concept scheme shall be display.

**Comment by jonquet** [comment]
This behaviour is inspired by VocBench as illustrated in the following figures: 

_Selection of the scheme to display:_ 
![image001](https://user-images.githubusercontent.com/7379183/161242305-92531a8d-3046-471d-8fed-f3ed1e748a45.png)

_Display of only the "main concept scheme" selected above:_ 
![image002](https://user-images.githubusercontent.com/7379183/161242426-86d16f56-f526-4bcf-9232-497024cf53b2.png)

_Same with several concept schemes: _
![image004](https://user-images.githubusercontent.com/7379183/161242526-08578642-a98b-41fb-bc61-01652db485a3.png)

![image005](https://user-images.githubusercontent.com/7379183/161242581-fd9fe3ac-6b54-4d93-9d64-6eb0c7da3c8b.png)

**Comment by syphax-bouazzouni** [comment]
Done with https://github.com/agroportal/project-management/issues/262

**Comment by saubin78** [comment]
Hi!

**Comment by saubin78** [comment]
Hi! I 've uploaded a new file for Thesaurus INRAE in StagePortal https://stageportal.lirmm.fr/ontologies/INRAETHES/?p=classes 
It looks great but there is a little things that does not seem to work properly : when I open the Class tab for the 1st time, the topConcepts of ALL the conceptSchemes appear (not only the top concepts of my main scheme).
Yet, stagePortal seems to "know" that my main Scheme is ThesaurusINRAE. When I clic on Filter, I can see this : 
![image](https://user-images.githubusercontent.com/18008698/234914927-e7d9ca13-515f-4fa2-9666-6fb99a55ea5b.png)
After that, when I play with the Filter and display a microthesaurus only, or the INRAE thesaurus only, it looks fine.
