### ISSUE TITLE
indexing not done in the submission process

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#261]
Source : slack 
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/29259906/161716952-3a6bbfeb-ee66-4812-8b5a-a64fee9a9148.png">

**Comment by syphax-bouazzouni** [comment]
It seems that after reprocess indexing, it is working
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/29259906/161717306-b00a7294-2a72-432a-aceb-d4ef20952d85.png">
but clicking on [tomate - French Crop Usage (Classification des plantes cultivées en France en fonction des usages) (CROPUSAGE)](http://agroportal.lirmm.fr/ontologies/CROPUSAGE?p=classes&conceptid=http%3A%2F%2Fontology.inrae.fr%2Ffrenchcropusage%2FTomates) gives an error 
<img width="1765" alt="image" src="https://user-images.githubusercontent.com/29259906/161717489-7199c623-e973-4e32-8453-c5bcb8dc75e6.png">

**Comment by jonquet** [comment]
J'avais cependant relancé moi-meme le parsing avec le script general /ncbo_ontology_process
Peut etre nous devrions verifier si il inclus bien l'étape d'indexation. Et si oui pourquoi c'est pas passé.

**Comment by syphax-bouazzouni** [comment]
This was surely an issue, with the languages indexing. FCU has two labels for the concept `tomato`, in English but also in French `tomate`.

The indexed value, maybe randomly chosen. So sometimes it can be found using English keywords and others with French one.

Anyway, I close this,  as we can't debug this more.
