### ISSUE TITLE
Enhance the portal to support SKOS

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#262]
### Requirements : 
- https://github.com/agroportal/project-management/issues/20
- https://github.com/agroportal/project-management/issues/258 
- https://github.com/agroportal/project-management/issues/259

### Schemes part

Todo : 
- [x] Add skos:ConceptScheme model (+ tests)
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/27
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/81
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/24
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/22
- [x] Filter tree view roots by concepts scheme
- [x] In the UI tree view add a select field to choose what concepts scheme to show
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/73#event-6438004344
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/72
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/84
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/83
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/43
- [x] Extract tree code into a module 
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/44
- [x] Add SKOS scheme model to the ontologies_api client
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/46
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/49
- [x] Fix in UI tree when expanding a concept children getting muted (grey color) by default
- [x] https://github.com/ontoportal-lirmm/ontologies_api_ruby_client/issues/6
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/51
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/112
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/113

### Collections part
Todo : 

- [x] Add the [`skos:Collection` class](https://www.w3.org/TR/skos-reference/#Collection) to the model (+ tests)
- [x] https://github.com/ontoportal-lirmm/ontologies_api/issues/20
- [x] Add the Collection filter to Concepts endpoint (will be the endpoint :collection/members)
- [x] Add a tab for Collections in the UI
- [x] Add UI to filter concepts by Collection 
- [x] Add SKOS collection model to the ontologies_api client
- [x] In the UI factorize the similar code between schemes, collections and concepts
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/45
- [x] Add a  filter in the tree view for collections (done with the attribute :isInActiveCollection)
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/98
- [x] Add icons in the concepts browsers (a tree icon for the hierarchy, and a list for the list)
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/103
- [x] show inCollection when we display=all for a concept
- [x] Hande resources that do not have collections
- [x] https://github.com/ontoportal-lirmm/ontologies_api_ruby_client/issues/6
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/51
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/112
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/54

### SKOS-XL labels part 

- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/47
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/48
- [x] Add the Labels endpoint (https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/47)
- [x] Add a UI component to display Label properties in the details tab especially `skosxl:literalForm`
- [x] Fix a bug in the link buttons (the ontology acronym is duplicated)
- [x] https://github.com/ontoportal-lirmm/ontologies_api_ruby_client/issues/6
- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/51
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/112

### Concept date sort

- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/50
- [x] https://github.com/ontoportal-lirmm/ontologies_api/issues/21
- [ ] https://github.com/ontoportal-lirmm/ontologies_api/issues/25
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/111
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/115

### use topConceptOf if no hasTopConcept found

- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/34

### Metadata part 

- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/33

**Comment by jonquet** [comment]
Note for later : when working on Collection we nend to remember that there are actually 2 type 
<img width="612" alt="image" src="https://user-images.githubusercontent.com/7379183/180447513-484f33d2-3855-4024-a0d1-f24e39df5e13.png">

**Comment by jonquet** [comment]
Little addition to this SKOS wish list : 
- A view to see the "news" based on the concept dates.
- A revised SKOS specific metrics in the Summary page.

**Comment by syphax-bouazzouni** [comment]
For next iterations

- [ ] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/33
- [ ] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/52
- [ ] revised SKOS-specific metrics in the Summary page
- [ ] Add the option to choose the Date property to use 
- [ ] https://github.com/ontoportal-lirmm/ontologies_api/issues/25
- [ ] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/46
