### ISSUE TITLE
Change Accrual Periodicity UI selection to suggest DC Collection Description Frequency Vocabulary

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#263]
## Background
The is a target vocabulary that can be used to encoded the "acrrualPeridocity" property. 
https://www.dublincore.org/specifications/dublin-core/collection-description/frequency/ 

## Enhancement
Change the UI selection for Accrual periodicity" to suggest the values from the above mentioned vocabulary (and encode the metadata with the corresponding URIs). 

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/7379183/162419561-47131060-f035-428f-b225-176f923fca72.png">

Like the "Natural langauage" property form which allows to select pre-set values or create a new one.

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/7379183/162419750-1a38c7e0-5b23-4f12-95a9-bf8645f1a0f2.png">

**Comment by syphax-bouazzouni** [comment]
was it done @jonquet ?

![image](https://github.com/agroportal/project-management/assets/29259906/4049b62b-45e4-467a-97bd-56223ee10cd6)

**Comment by jonquet** [comment]
Yes this was done. I just used it for VT. Could be closed.
