### ISSUE TITLE
Change default term in welcome page search box

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#264]
Let's use "plant height"

<img width="562" alt="image" src="https://user-images.githubusercontent.com/7379183/162428350-ad45b3ef-ad96-424f-913d-4e7b465a95f3.png">

**Comment by jonquet** [comment]
Another small. UI change : Also change the portal name and remove "LIRMM"

<img width="151" alt="image" src="https://user-images.githubusercontent.com/7379183/162429020-063ccad9-c933-48e1-9dba-d41c270c93ff.png">

**Comment by syphax-bouazzouni** [comment]
Done with https://gite.lirmm.fr/jonquetlab/bioportal-configs/-/commit/83d4b5086b875cd779f8a1ef77dd8209e4a6a0ec and https://gite.lirmm.fr/jonquetlab/bioportal-configs/-/commit/54f1d44453c1fb8238e06f7ae84a38c2da78aa4f
