### ISSUE TITLE
we need to think if we do a pull request of the /synchronize_groups with slices

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#272]
With https://github.com/ncbo/ontologies_api/pull/87 we will sync with the upstream still just to discuss if we need also the share synchronize_groups feature (https://data.agroportal.lirmm.fr/synchronize_groups)

**Comment by jonquet** [comment]
### Feature 

Update all slices to match the groups of the current appliance: create a new slice with the same parameters as the group if not existing, update the ontologies of the slice to match the ontologies of the group if already existing.
API Key of an administrator account required.
curl 	-X GET
	-H "Content-Type: application/json"
	-H "Authorization:apikey token=$APIKEY"
	http://data.agroportal.lirmm.fr/slices/synchronize_groups  

This feature was implemented by @vemonet to facilitate slice management after we took the "design" choice of having slice and groups aligned in AgroPortal (basically: slice are built out of ontologies that are in a group). We found it was more simple for users. 

@jvendetti @mdorf @graybeal @stdotjohn any thoughts ?

**Comment by graybeal** [comment]
I think that's a good design choice, it's much easier to understand.

I assume it  eliminates the ability to use a group orthogonally to a slice you were in  We'd have to double-check on BioPortal what slices are not synchronized to the same-named group and if any, see if we can tell why that is or who would care.  It will be unfortunate if a hardcore user sees a critical-to-them feature disappear, but maybe we'll get lucky and no conflicts exist.

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal/ontologies_api/pull/5
