### ISSUE TITLE
Add the Priority and Difficulty properties to all the issues

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#273]
The issue is a remember and a tracker for us to **set the priorities and difficulties** for our existing and future issues. 
For information, the **priorities" are set by the functional/business team and the difficulties by the developers team

### How to 
Go to the project tabs (in the left panel, below the labels) and set the project, then click on the "+2 more" to have the option to set the priorities and difficulties
![image](https://user-images.githubusercontent.com/29259906/170219506-5062b655-5541-482a-9ec0-1fa3dc348d18.png)

**Comment by jonquet** [comment]
Ahh celui la était tjrs dans ma todo list pourtant. Bon il est vrai que notre nombre d'issue à exploser avec notre généralisation de GitHub et que c'est devenu dur de tous les monitorer. Mais bon je pense qu'on trouve d'autres moyens de gérer les priorités. Puis on a pris aussi l'habitude de sélectionner la complexité et la priorité des nouvelles issues, donc petit à petit celles sans affectations vont disparaitre.
