### ISSUE TITLE
CGO parsing failing notifications than success

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#276]
The 09 June 2022, Common Greenhouse Ontology (CGO) was processed and in a short time, we had successively three notifications. Two with Error_rdf status and the last with parsed successfully.

**Comment by jonquet** [comment]
I did manually trigger the parsing. 
There was an issue with the pullURL and eventually a second submission was wrongly created. I fixed the submission folder and the pullURL. 

Now the resource is properly parsed.
