### ISSUE TITLE
AGROVOC latest version does not have skos:hasTopConcept

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#280]
related https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/78

**Comment by syphax-bouazzouni** [comment]
AGROVOV PullLocation got updated today with the correct URL (that contains the skos:hasTopConcept relations) 

Waiting for the automatically pull job, to see the follow-up

**Comment by jonquet** [comment]
Updated submission number 25 today to as 24 is not the latest anymore.
