### ISSUE TITLE
Multilingual support: UI Internationalization

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#309]
### Technical 
- [x] Make  all the text of the portal multilingual (in the start French and English) 
- [x] Make the portal detect and use automatically the local language (depending on the IP of the request) 
- [x] Save the users settings in his local browser session 

### Content 

- List all the hard-coded terms in the views, [here](https://docs.google.com/spreadsheets/d/1Swi0Qbfhb6ge1a0fgNPuGIBYWLWRCULGHtqpQ3QCN-s/edit#gid=1190226258)
- Translate all the terms in French 
- Put all the translated terms in the fr.yml local file 

## Documentation
- [Rails Internationalization (I18n) API](https://guides.rubyonrails.org/i18n.html)
- http://www.lirmm.fr/~jonquet/publications/documents/Article_MSW4_MultilingualBioPortal.pdf

**Comment by jonquet** [comment]
I would move the discussion in an older issue (one of the older!) #215 
For the pleasure of closing old issues ;)

**Comment by jonquet** [comment]
Discussed today. 

Possible way to select a language up right corner:

![image](https://user-images.githubusercontent.com/7379183/228623221-0aff2c7a-8335-4663-976c-36868b42f2e0.png)

**Comment by jonquet** [comment]
After release 2.7 with work from @haddadzineddine and @syphax-bouazzouni on the abstraction of the text fields into the 'locales' files, lets make another round chasing the sentence here and there not yet in French. 
@SirineMhedhbi Shall find them and put hem in the locales files with basic translation 
@jonquet Shall verify/correct/harmonize the translation to French

**Comment by syphax-bouazzouni** [comment]
Below are all items listed the our [2023/9 New UI - Stageportal/AgroPortal - TEST - Google Sheets](https://docs.google.com/spreadsheets/d/1lEdrxJKKOJYbSYH_Ptzu2dUliHAKcFTirrw8vs9Hcuk/edit#gid=713725591&fvid=1197518333) that migrated here:

Title | Part | Type | Author / Date
-- | -- | -- | --
Je ne trouve pas d'information m'expliquant comment fonctionne le "recommandateur". Je pense que pourrait etre utile pour mieux comprendre comment l'utiliser | Multilingual | Improvement Feedback | nina / 09-11-23
Show/Hide advanced options Du Recommender et Annoator en anglais pas traduit. | Multilingual | Content change | nina / 09-11-23 + Clement
Changement de "login" par "connexion" ? Sur la page Login | Multilingual | Content change | nina / 09-11-23
Raw data (sur le modal de details d'unc concept d'un search resiult) n'est pas traduit. | Multilingual | Aesthetic change | Clement / 20-11-23
Toutes les expressions du process de recuperation de mot de passe ne sont pas traduites | Multilingual | Content change | Clement / 23-11-23
Metrics>Page landscape pas traduits | Multilingual | Content change | Clement / 23-11-23
Footer pas traduit | Multilingual | Content change | Clement / 23-11-23
Exact Matches dans page Search pas traduit | Multilingual | Content change | Clement / 23-11-23
Search language et All language dasn la page Search | Multilingual | Content change | Clement / 23-11-23
French et English dans le menu deroulatn de la page Search | Multilingual | Content change | Clement / 23-11-23
(i) sur FAIR scores de la Home page | Multilingual | Content change | Clement / 23-11-23
Message Welcome admin feature page Browse | Multilingual | Content change | Clement / 23-11-23
Tous les filtres et les menus de la page Browse | Multilingual | Content change | Clement / 23-11-23
3 des 4 indications de la fennetre de chargement de mappings en bullk | Multilingual | Content change | Clement / 23-11-23
Tous les champs de la fenetre de seections des ontologies quand on clique sur "Selectionner dans la liste" | Multilingual | Content change | Clement / 23-11-23
Show/Hide advanced options de la page de l'Annotator => apparait la premiere fois puis quand onc lique desuss reste en anglias | Multilingual | Content change | Clement / 23-11-23
Les valeurs none et all des menus deroulant des options de l'Annotator | Multilingual | Content change | Clement / 23-11-23
LEs deux titres "ontologies properties" de la page landscape | Multilingual | Content change | Clement / 23-11-23
Tous les textes des interfaces des composants O'FAIRe => je ne parle pas des questions qui pourrnt etre fait separament | Multilingual | Content change | Clement / 23-11-23
La page admin et ces sous pages | Multilingual | Content change | Clement / 23-11-23
Toute le contenu de la page Summary (nom des blocs et texte explicatifs et texte generés par l'UI) | Multilingual | Content change | Clement / 23-11-23
Les titres des Tab de la la page Summary | Multilingual | Content change | Clement / 23-11-23
Les titres des Tab d'un concept donné | Multilingual | Content change | Clement / 23-11-23
Les menus et autres titres des sous tab pour un concept donné | Multilingual | Content change | Clement / 23-11-23
La page my acocount et edit personnal info | Multilingual | Content change | Clement / 23-11-23
Bouton Watch | Multilingual | Content change | Clement / 23-11-23
Page feedback | Multilingual | Content change | Clement / 23-11-23
Upload success view not translated | Multilingual | Content change | Clement / 24-11-23
Il faudrait mieux définir le terme "Parcourir" pour qu'il ne soit pas confondu avec "rechercher dans stageportal" | Top nav | Improvement Feedback | nina / 09-11-23
tous les intitulés de rubriques ne sont pas traduits en français dans le bandeau vert (je sais, ce n'est pas toujours évident) | Top nav | Improvement Feedback | Sophie / 09-11-23

**Comment by saubin78** [comment]
@syphax-bouazzouni there seems to be some issues displaying the content of the ontology depending on the UI language chosen.
We noticed the case for https://agroportal.lirmm.fr/ontologies/INRAETHES which is 100% French and 81% English.

Surprisingly, when selected language is French, some French labels don't show :  
![image](https://github.com/agroportal/project-management/assets/18008698/a81afeb4-aca8-4d1d-820a-524314a183ad)
For concept c_13078, the RDF file contains this line:
<rdf:Description rdf:about="http://opendata.inrae.fr/thesaurusINRAE/c_13078">
	<skos:prefLabel xml:lang="fr">carbone renouvelable</skos:prefLabel>
</rdf:Description>

When choosing "All languages", the French labels reappear
![image](https://github.com/agroportal/project-management/assets/18008698/f54b82e0-d38a-46e9-88bd-f000171cc0f4)

**Comment by syphax-bouazzouni** [comment]
> @syphax-bouazzouni there seems to be some issues displaying the content of the ontology depending on the UI language chosen. We noticed the case for https://agroportal.lirmm.fr/ontologies/INRAETHES which is 100% French and 81% English.

@saubin78, fixed in https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/128 if it's not the case, please continue the discussion in this issue https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/127,

**Comment by syphax-bouazzouni** [comment]
Moved to https://github.com/agroportal/project-management/issues/621
