### ISSUE TITLE
Distinguer les differentes propriétés des classes

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#31]
L'idée serait de changer la façon dont sont afficher les propriétés des classes.
Il faudrait sans doute: 
1. Séparer les propriétés générales d'AgroPortal, c'est à dire:
   "id", "prefLabel", "definition", "synonym", "obsolete", "subClassOf", "parents", "cui", "semanticType", "label", "notation", "prefixIRI", "xref"
   N'afficher que celle qui ont une valeur (autre que par défaut ou null) et les afficher d'une certaine manière.
2. Afficher les autres propriétés avec un "+" qui sont spécifique au vocabulaire, dans un autre bloc graphique. Pour ces propriétés donner le nom de la propriété au format ns:nom e.g., skos:prefLabel ou rdfs:label
   (si nécessaire il existe un outil pour obtenir les abréviations classiques pour un name space : http://prefix.cc/)

3.Offrir la possibilité en un clic d'obtenir le JSON-LD pour ce concept. C'est quand même vachement pratique quand on veut passer de l'UI à l'API.

**Comment by jonquet** [comment]
Le 1 est abordé dans https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/86
Le 2 aussi, sauf l'aspect de l'utilisation du short namespace qui n'est pas trivial. A discuter. 
Le 3 existe désormais. Il s'agirait juste de changer le bouton "Access class JSON" par une petit icone qui sera unifiée dans toutes les vues.

**Comment by syphax-bouazzouni** [comment]
1 et 3 fait.
2 pas fai mais deplacer ici https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/383
