### ISSUE TITLE
Update AgroPortal footer

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#314]
- [ ] Change OntoPortal link to "OntoPortal Alliance"  and move it to ABOUT section 
- [ ] Remove NCBO Widgets link
- [ ] Add OntoPortal link to https://github.com/ontoportal
- [ ] Change API button link to http://data.agroportal.lirmm.fr/documentation
- [ ] Chanqe documentation link to https://github.com/agroportal/project-management (the README will contain the link to jonquetlab)
- [ ] Move Cite US link to the ABOUT section

**Comment by syphax-bouazzouni** [comment]
Why not the documentation link directly to https://doc.jonquetlab.lirmm.fr/share/e6158eda-c109-4385-852c-51a42de9a412.

We will have http://agroportal.lirmm.fr/ -> https://doc.jonquetlab.lirmm.fr/share/e6158eda-c109-4385-852c-51a42de9a412.

**Comment by syphax-bouazzouni** [comment]
Also if we think about working on the footer we need to start of thinking of how we can make it customisable for the alliance folks

### Agroportal
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/29259906/202496386-2ebac36c-2264-4c28-b344-e38738674ad1.png">

### Bioportal 
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/29259906/202496488-e3528d5c-f95a-45d2-ba1b-16a10d8a9dc4.png">

### Industryportal
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/29259906/202496653-cb602151-c770-49e8-aa7c-f382ee51080b.png">

### Ecoportal
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/29259906/202496824-2ba4b210-7491-415c-84d9-910faca36d7c.png">


### Matportal

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/29259906/202496956-635d2b6c-a16b-4ee1-b7bf-296f3cf43573.png">

### Medportal

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/29259906/202497167-e4e0b879-9a67-4981-9ded-335a3a22be77.png">
