### ISSUE TITLE
Q/A remarques de Sophie (saubin) (INRAE DipSO) sur les fonctionnalités SKOS de la release 2.4

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#315]
Source slack 

### Content
> Pourquoi les Topconcepts (domaines) ne sont pas affichés dans l’ordre dans l’affichage à droite quand on est placé sur ThesaurusINRAE (main)?

On ne peut pas trop fixer ça (pour le moment) car il n'y a pas d'ordre. 
Clement: Les skos:ConceptScheme ne sont pas dans une structure ordonnée. Pour le moment on pourrait juste afficher dans l'ordre alpha-numerique de leurs labels.

> Est-ce qu’on pourrait distinguer visuellement les concepts créés de ceux qui ont été modifiés ?

Oui, c’est noté. 

> Pourquoi ces mappings sont de type « external » (external à quoi ? il faudra clarifier cette notion, à mon avis).

Oui, faudra penser à donner une indication aux utilisateurs du sens des types de mappings ou pointé vers   une doc (@jonquet), 

- https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/118

>Les concepts ont un mapping avec eux-mêmes. C’est habituel ?

Oui, un bug qu’on ne peut pas regeler pour le moment.

> Afficher l’URI sur tous les concepts comme sur adaptation écologique ; 01.ENVIRONNEMENT n’en a pas, deadwood non plus

Un bug.

- https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/115

> Agroportal ne récupère pas le label pour pour thésaurus INRAE sur la propriété inScheme et hasTopConcept (ça marche pourtant pour le concept scheme Domaines) (01.ENVIRONNEMENT)

Le scheme thesaurusINRAE n’a pas de label (skos:prefLabel ou rdfs:label) 
Clement: @saubin78 a vous de l'ajouter dans les versions à venir.

> Les définitions sont des objets réifiés avec une valeur et une source. Pour l’instant, seule l’URI de la définition s’affiche. Ex : acclimatation
Est-ce que vous affichez toutes les propriétés renseignées ou faites-vous une sélection. Par exemple, si une ressource a une skos:note, est-ce qu’elle sera affichée ?

Pour le moment, non.

-  https://github.com/agroportal/project-management/issues/316
- https://github.com/agroportal/project-management/issues/240

> Affichage des narrower : sur certains concepts (ex : natural resource) et sur d’autres non (01.ENVIRONNEMENT). Je sais que cela vient des données mais ça me pousse à vous suggérer un pré-traitement possible sur les données qu’on charge : Agroportal pourrait générer les relations inverses pour les propriétés SKOS concernées : broader/narrower (inverse of), related (symetric). Cela améliorerait la cohérence des données affichées et serait un petit service en plus pour améliorer la qualité.

Pour faire ça faut changé le fichier (la ressource) d’origine et c’est pas le rôle d’agroportal / ontoportal (d’après @jonquet)
Clement: c'est la boite de Pandore que je préfère pas ouvrir. On ne produit pas trop les triplets manquants sauf si c'est exigé par le modèle commun a toutes les resources dans AgroPorta (e.g., prefLabel).

> Agroportal semble chercher dans toutes les ressources hébergées (peut-être quand il ne trouve pas dans la ressource). Par exemple, si je cherche « thyroid » et que je clique sur un des résultats, j’obtiens ce message.

Oui c’est un bug dans stageportal (l’autocomplétion ne marche pas) ,

-  https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/117

> La hiérarchie à gauche est longue : quand on descend, on ne voit plus le haut de la section droite de l’interface avec les infos de la ficher concept. Si c’était possible de faire suivre ce contenu de droite quand on descend, ce serait plus facile pour l’utilisateur.

Oui, 

- https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/116

> Pourquoi avoir des infos redondantes entre la partie haute et la partie basse d’une fiche de concept ? j’ai l’impression qu’il s’agit d’une section générique pour owl et skos. Le problème, c’est qu’on présente les infos 2 fois et en plus de manière incohérente. Par exemple, dans la partie haute, le terme français (arbre mort) est présenté comme un « Synonym » du terme anglais (deadwood) dans la partie haute. Et comme altLabel dans la partie basse (où on voit que le prefLabel en français est bois mort). Peut-être qu’Agroportal prend le synonyme français parce qu’il n’en trouve pas en anglais. Pas facile la gestion de la langue dans l’interface… :wink:

Oui, c’est un gros problème qu’on a, qu’on ne peut pas pour le moment résoudre. 

- https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/86

**Comment by saubin78** [comment]
> Pourquoi les Topconcepts (domaines) ne sont pas affichés dans l’ordre dans l’affichage à droite quand on est placé sur ThesaurusINRAE (main)?

> On ne peut pas trop fixer ça (pour le moment) car il n'y a pas d'ordre.

> Clement: Les skos:ConceptScheme ne sont pas dans une structure ordonnée. Pour le moment on pourrait juste afficher dans l'ordre alpha-numerique de leurs labels.

Ce serait bien d'afficher dans l'ordre alpha-numerique de leurs labels mais ça n'est pas prioritaire

**Comment by jonquet** [comment]
Il me semble que c'est fait désormais.. ou j'ai pas compris ;)

Collections : 
<img width="323" alt="Capture d’écran 2023-04-05 à 12 20 53" src="https://user-images.githubusercontent.com/7379183/230183279-a9ee1cfe-0722-4d40-a522-f6935d2e3365.png">

Scheme : 
<img width="347" alt="Capture d’écran 2023-04-05 à 12 21 17" src="https://user-images.githubusercontent.com/7379183/230183362-a94ee805-f4b5-4100-92cf-4072da4949ba.png">

**Comment by jonquet** [comment]
@saubin78 De maniere plus générale, est-ce qu'on peut fermer ce ticket si tout est traité?

**Comment by saubin78** [comment]
Il s'agit des topConcept qui se trouvent ici :
![image](https://user-images.githubusercontent.com/18008698/231091361-5e1cc848-d331-40df-8416-d20e8f1242ab.png)

Mais on peut fermer ce ticket

**Comment by syphax-bouazzouni** [comment]
Close as outdated, and moved to smaller issues.
