### ISSUE TITLE
Implement Statuscacke for ontoportal-lirmm

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#317]
### Context

See discussion https://github.com/ontoportal/ontoportal-project/discussions/2#discussioncomment-4141966 

### Requirements

- [x] Create an account in StatusCacke (called ontoportal-lirmm, with a randomly generated password) @haddadzineddine 
- [x] Define a list of endpoints to tests (we have 10 free) @jonquet 
- [x] Send downtime alerts to  agroportal-support@lirmm.fr @haddadzineddine 
- [x] Write documentation of how we did it (in markdown) and add it to https://doc.jonquetlab.lirmm.fr/doc/agroportal-public-documentation-QMpsC9aVBb

**Comment by syphax-bouazzouni** [comment]
For example, their are the endpoints tested by Bioportal

- http://data.bioontology.org/ontologies/GAZ/classes/?include=prefLabel,hasChildren,created,synonym,definition&page=1&pagesize=50
- http://data.bioontology.org/ontologies/ICD10/classes/http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FICD10%2FA69.2/tree
- http://data.bioontology.org/ontologies/ICD10/classes/http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FICD10%2FA69.2/children
- http://data.bioontology.org/provisional_classes/?page=1&pagesize=50
- http://data.bioontology.org/ontologies/CEDARPC/provisional_classes/?page=1&pagesize=50
- http://data.bioontology.org/search?q=disease&also_search_provisional=true&valueset_exclude_roots=true&ontologies=ICD10&include=prefLabel,definition&page=1&pagesize=500&display_context=false&display_links=true
- http://data.bioontology.org/ontologies/FMA/classes/roots?include=prefLabel,hasChildren,created,synonym,definition
- http://data.bioontology.org/ontologies/BIBFRAME/properties/roots
- http://data.bioontology.org/search?q=delivery+procedures&also_search_provisional=true&ontology_types=VALUE_SET_COLLECTION&valueset_roots_only=true&include=prefLabel,definition&page=1&pagesize=500&display_context=false&display_links=true
- http://data.bioontology.org/search?also_search_provisional=true&valueset_roots_only=true&ontology_types=VALUE_SET_COLLECTION&ontologies=CEDARVS&page=1&pagesize=50
- http://data.bioontology.org/ontologies/CEDARVS/classes/http%3A%2F%2Fwww.semanticweb.org%2Fjgraybeal%2Fontologies%2F2015%2F7%2Fcedarvaluesets%23Study_File_Type?include=prefLabel,hasChildren,created,synonym,definition
- http://data.bioontology.org/ontologies/NLMVS/classes/http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FNLMVS%2F2.16.840.1.113762.1.4.1045.59/children?page=1&pagesize=5000&include=prefLabel,hasChildren,created,synonym,definition
- http://data.bioontology.org/property_search?q=title&page=1&pagesize=500&display_context=false&display_links=true
- http://data.bioontology.org/ontologies/BIBFRAME/properties/http%3A%2F%2Fid.loc.gov%2Fontologies%2Fbibframe%2FmainTitle
- http://data.bioontology.org/ontologies/BIBFRAME/properties/http%3A%2F%2Fid.loc.gov%2Fontologies%2Fbibframe%2Fdate/tree
- http://data.bioontology.org/ontologies/BIBFRAME/properties/http%3A%2F%2Fid.loc.gov%2Fontologies%2Fbibframe%2Fdate/children

**Comment by jonquet** [comment]
I would suggest to include the following URLs to test: 

- [x] http://agroportal.lirmm.fr/
- [x] http://agroportal.lirmm.fr/ontologies
- [x] http://agroportal.lirmm.fr/landscape
- [x] http://agroportal.lirmm.fr/search?q=plant%20height&ontologies=&include_properties=false&include_views=false&includeObsolete=false&require_definition=false&exact_match=false
- [x] http://services.agroportal.lirmm.fr/ofaire?ontologies=ATOL,EOL,AHOL&combined
- [x] http://data.agroportal.lirmm.fr/ontologies
- [x] http://data.agroportal.lirmm.fr/submissions
- [x] http://data.agroportal.lirmm.fr/ontologies/ANAEETHES/mappings
- [x] http://data.agroportal.lirmm.fr/annotator?text=There%20has%20been%20many%20recent%20studies%20on%20the%20use%20of%20microbial%20antagonists%20to%20control%20diseases%20incited%20by%20soilborne%20and%20airborne%20plant%20pathogenic%20bacteria%20and%20fungi,%20in%20an%20attempt%20to%20replace%20existing%20methods%20of%20chemical%20control%20and%20avoid%20extensive%20use%20of%20fungicides,%20which%20often%20lead%20to%20resistance%20in%20plant%20pathogens.%20In%20agriculture,%20plant%20growth-promoting%20and%20biocontrol%20microorganisms%20have%20emerged%20as%20safe%20alternatives%20to%20chemical%20pesticides.%20Streptomyces%20spp.%20and%20their%20metabolites%20may%20have%20great%20potential%20as%20excellent%20agents%20for%20controlling%20various%20fungal%20and%20bacterial%20phytopathogens.&ontologies=EFO,TO,ANAEETHES,ENVO,PATO,AGROVOC,AFO&longest_only=false&exclude_numbers=false&whole_word_only=true&exclude_synonyms=false&expand_mappings=false&fast_context=true&certainty=true&temporality=true&experiencer=true&negation=true&lemmatize=false&score_threshold=0&confidence_threshold=0&score=cvalueh&expand_class_hierarchy=true&class_hierarchy_max_level=1&display_links=false&display_context=false
- [x] http://services.agroportal.lirmm.fr/annotator?text=In%20agriculture,%20plant%20growth-promoting%20and%20biocontrol%20microorganisms%20have%20emerged%20as%20safe%20alternatives%20to%20chemical%20pesticides.%20Streptomyces%20spp.%20and%20their%20metabolites%20may%20have%20great%20potential%20as%20excellent%20agents%20for%20controlling%20various%20fungal%20and%20bacterial%20phytopathogens.&ontologies=EFO,TO,ANAEETHES,ENVO,PATO,AGROVOC,AFO&longest_only=false&exclude_numbers=false&whole_word_only=true&exclude_synonyms=false&expand_mappings=false&fast_context=true&certainty=true&temporality=true&experiencer=true&negation=true&lemmatize=false&score_threshold=0&confidence_threshold=0&score=cvalueh&expand_class_hierarchy=true&class_hierarchy_max_level=1&display_links=false&display_context=false

**Comment by syphax-bouazzouni** [comment]
@haddadzineddine can you complete this Issue and close it if finished

**Comment by jonquet** [comment]
Be sure to include a link to admin page in AgroPortal to go to Status ckae

**Comment by syphax-bouazzouni** [comment]
> Be sure to include a link to the admin page in AgroPortal to go to Status cake

And to write the correspondent doc (of how to use and access it) ,here https://doc.jonquetlab.lirmm.fr/doc/administration-guides-ts6ljG525K

**Comment by haddadzineddine** [comment]
todo : 

- [x] include a link to admin page in AgroPortal to go to Status cake
