### ISSUE TITLE
Add the possibility to export concepts to other format (CSV, Ntriples, JSON, ...)

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#324]
See skosmos https://skosmos.loterre.fr/JLC/fr/page/-XSQ2GXVV-X

![Image](https://github.com/agroportal/project-management/assets/29259906/b12340d1-5519-42ae-8657-d7bd39a2ef92)

**Comment by syphax-bouazzouni** [comment]
Not wanted

**Comment by jonquet** [comment]
Yes , indeed we prefer to offer the link to the API call for a class. Then someone can get the full source file.
