### ISSUE TITLE
Delete the agrold and rice groups and correpsonding slices. 

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#330]
We can delete the RICE and AGROLD groups. They are not really used and we use the notion of groups slightly differently now.

**Comment by syphax-bouazzouni** [comment]
Those groups are not empty and contain consecutively 23 and 6 ontologies.

![Image](https://user-images.githubusercontent.com/29259906/213664534-4bd4fa8e-ee4e-46ca-a0aa-43e2ca1fdd27.png)

Another problem is that there is no easy way (a script) to remove (or add and manage) groups

**Comment by jonquet** [comment]
Yes. But the groups are not used (AGROLD) and do not represent a relevant grouping anymore (RICE). 
We can delete the groups... and its the occasion to check if the metadata of each ontologies within these groups is automatically updated. 
Maybe we can save somewhere the list of the 6 and 23 ontologies, just in case we need to do this manually afterwards.

**Comment by syphax-bouazzouni** [comment]
in the API we have the following endpoints

- Display all groups: `get "/groups"`
- Display a single group `get '/groups/:acronym' `
- Create a group with the given acronym: put '/groups/:acronym'
- Update an existing submission of an group: `patch '/groups/:acronym' `
- Delete a group:  `delete '/groups/:acronym'`

Is it a good idea in the UI to add an admin panel to manage groups? @jonquet 

Otherwise, I will just remove them using the API

**Comment by syphax-bouazzouni** [comment]
I migrated the [old doc of Vicent about group/categories](https://drive.google.com/drive/u/2/folders/1hweU8UM823GrEV8Ik-qXLMuEd0ZT15L_) to this https://doc.jonquetlab.lirmm.fr/share/61da2094-6fa9-4d0c-8833-aa4f589ddbd0

**Comment by jonquet** [comment]
>Is it a good idea in the UI to add an admin panel to manage groups? @jonquet

Yes I think it will be necessary.  We would need a simple a UI to manage Groups, Categories and Slice.  Eventually this view will become a way to "setup" the portal and write the config files.

**Comment by syphax-bouazzouni** [comment]
You have now @jonquet , those UIs to manage the groups and remove agrold and rice, if not already done.

**Comment by jonquet** [comment]
Group RICE and AGRO-LD removed. 

@SirineMhedhbi Seems the Groups have been well erased
https://data.agroportal.lirmm.fr/groups/RICE
But, the ontologies still have the zombie assigned: 
https://data.agroportal.lirmm.fr/ontologies/CO_320?display=group

This is a bug I believed. 

@syphax-bouazzouni Can you clean up the code (old homepage listing maybe) and listing (HTTP redirects) for the corresponding 2 slices?

**Comment by syphax** [comment]
Hi, wrong syphax?

**Comment by syphax-bouazzouni** [comment]
Slices https://data.agroportal.lirmm.fr/slices, cleaned. 
For HTTP redirects it is on the level of STI-RX.
