### ISSUE TITLE
AFEO : impossible de supprimer la valeur erronée pour Natural Language / Idem OFPE

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#332]
Il y a une valeur erronée pour naturalLanguage 
http://data.agroportal.lirmm.fr/ontologies/OFPE/submissions/3?display=naturalLanguage

Qu'on arrive pas a enlever via l'interface ou meme des appels REST. 

<img width="486" alt="image" src="https://user-images.githubusercontent.com/7379183/207932448-53c280d2-2b91-4c45-b707-c8cdfd9745bb.png">

**Comment by jonquet** [comment]
Meme chose sur le champ "publisher de OFPE. 
Il faudrait le modifier pour indiquer : 
“MISTEA (https://www6.montpellier.inrae.fr/mistea), SPO (https://www6.montpellier.inrae.fr/spo/), IATE (https://umr-iate.cirad.fr/)”

**Comment by syphax-bouazzouni** [comment]
Recheck after merging this https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/161
