### ISSUE TITLE
Create a view with the evolutions of the home page statistics

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#333]
The proposition is to create a view : http://agroportal.lirmm.fr/statistics

That will be accessible from a link "More" at the bottom of the homepage statistics block (similar to the one on the visits block)

<img width="496" alt="image" src="https://user-images.githubusercontent.com/7379183/207933675-dd56ea31-70fe-4733-a45b-9229884f6fb6.png">

Ant that will open a specific page to show the same statistics but with their evolution since the begining of the AgroPortal project presented as diagrams / charts. E.g. 

<img width="494" alt="image" src="https://user-images.githubusercontent.com/7379183/207934557-7476f5f3-e112-44ec-8a1d-0f643ce4655f.png">

Currently, the statistics archive values are here : 
https://docs.google.com/spreadsheets/d/1Jx8lHfYXHA8elIlkmZ1AsPyRBUxYC-dQsSdcSqvRelc/edit#gid=1926671493
(Statistics tab)

Ultimatly the statistics should be automatically saved something like one a month and the diagrams on this new view will rely on htese values.

**Comment by syphax-bouazzouni** [comment]
Here do we get the data, if the evolution of Ontologies, Users,.... ? (Google Analytics)

**Comment by jonquet** [comment]
I can provide data for the past. 
For the future, we need to store them e.g., record a value every month.

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/428, can be revised after in the new landscape page iteration.
