### ISSUE TITLE
CGO n'affiche pas de mapping tandis qu'il y en a

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#336]
http://agroportal.lirmm.fr/ontologies/CGO/?p=mappings

<img width="492" alt="image" src="https://user-images.githubusercontent.com/7379183/207959496-d9be0ae9-7fe0-4b5c-b315-be3edc7a3451.png">

tandis que :http://agroportal.lirmm.fr/ontologies/CGO/?p=classes

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/7379183/207959576-279d2d6a-7ff2-47b1-9bc5-63f0882f560c.png">

**Comment by syphax-bouazzouni** [comment]
The API return also nothing 
http://data.agroportal.lirmm.fr/ontologies/CGO/mappings

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/29259906/208125918-98e60ea5-2e92-472b-876e-acafd21b9a67.png">

**Comment by syphax-bouazzouni** [comment]
Seems to be fixed 


![Image](https://github.com/agroportal/project-management/assets/29259906/280adade-f084-468f-88b5-93abd6f60623)
