### ISSUE TITLE
Modify user model to store GitHub and ORCID info

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#341]
I propose we put in our user model the user ORCID id and GitHub login. Both will be useful for several features. 
They must not be mandatory and must not be returned by the API by default (only with display=all). 

I would add them in the follwing view: 

<img width="396" alt="image" src="https://user-images.githubusercontent.com/7379183/208129465-c36cffd4-0d29-4ff2-9df2-0f3ae124c183.png">

**Comment by syphax-bouazzouni** [comment]
Done by https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/62



![Image](https://user-images.githubusercontent.com/29259906/214008047-020e4af7-b52e-4f98-a31c-8171f202bdb1.png)

The follow-up of the UIs will be here https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/130
