### ISSUE TITLE
Ontologies diagnostics (January 2023)

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#342]
# CMD used
```
[ontoportal@agroportal 20220124143731]$ bin/ncbo_ontology_diagnostics.sh 
```
# Result 

###  Ontologies missing a latest submission upload:

- http://bioportal.bioontology.org/ontologies/NCBITAXON

### Ontologies failing to parse, without RDF data ('ERROR_RDF','ERROR_RDF_LABELS'):

- http://bioportal.bioontology.org/ontologies/CL (submissionId=37, hasOntologyLanguage=OWL, submissionStatus=RDF,ERROR_RDF_LABELS,UPLOADED)

- http://bioportal.bioontology.org/ontologies/CO_357 (submissionId=58, hasOntologyLanguage=OWL ,submissionStatus=ERROR_RDF,UPLOADED)

- [x] https://github.com/agroportal/project-management/issues/353

### Ontologies with RDF data and METRICS has maxDepth == 0 && classesWithOneChild != 0 :

- http://bioportal.bioontology.org/ontologies/CO_715 (submissionId=3, hasOntologyLanguage=OBO, metrics=averageChildCount:4,classes:256,classesWithMoreThan25Children:1,classesWithNoDefinition:124,classesWithOneChild:8,individuals:0,maxChildCount:25,maxDepth:0,properties:2, submissionStatus=RDF,OBSOLETE,INDEXED_PROPERTIES,METRICS,RDF_LABELS,UPLOADED,ANNOTATOR,DIFF,INDEXED,INDEX_COUNT:256,ANNOTATIONS_AVAILABLE)

- http://bioportal.bioontology.org/ontologies/FOODEX2 (submissionId=2, hasOntologyLanguage=SKOS, metrics=averageChildCount:5,classes:10,classesWithMoreThan25Children:0,classesWithNoDefinition:5,classesWithOneChild:1,individuals:75222,maxChildCount:9,maxDepth:0,properties:119, submissionStatus=RDF,OBSOLETE,INDEXED_PROPERTIES,METRICS,RDF_LABELS,UPLOADED,ANNOTATOR,INDEXED,INDEX_COUNT:27894,ANNOTATIONS_AVAILABLE

- http://bioportal.bioontology.org/ontologies/GACS (submissionId=2, hasOntologyLanguage=SKOS, metrics=averageChildCount:4,classes:12,classesWithMoreThan25Children:0,classesWithNoDefinition:12,classesWithOneChild:1,individuals:584881,maxChildCount:6,maxDepth:0,properties:3, submissionStatus=RDF,OBSOLETE,INDEXED_PROPERTIES,METRICS,RDF_LABELS,UPLOADED,ANNOTATOR,DIFF,INDEXED,INDEX_COUNT:15444,ANNOTATIONS_AVAILABLE)

- http://bioportal.bioontology.org/ontologies/LANDVOC (submissionId=4, hasOntologyLanguage=SKOS, metrics=averageChildCount:3,classes:7,classesWithMoreThan25Children:0,classesWithNoDefinition:7,classesWithOneChild:1,individuals:7845,maxChildCount:5,maxDepth:0,properties:176, submissionStatus=RDF,OBSOLETE,INDEXED_PROPERTIES,METRICS,RDF_LABELS,UPLOADED,ANNOTATOR,DIFF,INDEXED,INDEX_COUNT:310,ANNOTATIONS_AVAILABLE)

### Ontologies with RDF data, without SOLR data:

- http://bioportal.bioontology.org/ontologies/CROPUSAGE ( submissionId=15, hasOntologyLanguage=SKOS, metrics=averageChildCount:2,classes:6,classesWithMoreThan25Children:0,classesWithNoDefinition:1,classesWithOneChild:2,individuals:707,maxChildCount:4,maxDepth:1,properties:32, submissionStatus=RDF,OBSOLETE,INDEXED_PROPERTIES,METRICS,RDF_LABELS,UPLOADED,ANNOTATOR,DIFF,INDEXED,INDEX_ERROR:missing,ANNOTATIONS_AVAILABLE)

- http://bioportal.bioontology.org/ontologies/EBO(submissionId=4, hasOntologyLanguage=OWL, metrics=averageChildCount:6,classes:332,classesWithMoreThan25Children:1,classesWithNoDefinition:332,classesWithOneChild:15,individuals:7,maxChildCount:168,maxDepth:4,properties:6, submissionStatus=RDF,OBSOLETE,INDEXED_PROPERTIES,METRICS,RDF_LABELS,UPLOADED,ANNOTATOR,DIFF,INDEXED,INDEX_ERROR:missing,ANNOTATIONS_AVAILABLE)

### Ontologies with RDF data, without ANNOTATOR status:

- http://bioportal.bioontology.org/ontologies/FOODON (submissionId=92, hasOntologyLanguage=OWL, metrics=averageChildCount:4,classes:34102,classesWithMoreThan25Children:137,classesWithNoDefinition:10472,classesWithOneChild:2644,individuals:435,maxChildCount:1017,maxDepth:33,properties:68, submissionStatus=RDF,OBSOLETE,ERROR_ANNOTATOR,INDEXED_PROPERTIES,METRICS,RDF_LABELS,UPLOADED,DIFF,INDEXED,INDEX_COUNT:34101,ANNOTATIONS_MISSING_STATUS,ANNOTATIONS_AVAILABLE)

- [x] #195
- [x] #197

**Comment by syphax-bouazzouni** [comment]
@jonquet Can we assign someone on this?

**Comment by jonquet** [comment]
For the moment its hard to assign any one to diagnostics and content management.
I am expecting we will all have a tour of this early 2024 after AgroPortal 2.7 release. 
Follow ups on the diganostics shall the by done with @user34ngrau

**Comment by syphax-bouazzouni** [comment]
I fixed most of them, and I am currently trying to parse  PR, NCIBTAXON, E-PHY and NALT before closing this.

**Comment by syphax-bouazzouni** [comment]
PR, NCIBTAXON, and NALT parsed successfully. 
I Close this issue and will open a new one, cleaner in the next iteration.
