### ISSUE TITLE
Changer la valeur publisher de OFPE

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#346]
OFPE : modifier “publisher” et indique “MISTEA (https://www6.montpellier.inrae.fr/mistea), SPO (https://www6.montpellier.inrae.fr/spo/), IATE (https://umr-iate.cirad.fr/)”  

Nous avons deja fait ce changement, mais il semblerait qu'il ne soit pas passé. 
<img width="595" alt="image" src="https://user-images.githubusercontent.com/7379183/210210876-0205f20d-9541-4ba9-acee-3b8b4b47fe76.png">

Il y aurait (il un problème avec le fait de mettre à jour la valeur actuelle?

**Comment by syphax-bouazzouni** [comment]
I assume it was done 
![image](https://github.com/agroportal/project-management/assets/29259906/b537c8ce-8e83-4277-b3cd-2f182f98d54d)
