### ISSUE TITLE
Enlever la valeur erronée pour natural language pour AFEO et OFPE

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#347]
AFEO : impossible de supprimer la valeur erronée pour Natural Language / Idem OFPE

<img width="538" alt="image" src="https://user-images.githubusercontent.com/7379183/210211181-79e2cc99-0767-4688-a467-65b5e27c6d94.png">

On a deja fait ce changement mais il semblerait qu'il ne soit pas pris en compte.

**Comment by syphax-bouazzouni** [comment]
Fixed for AFEO
<img width="488" alt="image" src="https://github.com/agroportal/project-management/assets/29259906/78a10be7-6d83-45b4-81d8-45e1ca988123">
Fixed for OFPE
<img width="488" alt="image" src="https://github.com/agroportal/project-management/assets/29259906/eece0fe8-5b0b-438d-90cb-b1c9c35b5016">
