### ISSUE TITLE
versionInfo property is not extracted when the datatype of the value is specified

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#350]
See here: https://gitlab.irstea.fr/copain/phenologicalstages/-/issues/3

Pour PPDO qui specifie le type, cela bloque l'extraction de cette propriété.

**Comment by syphax-bouazzouni** [comment]
@jonquet having datatypeIRI="http://www.w3.org/2001/XMLSchema#decimal" for version is no more an issue. I can't write in their repository so I let you reponed them.

See https://stageportal.lirmm.fr/ontologies/PPDO

**Comment by syphax-bouazzouni** [comment]
related https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/2
