### ISSUE TITLE
Problem browsing CO_356

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#352]
https://agroportal.lirmm.fr/ontologies/CO_356

Generate a "Something wend wrong" screen.

**Comment by syphax-bouazzouni** [comment]
A backend problem https://data.agroportal.lirmm.fr/ontologies/CO_356/submissions?include=all

**Comment by syphax-bouazzouni** [comment]
Fixed on its own 
<img width="1541" alt="image" src="https://user-images.githubusercontent.com/29259906/213489908-98c4abc3-b777-4426-9bd7-43131c14e9da.png">

Surely an story of cache , there is nothing special in the logs

**Comment by jonquet** [comment]
Humm those bugs (fixing by themselves!)  are the best ones...  but also the weirder
