### ISSUE TITLE
Include a "subscribed" attribute in the user model to determine if the user is subscribed or not.

### ISSUE THREAD

**Issue by haddadzineddine** [agroportal/project-management#356]
### Context

See discussion https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/130

### Requirements

- [ ] include a "subscribed" attribute with a default value of "false" in the user model.

**Comment by haddadzineddine** [comment]
Done @syphax-bouazzouni

**Comment by syphax-bouazzouni** [comment]
Ok good,  I remove this one
