### ISSUE TITLE
Impossible de changer le statut de CO_125 a "retired"

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#357]
Via l'interface graphique, le changement de statut de l'ontologie ne marche pas. 

j'ai pu changer d'autres propriétés (e.f. deprecated = true) mais pas le statut qui reste bloqué sur prodcution. 

<img width="268" alt="image" src="https://user-images.githubusercontent.com/7379183/214812367-ff93f195-4462-46ce-aaee-39396552bf31.png">

**Comment by jonquet** [comment]
Je précise : 
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/7379183/214812886-1d0af9f7-00c7-4531-beb9-9b18894c893d.png">

Il y a 2 occurrences du statut dans l'UI . Seulement la 2eme provoque une mise à jour. 

A verifier c'est dans doute la meme chose pour version.

**Comment by syphax-bouazzouni** [comment]
Fixed in Stageportal with https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/161
