### ISSUE TITLE
FLOPO does not have a hierachy and shos undreds of roots reosurces 

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#360]
So the call 
https://data.agroportal.lirmm.fr/ontologies/FLOPO/classes/roots takes super long to process

So do the UI
<img width="831" alt="image" src="https://user-images.githubusercontent.com/7379183/214876126-f1f2a6bb-183a-4760-b7ef-33bf60ec8199.png">

We either need to fix this or see with FLOPO editors how to manage this.

**Comment by jonquet** [comment]
So does CIQUAL
https://data.agroportal.lirmm.fr/ontologies/CIQUAL/submissions/1

**Comment by syphax-bouazzouni** [comment]
@Bilelkihal see here the same use-case, as asked by BioDivPortal
https://agroportal.lirmm.fr/ontologies/FLOPO?p=classes, here fixed with the `flat` option
and here https://agroportal.lirmm.fr/ontologies/CIQUAL?p=classes, the page not loading

**Comment by syphax-bouazzouni** [comment]
The proposed solution moved to https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/718
