### ISSUE TITLE
Harmonize Crop Ontology project URIs

### ISSUE THREAD

**Issue by hibadjebabria169** [agroportal/project-management#361]

**Comment by jonquet** [comment]
Pour toutes les soumissions des ontologies de ce groupe : 
https://data.agroportal.lirmm.fr/groups/CROP

Par exemple CO_330
https://data.agroportal.lirmm.fr/ontologies/CO_330/submissions?display=URI&display_links=false&display_context=false
=> Mettre la valeur d'URI : "http://www.cropontology.org/ontology/CO_330"

**Comment by jonquet** [comment]
@syphax-bouazzouni est-ce qu'on prévoir de releaser en prod l'interface d'administration en batch bientôt ou @hibadjebabria169  doit prévoir un script?
