### ISSUE TITLE
FALDO, EBO, SSN & AEO : The field must contain just the version of the ontology 

### ISSUE THREAD

**Issue by hibadjebabria169** [agroportal/project-management#364]
Fix the value of the version so that it doesn't contain extra informations that should be in other properties

**Comment by hibadjebabria169** [comment]
To be closed

![3](https://user-images.githubusercontent.com/59914426/221793781-bf9ccb07-bbd1-4501-a425-def7d675b44f.png)

**Comment by jonquet** [comment]
Can we change the value for SSN and pu this comment in another property ? 
Something like omv:notes.

**Comment by hibadjebabria169** [comment]
Done
