### ISSUE TITLE
AGROVOC : Specify the value of "other" on its property Syntax 

### ISSUE THREAD

**Issue by hibadjebabria169** [agroportal/project-management#366]

**Comment by hibadjebabria169** [comment]
To be closed 

![6](https://user-images.githubusercontent.com/59914426/221795022-843f3f17-8ec5-4c64-a86c-70dcd07da402.png)

**Comment by jonquet** [comment]
Have you also reported the bug of the double "other " value ? 
If yes, then you can close this.

**Comment by hibadjebabria169** [comment]
Done
