### ISSUE TITLE
Other identifier : Remove the http://purl.obolibrary.org/obo/TEMP and other TEMP values 

### ISSUE THREAD

**Issue by hibadjebabria169** [agroportal/project-management#367]

**Comment by jonquet** [comment]
Il faut surtout enlever les URI temporaire du champ "URI"... je ne pense pas qu'elles soit tres frequentes dans le champ "Identifier" mais a verifier. 

Cette issue se focalise sur le changement de métadonnées. Pour éviter que cela revienne, une autre issue existe  : 
https://github.com/agroportal/project-management/issues/396

**Comment by jonquet** [comment]
API call pour vérifier:  https://data.agroportal.lirmm.fr/submissions?&display=URI&display_links=false&display_context=false
