### ISSUE TITLE
Other identifier : Verify if value is different from URI except for OBO PURLs  

### ISSUE THREAD

**Issue by hibadjebabria169** [agroportal/project-management#368]
The call to see the differences betweem URI and identifier: 
https://data.agroportal.lirmm.fr/submissions?&display=identifier,URI&display_links=false&display_context=false

**Comment by jonquet** [comment]
After thinking several time about it, I would finally make no exception and remove all the values from "identifier" when this value is equal to "URI"
@hibadjebabria169 Be sure we have a rule in #393  fir this so that @syphax-bouazzouni can implement it in the new model.

**Comment by jonquet** [comment]
Please provide here the list of ontologies that need to be treated.

**Comment by hibadjebabria169** [comment]
Ontologies that have the URI equal to the Identifier : 

- [x] - GO (209)
- [x] - TO (14)
- [x] - ONTOBIOTOPE-51 (42)
- [x] - SO (98)
- [x] - EFO (52)
- [x] - VT (63)
- [x] - PATO (38)
- [x] - PIZZA8 (2)
- [x] - CO_347 (26)
- [x] - ENVO (21)
- [x] - LBO (21)
- [x] -  AGRO (9)
- [x] - RO (33)
- [x] - PCO (8)
- [x] - SNPO (3)
- [x] - VARIO (10)
- [x] - SIO (34)
- [x] - CDAO (4)
- [x] - OM (15)
- [x] - PIZZA (2)
- [x] - CD (1)
- [x] - OBOE (1)
- [x] - PIZZA5 (3)
- [x] - FALDO (2)
- [x] - EDAM (13)
- [x] - GFVO (4)
- [x] - DSW (3)
- [x] - CIQUAL (1)
- [x] - CO_370 (1)
- [x] - SSN (2)
- [x] - BFO (3)
- [x] - SAREF4AGRI (1)
- [x] - FOODIE (2)
- [x] - DMO-CORE (2)
- [x] - AGROVOC (31)
- [x] - FLAIR (3)
- [x] - FOBI (3)
- [x] - INIA-RDM (1)  
- [x] - SOSA (2) 
- [x] - CO_359 (68)
- [x] - PPO (1)
- [x] - TIME (3)
- [x] - CVO (2)
- [x] - SAREF4ENVI (1)
- [x] - OFPE (3)
- [x] - PR (4)
- [x] - PEAO (2)
- [x] - PECO (4)
- [x] - OWSD (1)
- [x] - C3POCM (1)
- [x] - PIZZA10 (1)
- [x] - SDGIO (1)
- [x] - OESO-CORE (1)
- [x] - CASO (5)
- [x] - C3POPLANT (1)
- [x] - ATC (1)
- [x] - PIZZA3 (1)
- [x] - PIZZA7 (1)
- [x] - BCO (1)
- [x] - OESO-PHIS (1)
- [x] - PIZZA4 (1)
- [x] - FOODEX2 (2)
- [x] - EBO (4)
- [x] - GAO (4)

**Comment by hibadjebabria169** [comment]
Delete the empty string on the identifier value on the following ontologies :  

- CO_350 (57) 
- CO_345 (57) 
- STY (3) 
- PO (16) 
- CO_341 (62) 
- CO_338 (63) 
- CO_337 (63)  
- CO_366 (23) 
- CO_358 (53)  
- PHYTOTRAITS (3)  
- CO_321 (63)  
- CO_324 (60)  
- CO_340 (60) 
- CO_331 (61)  
- CO_330 (57)  
- CO_346 (59)  
- CO_333 (10)  
- CO_322 (62) 
- CO_348 (58) 
- CO_356 (41) 
- C_335 (57)  
- CO_334 (60)  
- CO_336 (12) 
- CO_320 (63)  
- CO_360 (50)  
- TOP (1) 
- AFO (2)  
- SMLC-TEST (2)  
- CO_323 (2)  
- CLC (1)  
- AGRORDF (1)  
- CO_343 (56)  
- CO_365 (51)
