### ISSUE TITLE
PPDO ⇒ Insert the link of the GitHub repository in the field use guideline 

### ISSUE THREAD

**Issue by hibadjebabria169** [agroportal/project-management#370]
Delete "see the github repository"

**Comment by hibadjebabria169** [comment]
Didn't find the repo yet : 

![7](https://user-images.githubusercontent.com/59914426/221795457-a2f6a0ae-0193-41b2-88cf-4061c6a339eb.png)

**Comment by syphax-bouazzouni** [comment]
This one I think https://gitlab.irstea.fr/copain/phenologicalstages

**Comment by hibadjebabria169** [comment]
To be closed : 

![10](https://user-images.githubusercontent.com/59914426/221796742-2a196f21-7f2d-4313-9d33-cd9c564913c1.png)
