### ISSUE TITLE
CO_366 : Replace the version by the description of the ontology 

### ISSUE THREAD

**Issue by hibadjebabria169** [agroportal/project-management#372]

**Comment by jonquet** [comment]
Edited all the ontologies in the CROP group that do not have an explicit description  with the sentence: 

"This ontology is a part of the the Crop Ontology project (http://www.cropontology.org), created in 2008 by the CGIAR, as an essential source of traits and variables to support the standardization of the breeding databases."

**Comment by hibadjebabria169** [comment]
To be closed 

![8](https://user-images.githubusercontent.com/59914426/221795790-ba9e0101-86d7-4341-b9d5-6f17ff59d952.png)

**Comment by hibadjebabria169** [comment]
It has been extended to all crop ontologies that do not have a description in this field.
