### ISSUE TITLE
Implement dependencies between the dates 

### ISSUE THREAD

**Issue by hibadjebabria169** [agroportal/project-management#378]
When a new submission is submitted, the dates will be dependent from version n-1 to version n, there are rules to be resepcted, these rules are explained in [the curation document](https://docs.google.com/document/d/1NHFNUjwOV7_aBrwNqDDgSshLTVewiZsKnFPLWuKc-xY/edit?usp=sharing) for the following dates: Creation date, Modification date, Submission date, Validity date, Curation date

**Comment by syphax-bouazzouni** [comment]
@hibadjebabria169 put in your description the work to be done, not just the "see the curation document" text without any link.

**Comment by jonquet** [comment]
Issue superseded by https://github.com/agroportal/project-management/issues/393
