### ISSUE TITLE
Dépôt d'une ontologie sans soumission (ONLYMETADATA)

### ISSUE THREAD

**Issue by antool** [agroportal/project-management#38]
La création d'une ontologie avec seulement des métadonnées produit ce message d'erreur :
"We're sorry but something has gone wrong. We have been notified of this error."
Cela est probablement dû au fait qu'il n'y a pas de soumission associée. Mais l'ontologie est quand même créée : http://agroportal.lirmm.fr/ontologies/ONLYMETADATA
Il faut adapter le formulaire d'enregistrement (par exemple, inutile de demander le format du fichier de l'ontologie quand il n'y en a pas).

**Comment by syphax-bouazzouni** [comment]
resolved by NCBO here https://github.com/ncbo/bioportal_web_ui/issues/47
