### ISSUE TITLE
AgroPortal metadata curation 2023

### ISSUE THREAD

**Issue by hibadjebabria169** [agroportal/project-management#381]
## Context 
These issues concern the content, the metadata and their connections in AgroPoratl, they are extracted from the [curation document.](https://docs.google.com/document/d/1NHFNUjwOV7_aBrwNqDDgSshLTVewiZsKnFPLWuKc-xY/edit?usp=sharing)
They'll be used to manage the content of the AgroPortal and to adjust any errors in the metadata values and also to keep the semantic link between the properties 

## Requirements 
- [x] #361 
- [x] #362 
- [x] #367 
- [x] #376 
- [x] #379 
- [x] #380 
- [x] #383
- [x] #387
- [x] #388
- [x] #389
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/190
- [x] #415

**Comment by jonquet** [comment]
@hibadjebabria169 Can you separate the issues in this list into 2 categories : the ones that are specific to one or a couple of ontologies from the ones that are generic and requires some implemnation/change.

**Comment by jonquet** [comment]
Issue related to the verification of the rules between the properties: https://github.com/agroportal/project-management/issues/393

**Comment by syphax-bouazzouni** [comment]
Close the issue and let the remaining sub-task issues open.
