### ISSUE TITLE
DMO-CORE : (Target audience) ==> Clarify  the "all" value.

### ISSUE THREAD

**Issue by hibadjebabria169** [agroportal/project-management#382]
give more informations about the evaluation of this ontology

**Comment by syphax-bouazzouni** [comment]
Do you mean this value 
<img width="622" alt="image" src="https://user-images.githubusercontent.com/29259906/222379991-66905f7a-4c98-4d94-8b04-7b4b8a03bb47.png">

**Comment by hibadjebabria169** [comment]
Yes

**Comment by syphax-bouazzouni** [comment]
So it's not "Evaluation" but "Target audience", and this latter can be edited I think

**Comment by hibadjebabria169** [comment]
I'll fix it and close th issue
