### ISSUE TITLE
Repository ==> Fill in the URL of the code repository if it exists, typically a GitHub, GitLab or other mercurial or SVN repo

### ISSUE THREAD

**Issue by hibadjebabria169** [agroportal/project-management#383]

**Comment by jonquet** [comment]
Please list here the ontologies which does not have a value for the "repository" metadata property.

**Comment by hibadjebabria169** [comment]
Ontologies that have "null" on the repository property 

- WHEATPHENOTYPE (9) et ONTOBIOTOPE-51 (42) et ONTOBIOTOPE (8)
- GENO (61)
- EO (6)
- DEMETER-AIM (7)
- SPTO (3)
- AHOL (2) + EOL (247) + ATOL (154)
- SNPO (3)
- VARIO (10)
- LEXEAU (14)
- SIO (34)
- CGO (5)
- OSA (2)
- POLAPGEN_BARLEY (1)
- CD (1)
- CBI (2)
- OEEV (6)
- PO2 (4)
- FALDO (2)
- SIREN (1)
- GFVO (4)
- GECO (90)
- AFEO (12)
- SAREF (2)
- CO_370 (1)
- DURUM_WHEAT (3) + BIOREFINERY (8) +  CIQUAL (1) + TRANSMAT (5)
- WHEAT_TAX (1)
- MS2O (2)
- SOIL (1)
- AWS (1)
- MICROFILTRATION (1) + INFRARISK (8)
- SAREF4AGRI (1)
- AFO (2)
- ASCOPAIN-T (1)
- DATA4CPLUS (2)
- ICC (2)
- FOODIE (2)
- OEPO (2)
- FOBI (3)
- INIA-RDM (1)
- CPC  (2)
- CLC (1)
- ANDO (4)
- ANT (1)
- AGRORDF (1)
- AEO (1)
- CVO (2)
- SAREF4ENVI (1)
- OFPE (3)
- WCACROPS (1)
- THESAE (7)
- CASO (5)
- BT (3)
- ATC (1)
- USE (3)
- MEAT-T (1)
- FOODEX2 (2)
- TRIPHASE (1)
- GAO (4)

**Comment by hibadjebabria169** [comment]
They need to be referenced in another place to make it easier to fill in the values.

**Comment by jonquet** [comment]
Va necessiter de contacter les gens. 
Donc a lister avec l'email de contact utilisateur a préparer pour plusiuers champs de mdétadonnées ensemble.

**Comment by hibadjebabria169** [comment]
liste des contacts : 

- [ ] claire.nedellec@inrae.fr
- [ ] Matthew H. Brush, brushm@ohsu.edu
- [ ] Claire Nédellec, claire.nedellec@inra.frEstelle Chaix, estelle.chaix@inra.fr
- [ ] Olivier Bodenreider, olivier@nlm.nih.gov / Agroportal, agroportal-support@lirmm.fr
- [ ] Laurel Cooper, cooperl@science.oregonstate.edu / Pankaj Jaiswal, jaiswalp@science.oregonstate.edu
- [ ] Jim Reecy, jreecy@iastate.edu
- [ ] Raul Palma, rpalma@man.poznan.pl / Ioanna Roussaki, ioanna.roussaki@cn.ntua.gr
- [ ] Naama Menda, nm249@cornell.edu
- [ ] Jim Reecy, jreecy@iastate.edu
- [ ] Matthieu Reichstadt, matthieu.reichstadt@inrae.fr / Jerome Bugeon, jerome.bugeon@inrae.fr / Pierre-Yves Le Bail, pierre-yves.le-bail@inrae.fr
- [ ] Bouazzouni syphax, gs_bouazzouni@esi.dz 
- [ ] Adrien Coulet, adrien.coulet@loria.fr
- [ ] Mauno Vihinen, mauno.vihinen@med.lu.se
- [ ] Jean-Louis Janin, jeanlouisjanin@gmail.com
- [ ] Michel Dumontier, michel.dumontier@gmail.com
- [ ] Jack Verhoosel, jack.verhoosel@tno.nl
- [ ] Chen Yang, chen.yang@UGent.be
- [ ] Crop Ontology Helpdesk, helpdesk@cropontology-curationtool.org
- [ ] Neha Kaushik, swami.neha@gmail.com / Niladri Chatterjee, niladri.iitd@gmail.com
- [ ] Fahad , mhd.fahad@gmail.com
- [ ] Llorenç Cabrera-Bosquet, llorenc.cabrera-bosquet@inra.fr
- [ ] Stephane Dervaux, stephane.dervaux@inrae.fr
- [ ] NCBI information, info@ncbi.nlm.nih.gov
- [ ] Jerven Bolleman, jerven.bolleman@isb-sib.ch
- [ ] Buche, patrice.buche@inrae.fr
- [ ] Biodiversity Thesaurus contact, contact-terminologietal@inist.fr / Dominique Vachez, dominique.vachez@inist.fr / Isabelle Gomez, isabelle.gomez@inist.fr
- [ ] Joachim Baran, kim@codamono.com
- [ ] GECO support, geco@acta.asso.fr
- [ ] Tireau Anne, anne.tireau@inrae.fr
- [ ] Maxime Lefrançois, maxime.lefrancois@emse.fr / María Poveda-Villalon, mpoveda@fi.upm.es / Laura Daniele, Laura.Daniele@tno.nl / Raúl García Castro, rgarcia@fi.upm.es
- [ ] Ekaterina Chuprikova, ekaterina.chuprikova@eurac.edu 
- [ ] Catherine Roussey, catherine.roussey@irstea.fr
- [ ] Juliette Dibie, juliette.dibie-barthelemy@inrae.fr / Sophie Aubin, sophie.aubin@inrae.fr
- [ ] Giovanni L'Abate, giovanni.labate@crea.gov.it
- [ ] Bernard Vatant, na@na.com
- [ ] Eero Hyvönen, Eero.Hyvonen@tkk.fI
- [ ] VO@INRAE, vocabulaires-ouverts@inrae.fr
- [ ] Julien Demenois, julien.demenois@cirad.fr / DATA4C+ curator, data4c@cirad.fr
- [ ] Food and Agriculture Organization of the United Nations (FAO), faq-hq@fao.org
- [ ] Raul Palma, rpalma@man.poznan.pl
- [ ] Llorenç Cabrera-Bosquet, llorenc.cabrera-bosquet@inra.fr
- [ ] AGROVOC, AGROVOC@fao.org
- [ ] Land Portal Foundation, info@landvoc.org
- [ ] Phil Archer, phil.archer@gs1.org
- [ ] Pol Castellano Escuder, polcaes@gmail.com
- [ ] Antonio J. Sánchez-Padial, antonio@spadial.com
- [ ] Jerome Bugeon, jerome.bugeon@inrae.fr
- [ ] Sophie Aubin, sophie.aubin@inra.fr
- [ ] International Food Policy Research Institute, ifpri@cgiar.org
- [ ] KBTL, ktbl@ktbl.de
- [ ] Tireau Anne, anne.tireau@supagro.inra.fr
- [ ] Akane Takezaki, akane@affrc.go.jp / Hideaki Takeda, takeda@nii.ac.jp
- [ ] Caterina Caracciolo, Caterina.Caracciolo@fao.org
- [ ] Véronique Batifol, veronique.batifol@inrae.fr
- [ ] Catherine Roussey, catherine.roussey@irstea.fr
- [ ] Stefan Schulz, stefan.schulz@medunigraz.at
- [ ] Dumitru Roman, dumitru.roman@sintef.no
- [ ] European Food Safety Authority, datex@efsa.europa.eu
- [ ] Cyril Pommier, cyril.pommier@inrae.fr / Eric Duchêne, eric.duchene@inrae.f

**Comment by hibadjebabria169** [comment]
Fields are filled with the values provided by contact' users
