### ISSUE TITLE
PPO ==> (prior version) : the link doesn’t match the previous version 

### ISSUE THREAD

**Issue by hibadjebabria169** [agroportal/project-management#384]
prior verison ==> Update the URL on the CVO ontology &  OESO-PHIS

**Comment by syphax-bouazzouni** [comment]
@hibadjebabria169 in your closing comment always put a screenshot of the work done (so that we don't need to recheck ourselves)

**Comment by hibadjebabria169** [comment]
this issue should be closed before because the value was right 
for other issues, i fixed them (still need a validation) then be closed here with the screenshot
