### ISSUE TITLE
Change relation btw ontologies in metadata from data.agroportal URLs to UI URLs

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#391]
For instance 
https://agroportal.lirmm.fr/ontologies/PO

Has a bunch of relations that are expressed with data.agroportal.lirmm.fr URL rather than the relevant UI URLs of the ontologies in AgroPortal. 

<img width="440" alt="image" src="https://user-images.githubusercontent.com/7379183/215775182-87c680f8-419a-4c3a-a2bd-84ecd0278ae1.png">

**Comment by jonquet** [comment]
The problem is too frequent to be an error.
 
In fact, I believe this is a change coming from latest change in the form which has changed  the URL in the displayed form rather than leaving the UI URLs. 

<img width="767" alt="image" src="https://user-images.githubusercontent.com/7379183/215783046-b9fd3d04-9988-47e6-949f-cf0cb9efa2a9.png">

**Comment by syphax-bouazzouni** [comment]
This issue is related to our transition to HTTPS. But is not a technical issue, you will need to reset the metadata values again and they will work.

**Comment by jonquet** [comment]
Ok. Make sense... with moving to HTTPS everything changed... we will see with @hibadjebabria169 how to automate this.

**Comment by syphax-bouazzouni** [comment]
Seems to be fixed somewhere, the ontologies are in green and detected as internal to the portal
![image](https://github.com/agroportal/project-management/assets/29259906/5965ec8b-77d7-4af2-a83e-406d45eb7c7e)

Even if they are using the API link or the UI link. the code detected both now
![image](https://github.com/agroportal/project-management/assets/29259906/6b046be1-78cb-4021-80d5-b041221029c3)
