### ISSUE TITLE
AgroPortal metadata curation_2023_ontologies

### ISSUE THREAD

**Issue by hibadjebabria169** [agroportal/project-management#392]
## Context 
These issues concern the content, the metadata and their connections in AgroPoratl, they are extracted from the [curation document.](https://docs.google.com/document/d/1NHFNUjwOV7_aBrwNqDDgSshLTVewiZsKnFPLWuKc-xY/edit?usp=sharing)
They'll be used to manage the content of the AgroPortal and to adjust any errors in the metadata values and also to keep the semantic link between the properties 

## Requirements 
- [x] #363 
- [x] #364
- [x] #365 
- [x] #366 
- [x] #368 
- [x] #369 
- [x] #370 
- [x] #371 
- [x] #372 
- [x] #373 
- [x] #374 
- [x] #375
- [x] #377 
- [x] #382 
- [x] #384 
- [x] #385 
- [x] #386 
- [x] #390
- [x] #404

**Comment by jonquet** [comment]
Closing this issue as this curation iteration is closed now. 
Remaining issue will be handle apart.
