### ISSUE TITLE
Manually match the LBO version info in BioPortal with the versions info we have in AgroPortal 

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#397]
We automatically pull LBO from BioPortal...  but we don't get the metadata... typically version info which is manually edited in this case by the developper of LBO. 

We need to update (based on the submission dates) AgroPortal values : 
https://agroportal.lirmm.fr/ontologies/LBO
<img width="172" alt="image" src="https://user-images.githubusercontent.com/7379183/217240115-6f9f4f6d-0c01-4910-9aa9-a87d9aa86d19.png">

With the BioPortal ones 
https://bioportal.bioontology.org/ontologies/LBO
<img width="201" alt="image" src="https://user-images.githubusercontent.com/7379183/217240422-d511f29a-20a9-40a0-89eb-607d4714b573.png">

**Comment by syphax-bouazzouni** [comment]
To close if done  @jonquet 


![Image](https://github.com/agroportal/project-management/assets/29259906/cbba8164-5f91-4939-89ae-ad286a7bfc05)

**Comment by syphax-bouazzouni** [comment]
Not fully aligned before 8.6, but are after. Close as this issue is not updated since one year.
![image](https://github.com/agroportal/project-management/assets/29259906/3155148f-dd2b-47f7-abd7-5e5d4524a9cb)

**Comment by jonquet** [comment]
Alors j'ai regardé pour changer manuelmement les versions des soumisisons précedentes. Il y en a pour 5 min avec l'info chez BioPortal. 
Le problème est que avec les contraintes ajoutées sur les métadonnées, on ne peut plus éditer seulement la version des soumissions précédentes sans avoir une erreur... à cause d'autres valeurs ...  

<img width="665" alt="Capture d’écran 2024-07-17 à 10 52 01" src="https://github.com/user-attachments/assets/189687a5-aeec-4d83-8758-5b90a28178ab">

C'est pas forcement tres grave de ne plus pouvoir éditer les versions d'avant... et encore.. mais le champ version (et le champ "modification date" sont les 2 qu'il serait vraiment pratique de pouvoir continuer a éditer qq soit les soumissions. 

Donc idéalement il faudrait fermer cette issue quand on aura régler les numéros des soumissions 8 à 20 qui sont les memes. Mais pour ca il faut pouvoir éditer les soumissions précédentes.

**Comment by syphax-bouazzouni** [comment]
@jonquet , Est ce que vous pouvez me mettre ici, les changements de versions a faire, et je les ferai en linge de commande.

**Comment by jonquet** [comment]
- Submission 8 => version 7.2
- 9 => 7.3
- 10 => 7.4
- 11 => 7.5
- 12 => 7.6
- 13 => 7.7
- 14 => 7.8
- 15 => 7.9
- 16 => 7.10
- 17 => 7.11
- 18 =>  7.12
- 19 =>  7.13
- 20 => 7.14

**Comment by syphax-bouazzouni** [comment]
Done 
![image](https://github.com/user-attachments/assets/d8de0bba-0e04-423c-a5da-daa769ad1979)
