### ISSUE TITLE
TEMP URI for the obo foundry ontologies 

### ISSUE THREAD

**Issue by hibadjebabria169** [agroportal/project-management#406]
For the existing ontologies, I deleted the URI for the obo ontologies, because they're wrong ...

**Comment by hibadjebabria169** [comment]
@syphax-bouazzouni 
For the coming ontologies : 

- When it comes to a kind of TEMP URI, the system should ignore it 
- else, it'll be added

**Comment by syphax-bouazzouni** [comment]
related to #367 and #396
