### ISSUE TITLE
Complete and update the Agroportal submission metamodel 2023 - Part 1

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#410]
# Goals

- Enrich submission attributes metadata 
- Make the validators less permissive
- Keep always the data consistency and coherence  

# Refrences

- [Agroportal metadata curation template](https://docs.google.com/document/d/1NHFNUjwOV7_aBrwNqDDgSshLTVewiZsKnFPLWuKc-xY/edit)
-  [Agroportal model 2023 sheet](https://docs.google.com/spreadsheets/d/1DuHmz0G6NrLB6jXuU040Nf-ZcDIyOjtt7AT1-NSgWHQ/edit)
    
# Requirements

##  Goo development 
**DataTypes**

- [x]  https://github.com/ontoportal-lirmm/goo/pull/23

**Validators**

- [x]  https://github.com/ontoportal-lirmm/goo/pull/26
- [x]  https://github.com/ontoportal-lirmm/goo/pull/27
    - [x]  https://github.com/ontoportal-lirmm/goo/issues/18
    - [x]  https://github.com/ontoportal-lirmm/goo/issues/19
    - [x]  https://github.com/ontoportal-lirmm/goo/issues/20
    - [x]  https://github.com/ontoportal-lirmm/goo/issues/21
- [x]  https://github.com/ontoportal-lirmm/goo/pull/28

**YAML Model schemes** 

- [x]  https://github.com/ontoportal-lirmm/goo/pull/30

**On Update callback**  

- [x]  https://github.com/ontoportal-lirmm/goo/pull/31

## Ontologies linked to data development

- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/72

## API development 

- [x] https://github.com/ontoportal-lirmm/ontologies_api/issues/26
- [x] https://github.com/ontoportal-lirmm/ontologies_api/pull/33
- [x] https://github.com/ontoportal-lirmm/ontologies_api/issues/30

## UI development

- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/240
- [ ] Make a public guide for the portal meta model

**Comment by jonquet** [comment]
Related to this issue, I realize this is certainly the time to introduce a couple of other properties in the model being candidate at MOD2.1 too. 

mod:upperOntology
mod:hasFAIRscore
mod:crossReference

Metrics (will be necessary for O'FAIRE v2)
mod:numberOfReusedTerms
mod:numberOfReusedTermsWithMIREOT
mod:numberOfMappings
mod:numberOfMappingsReusable
mod:numberOfCrossReferences
mod:numberOfCrossReferencesReusable
mod:numberOfObjectsWithLabels
mod:numberOfObjectsWithTextDescription
mod:numberOfObjectsWithFormalDescription
mod:numberOfObjectsWithProvenance

To be completed in @syphax-bouazzouni's metadata document
To be completed in MOD2.1 => https://github.com/FAIR-IMPACT/MOD

**Comment by jonquet** [comment]
New metrics discussion is here : 
https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/103

mod:upperOntology => not needed as we have mod:specializes
