### ISSUE TITLE
How to view the list of concepts in a collection at one sight?

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#416]
We did not found the way to list them. We can only see 
- the colored bullet in the hierarchy indicating to which collection(s) a concept belongs
- the number of members of a collection 
We would like the list of members on the collection page.

**Comment by syphax-bouazzouni** [comment]
The collection view is not enough?

Otherwise, we can add a popup on the collection page, in front of the number, that will list all the members.

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/29259906/230156790-ae5bbcae-54e1-4715-b8a6-492b7da22e79.png">

**Comment by saubin78** [comment]
We just did not remember the collection tab in the Concept page. This is because we were in the Collection page. Yes, it may be good to have a way to view the members of a list from this place.

**Comment by syphax-bouazzouni** [comment]
Assigned to @SirineMhedhbi 

### TODO

- [x] On the collection page, make the in Members count number clickable, and on click open a popup with the list of all the members of the collection or redirect to the concept section with the collection with the right collection selected; see the mockup below.


![Image](https://github.com/agroportal/project-management/assets/29259906/09f2e83c-1306-415c-98f2-c728365a3935)

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/295
