### ISSUE TITLE
Update ontoportal groups/categories administration

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#422]
## Context

See https://github.com/ontoportal/ontoportal_web_ui/issues/2

## Requirements 

- [x] Add groups and categories administration panel (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/237)
- [x] Add groups/categories ontologies count
- [x] Redirect the click on the groups/categories ontologies count link to the browse page with the correct filter applied 
- [x] Add a button to sync groups to slices (https://github.com/agroportal/project-management/issues/272) 
- [x] Open a popup to add/remove ontologies  from a group/category
- [x] Add delete action to remove an ontology from a group/category
- [x] Do the add an ontology to a group/category action

**Comment by syphax-bouazzouni** [comment]
@jonquet please add other requirements if you do have others

**Comment by jonquet** [comment]
Yes. Discussed with @SirineMhedhbi offline already. 

- [x] Add "Delete" action in the right hand Actions column  
- [x] Add a column to see the list of ontologies in a group (comma separated list of clickable acronyms).
- [x] Add a column to see the list of ontologies in a category (comma separated list of clickable acronyms). => @syphax-bouazzouni might require a back-end change as the data is not available in Json
- [x] Add a ontology selector form to the pop-up window opening when clicking "Edit" to select the ontologies in a Group.
- [x] Add a ontology selector form to the pop-up window opening when clicking "Edit" to select the ontologies in a Category.

**Comment by jonquet** [comment]
Just ticked the "Delete" as this is done by the UI already (in batch above the table). 
Sorry. :)
<img width="440" alt="Capture d’écran 2023-05-31 à 11 13 56" src="https://github.com/agroportal/project-management/assets/7379183/7052b66f-2a35-4e67-8979-14ab2a8abe37">

**Comment by SirineMhedhbi** [comment]
Yes. It is not necessary to repeat the action. 
Thank you! :)

**Comment by syphax-bouazzouni** [comment]
Here @SirineMhedhbi, it still to do this 

- [x] Add a button to sync groups to slices (https://github.com/agroportal/project-management/issues/272)
