### ISSUE TITLE
Expected behaviour with multiple mapped properties with different types

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#425]
We have an example of a SKOS resource in AgroPortal, which provides 2 definitons: 
https://agroportal.lirmm.fr/ontologies/ANAEETHES/?p=classes

<img width="605" alt="Capture d’écran 2023-06-08 à 05 16 17" src="https://github.com/agroportal/project-management/assets/7379183/5abf1b4e-292b-425f-b503-d39906876425">

Which ends up in the API as
<img width="928" alt="Capture d’écran 2023-06-08 à 05 22 54" src="https://github.com/agroportal/project-management/assets/7379183/a1681394-a180-4fd8-a606-91afbf58dab3">

(the difference of types creates a non regular JSON structure)

Which ends up in the UI as 
<img width="1047" alt="Capture d’écran 2023-06-08 à 05 22 11" src="https://github.com/agroportal/project-management/assets/7379183/8bd9b5df-69b5-402d-8ce6-fd348f7aa226">

(Similar situation could happen with synonyms which are also mapped to a unique "synonym" property).

What is the expected behaviour  when this situation occurs? 
We can expect the display and the JSON being well structured.

**Comment by syphax-bouazzouni** [comment]
> We can expect the display and the JSON being well structured.

So it's more of a UI bug.

When it's an object it needs to be shown as a link (for now, in the future we will fetch more data about it )

I assign @SirineMhedhbi  to fix this.

**Comment by syphax-bouazzouni** [comment]
Fixed with https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/273

**Comment by jonquet** [comment]
Penser a gèrer le cas ou les valeurs sont des objects (URI) pour les afficher comme des "boutons"

**Comment by SirineMhedhbi** [comment]
@jonquet  Done

**Comment by syphax-bouazzouni** [comment]
> @jonquet Done

@SirineMhedhbi done where? you need to give a link to your commit fix or new PR and a screenshot so that we can see it.

In this case, the commit is https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/67ff34cceacb7149f5d73a075a5fa63e565e3be5

But for the PR, you will need to open a new one as a follow-up of this https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/273  (because already closed) 

Thanks;

**Comment by SirineMhedhbi** [comment]
@syphax-bouazzouni 

okay thanks 

![image](https://github.com/agroportal/project-management/assets/31127782/eef94e7f-da92-41e0-8a92-53dd5434f18e)

**Comment by SirineMhedhbi** [comment]
@syphax-bouazzouni  this is the new PR : 
https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/280
