### ISSUE TITLE
Probleme de navigation pour FoodEx 2

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#426]
On a une erreur de "missing roots" pour FOODEX2

https://agroportal.lirmm.fr/ontologies/FOODEX2/?p=classes

**Comment by syphax-bouazzouni** [comment]
La vu liste Marche 
![Image](https://github.com/agroportal/project-management/assets/29259906/287cd18a-7b17-4626-a13e-728327232f24)

est ce que cette resource n'a pas une structure particulier, de type flat ?

**Comment by jonquet** [comment]
Fixed with good error handling.
