### ISSUE TITLE
Removing mappings generate mapping retrieval error

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#427]
On AGROVOC, concept "farm leases": 
https://agroportal.lirmm.fr/ontologies/AGROVOC/?p=classes&conceptid=http%3A%2F%2Faims.fao.org%2Faos%2Fagrovoc%2Fc_10747&jump_to_nav=true

I just removed a duplicate mapping in the UI. 
As a consequence the mapping tab does not load anymore: 
<img width="895" alt="Capture d’écran 2023-07-12 à 17 47 04" src="https://github.com/agroportal/project-management/assets/7379183/6abaab27-c084-4195-a46f-16ec98cf606d">

**Comment by syphax-bouazzouni** [comment]
The backend is also not working https://data.agroportal.lirmm.fr/ontologies/AGROVOC/classes/http%3A%2F%2Faims.fao.org%2Faos%2Fagrovoc%2Fc_10747/mappings

**Comment by syphax-bouazzouni** [comment]
The log of the error
```
 NoMethodError - undefined method `process' for nil:NilClass:
        /srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/bundler/gems/ontologies_linked_data-e9b708c40
b2b/lib/ontologies_linked_data/mappings/mappings.rb:234:in `block in mappings_ontologies'
        /srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/bundler/gems/ontologies_linked_data-e9b708c40
b2b/lib/ontologies_linked_data/mappings/mappings.rb:226:in `each'
        /srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/bundler/gems/ontologies_linked_data-e9b708c40
b2b/lib/ontologies_linked_data/mappings/mappings.rb:226:in `mappings_ontologies'
        /srv/ontoportal/ontologies_api/shared/bundle/ruby/2.7.0/bundler/gems/ontologies_linked_data-e9b708c40
b2b/lib/ontologies_linked_data/mappings/mappings.rb:258:in `mappings_ontology'
        /srv/ontoportal/ontologies_api/releases/20230217110509/controllers/mappings_controller.rb:15:in `block in <class:MappingsController>'

```

**Comment by syphax-bouazzouni** [comment]
The creation and deletion of REST mappings is working for the other classes (tested with https://agroportal.lirmm.fr/ontologies/AGROVOC/?p=classes&conceptid=http%3A%2F%2Faims.fao.org%2Faos%2Fagrovoc%2Fc_50191)

**Comment by syphax-bouazzouni** [comment]
See to work now created and removed a mapping 
![image](https://github.com/agroportal/project-management/assets/29259906/11005c81-f9ea-4b6b-b7cd-497ac5d2a5f8)
