### ISSUE TITLE
Metadata Administration : Select all properties when the input is empty

### ISSUE THREAD

**Issue by hibadjebabria169** [agroportal/project-management#429]
when the user enters nothing on the input, it should return all metadata properties for the selected ontologies

**Comment by syphax-bouazzouni** [comment]
Related https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/190

**Comment by syphax-bouazzouni** [comment]
It takes too much time to show all the metadata of all ontologies. So filtering by metadata is required here.
