### ISSUE TITLE
Chargement d'une soumission pour VBO ne fonctionne pas

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#434]
Deux essais de chargement d'une 1ere soumission a VBO ce matin (ontologie private pour laquelle @user34ngrau avait deja crée l'ontologie) 
https://agroportal.lirmm.fr/ontologies/VBO

Une en erreur "upload" infini.
Une autre atterri sur "INternal server error"

**Comment by jonquet** [comment]
Problème reproduit avec une nouvelle ontologie (chargée directement sans passer par la phase "sans soumission") : ONS
Log vers 16h58

Bizarrement, on a eu une autre ontologie chargée par un autre utilisateur ce jour (TRIBONT) qui a l'air d'avoir marchait comme il faut... mais pour laquelle on a une erreur de parsing (apres que la soumission se soit crée)
@syphax-bouazzouni Est-ce que tu arrives a reproduire le bug ?

**Comment by syphax-bouazzouni** [comment]
I close it as it seems fixed, please reopen it if not. 
![image](https://github.com/agroportal/project-management/assets/29259906/98dbb291-f322-44b5-9d39-d62c26258590)
