### ISSUE TITLE
Remove a few ontologies from AgroPortal

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#435]
Form multiple reasons we are considering removing some ressources in AgroPortal. 
Mostly because they are already available in another portal in the Alliance (in our case BioPortal mostly) and because the communities are not necessarily coming to AgroPortal to browse/use these ontologies. 

These include: 
- [x] GO
- [x] PR
- [x] ITIS
- [x] CL
- [x] EFO
- [x] SO
- [ ] SIO 

At least, we should adopt a strategy to keep only a few version of these ontlogies. 

NB: PR is not plugin to any pullURL hence the version is super old.

**Comment by jonquet** [comment]
Done. 
- For GO, kept only one version per year.
- For CL, kept only one version per year.
- For SO, kept only one version per year.
- For EFO, kept only one version per year. Problem removing 18,19,20,21,22,23, 40,41
<img width="1134" alt="Capture d’écran 2023-09-12 à 15 06 03" src="https://github.com/agroportal/project-management/assets/7379183/c5b77ce6-703d-4792-b165-0e6fd0dcc067">

- For PR, I just add a pullURL so the ontology will be maintainted updated. Willa dopt the same policy (one per year) later. The new submission shall remove the huge mappings file.

- For ITIS: https://agroportal.lirmm.fr/ontologies/ITIS @syphax-bouazzouni can you remove it with the script ? (the UI does not work ...)

**Comment by syphax-bouazzouni** [comment]
Any new on this @jonquet ?

**Comment by jonquet** [comment]
We shll keep this move when the discussion about the canonical ontologies with the OntoPortal Alliance will occur.

**Comment by syphax-bouazzouni** [comment]
@jonquet reminder.

**Comment by syphax-bouazzouni** [comment]
ITIS is removed, and I cleaned the EFO submissions 
<img width="1315" alt="image" src="https://github.com/agroportal/project-management/assets/29259906/b89794c1-209f-41b6-8781-e5440c1a5019">

**Comment by jonquet** [comment]
Let's assume this issue was the first phase. We shall certainly completely remove these ontologies one day. But we will see when fédération with BioPortal will be enabled
