### ISSUE TITLE
NCBITAXON clean up

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#436]
Seems we had and issue with pur pullRUL (conencting to NCBO BioPortal) with NCBITAXON. 
We need to remove some submisisons : from 12 to 22 

Then, I think the best is to "unplug" this resoruce (remove the pullURL). ... I recall this can't be done for the moment in the UI.

**Comment by syphax-bouazzouni** [comment]
### Deleting the duplicated versions
Done using NCBO cron delete script
<img width="1007" alt="image" src="https://github.com/agroportal/project-management/assets/29259906/75ea0b68-f02b-48e9-ae03-16f5fa20a92c">
result 
<img width="1738" alt="image" src="https://github.com/agroportal/project-management/assets/29259906/e62dbce7-0d4e-40ae-8853-f06cd30a5109">

### Unplug NBCITAXON
It did not work using the submission form but worked using the metadata curator
 
<img width="2352" alt="image" src="https://github.com/agroportal/project-management/assets/29259906/ebe206ca-40a4-4326-955a-9193148d670a">

**Comment by syphax-bouazzouni** [comment]
Close as done
