### ISSUE TITLE
AGFOOD does not parse

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#438]
https://agroportal.lirmm.fr/ontologies/AGFOOD

The file (SKOS) opens in Protégé (well parsed, without error). 
Our parsing fails with the following error.

<img width="1203" alt="Capture d’écran 2023-09-13 à 16 30 35" src="https://github.com/agroportal/project-management/assets/7379183/8f6e412d-2cec-49f0-8357-522f6f04713f">

**Comment by syphax-bouazzouni** [comment]
Related to this https://github.com/ontoportal-lirmm/owlapi_wrapper/issues/4.
I think it is fixed in stageportal, you can check.

**Comment by jonquet** [comment]
File is now parsed (with owl:Ontology added). 

Other issues include: 
There is not top level concept. AgroPortal behaves well with this: 
<img width="451" alt="Capture d’écran 2023-09-13 à 21 40 17" src="https://github.com/agroportal/project-management/assets/7379183/e79faa7d-1517-4b66-90b5-ef3270adcf27">

There is not collection. AgroPortal behaves well with this: 
<img width="454" alt="Capture d’écran 2023-09-13 à 21 41 38" src="https://github.com/agroportal/project-management/assets/7379183/691b9739-10a9-4b25-952b-4ee445d8f606">

**Comment by jonquet** [comment]
@syphax-bouazzouni Note for later: the first message could contain a parenthesis (skos:topConceptOf)... to harmonised the error message

**Comment by syphax-bouazzouni** [comment]
> @syphax-bouazzouni Note for later: the first message could contain a parenthesis (skos:topConceptOf)... to harmonised the error message

@SirineMhedhbi please take care if this.

**Comment by SirineMhedhbi** [comment]
Fixed => https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/348
