### ISSUE TITLE
Google analytics is will no more work / Need migration to V4

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#439]
In Stageportal we do nore more see the visits anymore 
<img width="576" alt="image" src="https://github.com/agroportal/project-management/assets/29259906/185a6003-f6b6-454d-a610-333c84565ec5">

because Google Analytics stopped sending data to us in the old way that is implemented in our code.
<img width="1251" alt="image" src="https://github.com/agroportal/project-management/assets/29259906/46eade28-aac5-4114-a4ea-e75dc47c335a">

In Agroportal it still working for some time but it will not be the case for more time 
<img width="1193" alt="image" src="https://github.com/agroportal/project-management/assets/29259906/7fafd9ee-c34a-4d1d-8f77-6e0d29ea9f0c">
 
I give more details here https://github.com/ontoportal/ontoportal-project/issues/30, of how bioportal did the migration.

**Comment by jonquet** [comment]
Fine for me to implement those changes on our side. Hopefully with some guidance from Alex.

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/423
