### ISSUE TITLE
Concept error on seed in AGROVOC

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#440]
https://agroportal.lirmm.fr/ontologies/AGROVOC?p=classes&conceptid=http%3A%2F%2Faims.fao.org%2Faos%2Fagrovoc%2Fc_6927

D'autres concept foctionne mais Seed non.

**Comment by syphax-bouazzouni** [comment]
fixed 
![image](https://github.com/agroportal/project-management/assets/29259906/74f700c8-f44d-477d-9d52-9ed9ad767219)
