### ISSUE TITLE
clean duplicated accounts with the same email

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#441]
With the new SSO features, we enforced that user emails be unique.
To prevent future bugs we need to clean our users table from duplicated emails.

### TODO

- [x] Agroportal
- [x] Bioportal
- [x] Stageportal
- [ ] Testportal

**Comment by jonquet** [comment]
Done. TestPortal is not available for now.

**Comment by syphax-bouazzouni** [comment]
@jonquet testportal is up, now. You can try again.

**Comment by syphax-bouazzouni** [comment]
done
