### ISSUE TITLE
Renew the license of Testportal 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#443]
<img width="1617" alt="image" src="https://github.com/agroportal/project-management/assets/29259906/fc9db6f1-c625-485b-b582-1049f9e61a22">

**Comment by jonquet** [comment]
<img width="386" alt="Capture d’écran 2023-11-10 à 20 46 06" src="https://github.com/agroportal/project-management/assets/7379183/4fecd747-1820-4865-9cf7-42dfcfbb7d9a">

I have the license available but got a 500 error when I try to submit it.
