### ISSUE TITLE
Obsolete classes/concepts in the "Historical view" are not italicize

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#444]
Go to 
https://agroportal.lirmm.fr/ontologies/BIODIVTHES?p=classes&conceptid=http%3A%2F%2Fdata.loterre.fr%2Fark%3A%2F67375%2FBLH-D3F1RQQP-0

<img width="537" alt="image" src="https://github.com/agroportal/project-management/assets/7379183/fdb14c53-4227-4bf6-9e55-4dcc2b247efa">

The UI of the "Historical view" do not italicize the name of the concept. 
It works on the hiearchy view: 

<img width="331" alt="image" src="https://github.com/agroportal/project-management/assets/7379183/2c2381eb-8ea1-4d9b-8fbc-412084a15a88">

But I am pretty sure it might not work on the "Collection view" too. I can't test has the concept deprecated are not inside collection.

**Comment by jonquet** [comment]
@SirineMhedhbi As you have worked on the displays on the left, could you handle this issue? 
Note: this is not related to recent bug fixed on obsolete... 
In this case we see that the obsolete value is true. 

<img width="603" alt="image" src="https://github.com/agroportal/project-management/assets/7379183/7e43058f-ecbf-4519-9e39-5c1c100758c8">

**Comment by SirineMhedhbi** [comment]
@jonquet  I will fix this

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/307 and https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/419
