### ISSUE TITLE
export metadata : prefix missing

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#448]
Hi there. On the agroportal (prod), I notice that the PREFIX are missing in the metadata export file in RDF/XML at least. The file is therefore not compliant (according to RDF validator). I've just looked at stageportal, and it's the same thing. I didn't look at the json-ld and n-triple files.

**Comment by jonquet** [comment]
Duplicate of https://github.com/agroportal/project-management/issues/448

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/469
