### ISSUE TITLE
metadata for dates to be clarified

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#450]
Metadata related to dates remain unclear
![image](https://github.com/agroportal/project-management/assets/18008698/da93da5e-d307-4306-8cc5-2b296884db2b)

Be more precise in the help text: Date of the **first** submission... (if it is what you expect)
submission and release are difficult to understand. Is it the same or not ? 

In the exported metadata, the date elements are confusing too

**Comment by saubin78** [comment]
This is strange too 
![image](https://github.com/agroportal/project-management/assets/18008698/c555640e-7ed0-427b-a0ec-55ad21ea89ef)

"Creation date" should be 1st release on AgroPortal
"Initially created On" --> change to Initially created on

Metadata elements are in English but values are in French. The date format is incorrect in French. It should be 12 juillet 2023.

**Comment by jonquet** [comment]
Il y a plusieurs chose ici: 

- En ce qui concerne le menu "Date of original creation" lors de la creation ... en effet c'est une erreur. 
C'est la bonne légende "Date of original creation" (qui correspond a creationDate) mais pas le bon (i) qui correspsond a released @syphax-bouazzouni 

- Dans la page Summary  le bloc Dates affichera "Creation date", "Modification date", "Validity date", "Curation date" et "Curation date" et "Submission date" . Les dates seront au format de la langue du portail. A terme les expressions (nom des propriétés seront egalkement traduites)

- La page edit submission affiche la possibilité d'éditer ces 5 dates (sauf la Submisison date qui est calculée par le portail) avec ces infos 
  label: "Creation date"
  helpText: "Date of original (or first) creation of the resource."
  label: "Modification date"
  helpText: "Date of the last modification made to the ontology."
  label: "Validity date"
  helpText: "Date of end of validity of a the ontology."
  label: "Curation date"
  helpText: "Specifies the date this resource was curated. pav:curatedBy gives the agents that performed the curation."
  label: "Submission date"
  helpText: "Date of the submission/release in the portal."

@saubin78 A verifier quand on aura tout traiter et fermer l'issue ;)

**Comment by syphax-bouazzouni** [comment]
@jonquet is it good, now?  (thanks @saubin78  for the feedback)

**Comment by jonquet** [comment]
We still have the issue that Curation date in the Edition of metadata is not a date but a text field.
Except this, I would close the issue as we in fact did the tour of all the mention of the dates in the portal to harmonize the names.
