### ISSUE TITLE
Create a note (comment, proposal) does not send the notification email to corresponding ontology contact.

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#456]
Recently experiemented with 
https://agroportal.lirmm.fr/ontologies/ANAEETHES?p=classes&conceptid=http%3A%2F%2Fopendata.inra.fr%2FanaeeThes%2Fc_57b59c10

Or 
https://bioportal.lirmm.fr/ontologies/MUEVO/?p=classes&conceptid=http%3A%2F%2Fpurl.lirmm.fr%2Fontology%2FMUEVO%2Fvpm61
=> never received the notif

**Comment by syphax-bouazzouni** [comment]
The email is sent only to the subscribed users to the ontology, not to the ontology administrators. Tested by subscribing to the ontology ANAEE and creating a note.

<img width="854" alt="image" src="https://github.com/agroportal/project-management/assets/29259906/d238f36a-cff3-4c45-815f-08ee597c9a0d">
 
 
 I update the code to send the email to the ontology admins and support email in this https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/137
