### ISSUE TITLE
Create a new mapping at the Classe level makes an error. Try on SOIL

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#459]
Source @jonquet in the https://docs.google.com/spreadsheets/d/1lEdrxJKKOJYbSYH_Ptzu2dUliHAKcFTirrw8vs9Hcuk/edit#gid=713725591&fvid=1197518333 document.

**Comment by Bilelkihal** [comment]
Fixed here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/538
