### ISSUE TITLE
Change publisher of GECO and ASCOPAIN

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#461]
Pour GECO et ASCOPAIN, nous n'arrivons pas à modifier la valeur pour publisher. La valeur actuelle "INRAE" est déclarée comme une Personne. Si on veut la remplacer par INRAE l'organisation, on a un message d'erreur. SOLUTION : changer le type de la valeur initiale (PERSON--> ORGANISATIOn). Puis on peut changer de valeur
Source: https://docs.google.com/spreadsheets/d/1lEdrxJKKOJYbSYH_Ptzu2dUliHAKcFTirrw8vs9Hcuk/edit#gid=713725591&fvid=1197518333

**Comment by jonquet** [comment]
Fixed.
