### ISSUE TITLE
problème affichage filtre collection

### ISSUE THREAD

**Issue by asbage** [agroportal/project-management#472]
Bonjour,
 nous avons repéré un problème d'affichage https://stageportal.lirmm.fr/ontologies/INRAETHES/?p=classes

le problème d'affichage apparait quand on déploie la hiérarchie puis que l'on filtre avec une première puis une seconde collection. La pastille de la collection sélectionnée en première apparait en double
![Capture-bug affichage](https://github.com/agroportal/project-management/assets/125587304/b327866d-df3b-4d76-93f1-3bc0a7e772cb)
Par contre le problème ne se produit pas si on sélectionne les filtres avant de déployer la hiérarchie.

Sonia et Anne-Sophie

**Comment by syphax-bouazzouni** [comment]
fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/465
