### ISSUE TITLE
Display of the version date

### ISSUE THREAD

**Issue by user34ngrau** [agroportal/project-management#475]
Proposition to change the date display of the ontology versions to YYYY/MM/D, like suggested by the ISO 8601 standard.

**Comment by syphax-bouazzouni** [comment]
In Stagrportal, and the incoming release of Agroportal,
the dates are localized (depending on the language), see the screenshot below 

in English 
![image](https://github.com/agroportal/project-management/assets/29259906/840c9e33-ebfe-4fa1-9c77-ed2712d465c5)

and in French
![image](https://github.com/agroportal/project-management/assets/29259906/e47ca56b-2130-4e5e-975b-1cc3f4c2b033)

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/releases/tag/v2.7.3
