### ISSUE TITLE
AGROVOC metrics fail recursively

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#477]

**Comment by saubin78** [comment]
Metrics are not computed for other resources like INRAETHES, MILKOLIGO, CDNO, INIA-RDM

![image](https://github.com/agroportal/project-management/assets/18008698/58bd8cad-bf12-465f-9757-e41c04a80fa5)

and 

![image](https://github.com/agroportal/project-management/assets/18008698/7e902cf9-450a-4375-b07d-58d1e2c717da)

**Comment by syphax-bouazzouni** [comment]
Metrics are working for AGROVOC 
![image](https://github.com/agroportal/project-management/assets/29259906/5264e0b7-5e34-4fe8-90ab-ff89d23f6575)

Same for MILKOLIGO
![image](https://github.com/agroportal/project-management/assets/29259906/a075dc75-1d7e-42b0-a639-e5573c6881fa)

And  CDNO
![image](https://github.com/agroportal/project-management/assets/29259906/a7b60241-929b-43f5-8586-647029cbb47d)
