### ISSUE TITLE
Search does not wotk for INRAETHES

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#478]
Hi,

The content of INRAETHES does not seem to be indexed. The search feature does not work (whatever the language chosen: French, English, All)
![image](https://github.com/agroportal/project-management/assets/18008698/2f21acff-eb29-4280-90da-20e130b365d6)

Is it because the project is private?

**Comment by syphax-bouazzouni** [comment]
Fixed
![image](https://github.com/agroportal/project-management/assets/29259906/bd202c66-7bbc-4777-b15f-114cdbc8007d)
