### ISSUE TITLE
Center hierarchy on the searched concept

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#479]
After searching / clicking on a concept, the hierarchy opens well and the searched concept appears in bold. But it does not appear in the frame. One needs to scroll down
 An improvement would be to center the hierarchy frame on the selected concept
Currently :
![image](https://github.com/agroportal/project-management/assets/18008698/266a8554-17e5-4bc9-99df-19f06d291ec6)

What would be nicer:
![image](https://github.com/agroportal/project-management/assets/18008698/17f10029-4630-4c0d-8869-897d45b37c50)

**Comment by Bilelkihal** [comment]
Fixed here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/646
