### ISSUE TITLE
Display of resources names rather than URIs : unstable

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#480]
When looking at a concept, the values for  "in Scheme" or "Member of"  **sometimes show as URIs** :

![image](https://github.com/agroportal/project-management/assets/18008698/f8fa23c4-27b1-4c15-9743-3462707185f2)

and **sometimes with their label** :

![image](https://github.com/agroportal/project-management/assets/18008698/26787add-9712-4679-85bc-eb7e9dcefeb3)

The 2 behaviours seem to be random

**Comment by syphax-bouazzouni** [comment]
Hello, we are fetching concept labels, after page display. So theoretically at first will display the concept IDs, but for each of them we do a request to fetch its label and replace it, this operation may take some time, but after a while, you should see only the labels.

**Comment by jonquet** [comment]
Test during meeting: 
https://agroportal.lirmm.fr/ajax/schemes/label?language=EN&ontology=INRAETHES&id=http%3A%2F%2Fopendata.inrae.fr%2FthesaurusINRAE%2Fmt_44

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/821
