### ISSUE TITLE
cannot delete a submission

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#481]
This happens with https://agroportal.lirmm.fr/ontologies/TRIPHASE
The last file does not seem to load and when I want to delete a previous submission, I get an error message :
![image](https://github.com/agroportal/project-management/assets/18008698/88507da8-4a7c-4918-955a-15e094b6f2a6)

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/agroportal/project-management/issues/481
