### ISSUE TITLE
advanced search: missing button?

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#482]
I search "pomme" in the "ontology content" on all the ontologies.
I get a list of results and I want to filter them. I open the advanced search, restrict to "INRAE thesaurus" and to French but the results don't change and I cannot find an "entry" button to click on. Am I missing something?

![image](https://github.com/agroportal/project-management/assets/18008698/0e5e2ef7-2604-4244-b7bb-669a636d32e3)

**Comment by Bilelkihal** [comment]
Fixed here:
https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/504

Now we perform an auto search when the user changes advanced options.
