### ISSUE TITLE
Edit metadata/submission : Visibility element is missing

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#484]
We need to change the visbility of INRAETHES from "private" to "public" but we found no way to edit this value.
The element is only present in the "add submission" 

![image](https://github.com/agroportal/project-management/assets/18008698/045127ff-5175-4195-b18e-c16678b45b5f)

We'd like the same in the Edit interface

**Comment by syphax-bouazzouni** [comment]
You can find the private field, on the edit submission page, in the section "licensing"
![image](https://github.com/agroportal/project-management/assets/29259906/5ae05083-3c66-482d-88cd-6533dd68d96c)
Please @saubin78 close this issue, if it worked for you.

**Comment by saubin78** [comment]
Thank you. We had thought of it but hadn't seen it, and the term "Visibility" is not searchable in Edit ontology / Filter properties to show (like others on the 1st page of metadata editing, such as "administrator", "representation language", etc.).

**Comment by syphax-bouazzouni** [comment]
Yes, we have noticed this issue, I propose to let open this issue, So that I remember to fix it, thanks.

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/669
