### ISSUE TITLE
FAIRness service failure

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#485]
It seems that it is the same problem with all ontologies, in the Home page and also on stageportal

![image](https://github.com/agroportal/project-management/assets/18008698/ae90dc42-3c16-4496-afd1-51327fc2d610)
![image](https://github.com/agroportal/project-management/assets/18008698/9df73644-0e57-4c89-a661-fa979bf80552)

**Comment by saubin78** [comment]
also, why is the block about FAIRness score is absent from the page for Agrovoc?

**Comment by syphax-bouazzouni** [comment]
O'FAIRE vizualization fixed in Agroportal.

For Agrovoc, they asked us to disable it for them.
