### ISSUE TITLE
Concept URL (in hierarchy) opens a strange page

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#486]
Copy the link of a concept in a hierarchy like :
![image](https://github.com/agroportal/project-management/assets/18008698/2cf553cc-ab91-4574-bc54-74dbad70821c)

and paste it (https://agroportal.lirmm.fr/ontologies/INRAETHES/concepts/?id=http%3A%2F%2Fopendata.inrae.fr%2FthesaurusINRAE%2Fc_3171&language=FR) in a browser, it displays this:

![image](https://github.com/agroportal/project-management/assets/18008698/57a54f4a-8f83-484a-8924-11ed636f175b)

It looks like a frame of the concept page. Could we have the complete Agroportal UI instead like : 
![image](https://github.com/agroportal/project-management/assets/18008698/463cafb6-46be-441c-8594-2a203e85fe56)

**Comment by syphax-bouazzouni** [comment]
fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/613 

https://github.com/agroportal/project-management/assets/29259906/c0b245a3-7ca3-4ef7-957d-4852598acaf9
