### ISSUE TITLE
 "Mappings" tab does not show any mappings (though there are)

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#487]
For https://agroportal.lirmm.fr/ontologies/INRAETHES mappings can be displayed at concept level but not for the entire thesaurus

![image](https://github.com/agroportal/project-management/assets/18008698/2bc4e785-8739-4ac2-9602-7f3518fc43bb)

though 

![image](https://github.com/agroportal/project-management/assets/18008698/4f54071e-6f6b-4972-ba32-75b76b71a208)

**Comment by jonquet** [comment]
Indeed, it embarassing..

**Comment by syphax-bouazzouni** [comment]
Mappings seem to be back for this ontology
![image](https://github.com/agroportal/project-management/assets/29259906/b1c83c52-0ded-471c-9742-3f27399753f0)

Maybe related but we have a strange behavior in the API, where it says there are 1188 mappings, but returns an empty array
![image](https://github.com/agroportal/project-management/assets/29259906/8585814a-bb9e-449d-9d4f-5ec8fb0d8c0b)

**Comment by syphax-bouazzouni** [comment]
Seems to be fixed  
![image](https://github.com/agroportal/project-management/assets/29259906/08394a64-4fdc-454e-a5a2-1e218ab9d721)
