### ISSUE TITLE
error 404 - page URL

### ISSUE THREAD

**Issue by user34ngrau** [agroportal/project-management#489]
when I get a error 404 page and I click on "send feedback" the field: "error/proposition page URL" isn't pre-filled. Could be a good idea to have it, and avoid to go back to the failed page to get the URL page.

**Comment by Bilelkihal** [comment]
Fixed here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/613

**Comment by syphax-bouazzouni** [comment]
@Bilelkihal, if it is global PR that fixes multiple issues, when closing the issue put also the corresponding  commit
