### ISSUE TITLE
cannot edit version information 

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#491]
On https://agroportal.lirmm.fr/ontologies/TRANSFORMON, we can edit the version information but it is NOT saved.
We want to change from 2.3 to 4.0

![image](https://github.com/agroportal/project-management/assets/18008698/9260e480-8baf-4c76-8c64-7f56dcc2766f)

**Comment by syphax-bouazzouni** [comment]
here is what we can see in the triplestore, we saved "4.0" but can't remove the old "2.3"^String. This occurred while we did the migration to 2.7.0. 

![image](https://github.com/agroportal/project-management/assets/29259906/9148584a-4d04-4fef-bd1c-13da87cc7856)

So I had to remove it using SPARQL delete query, bellow:

```ruby
Goo.sparql_update_client.response("DELETE { 
         <http://data.bioontology.org/ontologies/TRANSFORMON/submissions/4>  
         <http://omv.ontoware.org/2005/05/ontology#version> ?obj .
      } 
WHERE { 
          <http://data.bioontology.org/ontologies/TRANSFORMON/submissions/4> 
         <http://omv.ontoware.org/2005/05/ontology#version> ?obj . 
}")
```

**Comment by syphax-bouazzouni** [comment]
Now we see the correct version
![image](https://github.com/agroportal/project-management/assets/29259906/59e46450-d956-4f20-af4a-7f7b50a7b0f2)
