### ISSUE TITLE
add a space between ontology name and acronym in  search

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#493]
A space is missing before the opening bracket of the acronym
![image](https://github.com/agroportal/project-management/assets/18008698/1635c91c-2bd7-4551-b1c4-07f96e3e4104)

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/505
![image](https://github.com/agroportal/project-management/assets/29259906/7aa57963-697a-476f-8b6a-6497c3d5d317)
