### ISSUE TITLE
Search does not work in the Instances tab

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#495]
I am working on StagePortal with a resource that mixes owl:Class and skos:Concept : WTOTEST
First, the good news is that both classes and concepts can be displayed in their respective tabs.
Yet, I noticed that the search does not give any results
Example: resistance 
![image](https://github.com/agroportal/project-management/assets/18008698/a60d4cd7-206c-4ce5-ae67-a2c48f27bcbd)

**Comment by syphax-bouazzouni** [comment]
It does work but only for ` rdfs:label` I think,  we will extend it in the near future to work as the concepts search. 
![image](https://github.com/agroportal/project-management/assets/29259906/124f6ab7-4d46-48e6-9906-094cda0b41d2)

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/550
![image](https://github.com/agroportal/project-management/assets/29259906/60df0ee2-cc9c-4511-b568-4fc55ad8d303)
