### ISSUE TITLE
Logical axioms (equivalentClass or subClassOf done with ow:Restriction) are transformed into direct triples by our backend

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#499]
I like to investigate a bit how we deal with logical axioms in AgroPortal. 

Lets take SFWO as an example: https://agroportal.lirmm.fr/ontologies/SFWO 

_We use logical axioms a lot, because our ontology is designed for applications that use reasoning.
Here is an example of a logical definition:
microbivore (http://purl.org/sfwo/SFWO_0000061) = eats some microorganism
We also have some General Class Axioms:
microbivore and ('member of' some Oribatida) SubClassOf 'member of' value Oribatida.microbivores_

Indeed the source file show this: 
(e.g. RO_0002470 = "eats")

<img width="639" alt="Capture d’écran 2024-03-08 à 11 53 46" src="https://github.com/agroportal/project-management/assets/7379183/b4b60562-d059-4226-895a-f555cdff902e">
 
and later
(with NCBITaxon_66551 = "Oribatida)

<img width="698" alt="Capture d’écran 2024-03-08 à 11 59 06" src="https://github.com/agroportal/project-management/assets/7379183/4baa8081-cf1c-42c5-99b0-5cf4f09e3713">

Then our API call for the resulted class in our backend is : 
https://data.agroportal.lirmm.fr/ontologies/SFWO/classes/http%3A%2F%2Fpurl.org%2Fsfwo%2FSFWO_0000061?display=all

But this shows that on our side the equivalentClass and restriction has been transformed into a direct triple : 
SFWO_0000061 (subject) RO_0002470 (predicate) SFWO_0000062 (object)

<img width="491" alt="Capture d’écran 2024-03-08 à 12 02 44" src="https://github.com/agroportal/project-management/assets/7379183/eedbb6e9-c37f-4c2a-bb0a-07bb7886a319">

Which is confirmed by our triple store: 
<img width="785" alt="Capture d’écran 2024-03-08 à 12 05 26" src="https://github.com/agroportal/project-management/assets/7379183/18a98c84-49c0-4c91-bdd1-77412624290c">

And the  General Class Axioms do not even appear... they are not parsed/treated.

**Comment by jonquet** [comment]
I am not sure of what we should do exactly to "deal with" these logical axioms ... but I am not crazy about the fact that we flatten the owl:Restriction into a triple. 
@jvendetti an idea ?

**Comment by syphax-bouazzouni** [comment]
Where do you see the flattened axioms ? did they not  disappear;

**Comment by jonquet** [comment]
Well in the UI, in the Raw data part, the json triple is basically displayed like this: 
<img width="501" alt="Capture d’écran 2024-03-08 à 12 29 23" src="https://github.com/agroportal/project-management/assets/7379183/a29e3b65-7a0b-419a-8817-31c0ed1b371d">

**Comment by jonquet** [comment]
Related to this... need investigation: CO_356 has similar OWL restrictions statements but they are not "flatten" into simple relation by the OWL-API. 
Source file
<img width="643" alt="Capture d’écran 2024-03-13 à 17 08 04" src="https://github.com/agroportal/project-management/assets/7379183/21a8a8ac-47c2-4df1-a410-d53d72c44682">

Result in AgroPortal
<img width="508" alt="Capture d’écran 2024-03-13 à 17 09 37" src="https://github.com/agroportal/project-management/assets/7379183/2da6a433-a8f0-49ce-a4ca-415a59c577dc">

To do: 
- [ ] Check with reparsing if this is not an OWL-API parametrization or versioning issue.
- [ ] Upload new version from URI
- [ ] ??

**Comment by syphax-bouazzouni** [comment]
duplicate of  https://github.com/agroportal/project-management/issues/217
