### ISSUE TITLE
Unexplained missing triple from a class in CO_356

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#500]
Go to : 
https://agroportal.lirmm.fr/ontologies/CO_356?p=classes&conceptid=https%3A%2F%2Fcropontology.org%2Frdf%2FCO_356%3A2000005

We do not display in "Raw data" the 2 relations 'entity' and 'attribute' that are within the source file: 
<img width="797" alt="Capture d’écran 2024-03-13 à 17 25 43" src="https://github.com/agroportal/project-management/assets/7379183/a361f83e-fd27-441f-b648-8c5a5ec93fcb">

Protégé does: 
<img width="477" alt="Capture d’écran 2024-03-13 à 17 26 49" src="https://github.com/agroportal/project-management/assets/7379183/1c7e509b-d107-455d-b382-9bc8b877574b">

**Comment by syphax-bouazzouni** [comment]
Fixed with https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/584
![image](https://github.com/agroportal/project-management/assets/29259906/758f974a-9c79-41ae-87d9-3207b6888174)
