### ISSUE TITLE
Le chargement d'une nouvelle soumission pour CO_356 génère une erreur 

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#503]
Le chargement d'une nouvelle soumission pour CO_356 génere une erreur 

<img width="530" alt="Capture d’écran 2024-03-12 à 17 29 43" src="https://github.com/agroportal/project-management/assets/7379183/9468b6b1-b0ff-4613-ae47-2edfba640807">

**Comment by syphax-bouazzouni** [comment]
Pour la signification de `proc_naming` , c’est ce message d’erreur `There is already a persistent resource with id #{@id.to_s}`  qui n’est pas afficher car dans la nouvelle UI on affiche que les labels(keys) des erreurs.

Et vous avez eu cette erreur car cette ontologie avez deja une soumission zombie avec le meme ID, ce qui fait que vous pouviez pas faire de nouvelle soumission dans l’UI, mais que ca marche en ligne de commande.

**Comment by jonquet** [comment]
Ok donc après investigation il y a bien une soumssion zombie (la 42) qui empêche de mettre une nouvelle soumission. 
<img width="296" alt="Capture d’écran 2024-07-03 à 11 08 19" src="https://github.com/agroportal/project-management/assets/7379183/734459ee-1f9e-4f18-acc1-b455412cbc69">

mais cela renoie rien: 
[https://data.agroportal.lirmm.fr/ontologies/CO_356/submissions/42?display=all](https://data.agroportal.lirmm.fr/ontologies/CO_356/submissions/42?display=all)

On doit faire le nettoyage manuelleent. 
Je peux faire le repertoire sur le serveur, mais @syphax-bouazzouni pourrait tu verifier qu'il y apas de graphe zombie aussi dans le triple store ?

**Comment by syphax-bouazzouni** [comment]
@jonquet, I removed submission 42, you can now create new submissions and close this issue if done.

**Comment by jonquet** [comment]
Bon ok , j'ai ajouté une soumission et cela ne que partiellemnt marché. 
En fait, il a repris le fichier de la 41 comme fichier source. Et pas celui à la pullLocation. Bizarre.

J'ai ensuite essayé (apres le parsing qui s'est bien passé et du oup apres avoir envoyé l'email aux utilisateurs @cpommier entre autres) .. de changer via l'API les valeurs des propriétés pas mise à jour vers :  
"uploadFilePath": "/srv/ontoportal/data/repository/CO_356/42/CO_356-Vitis-inra-ontology.nt",
"diffFilePath": "/srv/ontoportal/data/repository/CO_356/42/bubastis_diff.xml"

Mais cela n'a pas marché. J'ai bien un 204 mais pas de changement dans le JSON. Comme vu ici: 
https://data.agroportal.lirmm.fr/ontologies/CO_356/submissions/42?display=uploadFilePath,diffFilePath

Donc nouvelle tentative de chargement d'une nouvelle soumission (quie devrait etre la 43) et qui je l'espere prendra le bon fichier source.

**Comment by jonquet** [comment]
Closing this. New verion loaded for CO_356
