### ISSUE TITLE
Can't remove admin user from Admistrators metadata from a bunch of ontologies

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#504]
<img width="559" alt="Capture d’écran 2024-03-14 à 14 49 22" src="https://github.com/agroportal/project-management/assets/7379183/dc8cdea8-b957-47e8-866e-3dea09dbdaa4">

**Comment by syphax-bouazzouni** [comment]
Done 


![Image](https://github.com/agroportal/project-management/assets/29259906/c1fe5a37-6302-4d0b-8f4d-7ac6168d7363)

An ontology need at least one administrator, so i replaced it when necessary wit `jonquet` user
