### ISSUE TITLE
Deleting submission from UI fails (CSOPRA)

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#506]
Go to https://agroportal.lirmm.fr/ontologies/CSOPRA?p=summary connected as admin
Try to remove a submission with "unkwon version" 

<img width="722" alt="Capture d’écran 2024-03-28 à 22 10 30" src="https://github.com/agroportal/project-management/assets/7379183/a103af2a-9cb5-4e2f-b7ed-7955f53a6caa">

**Comment by jonquet** [comment]
Do not close the issue before we have used the prod UI to clean number 95, 96, 97, and 98 
Then we will need to clean the server that constains bunch of zombie folders. 

Related to #505

**Comment by syphax-bouazzouni** [comment]
fixed in  https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/585
