### ISSUE TITLE
Add new submission  page feedback

### ISSUE THREAD

**Issue by user34ngrau** [agroportal/project-management#510]
1- Home Page : Add "My AgroPortal Account" 
Why: Would be nice to have something different than "Account setting"
<img width="289" alt="Capture d’écran 2024-04-05 à 15 16 02" src="https://github.com/agroportal/project-management/assets/135241416/5b2efc0c-36bd-4a52-a5ee-cef78f3fc5c8">

2-Submission Page (Date & contact): Change "creation date"
Why: would be easier to be able to enter the date by hand (be careful to use ISO standard: YYYY-MM-DD)
<img width="341" alt="image" src="https://github.com/agroportal/project-management/assets/135241416/c8a00fad-08ec-4b75-8a6d-3bcf3965a27d">

3- Submission Page (General information): Change "Status default"
Why: would be better to have a "production" status instead of "alpha" status
<img width="548" alt="image" src="https://github.com/agroportal/project-management/assets/135241416/b9310d99-0cdd-4271-996a-fd58d9a2587e">

4- Subscription or Submission Page : Add preferential institutional email for contact
Why: would be better to have contact's institutional email while personal address. 
<img width="548" alt="image" src="https://github.com/agroportal/project-management/assets/135241416/183ad828-6956-4aa0-a9ec-56d758dcf12c">

**Comment by jonquet** [comment]
I would discard proposition 1 and 2. 
Not "my" because we use this expression for something else. 
Not date because we worked on harmonizing all of this already.

**Comment by syphax-bouazzouni** [comment]
> I would discard proposition 1 and 2. Not "my" because we use this expression for something else. Not date because we worked on harmonizing all of this already.

I would replace 1; with `Account details` instead of `Account settings`

**Comment by Bilelkihal** [comment]
For the 3, done here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/625
for the 2, the field's gonna be pre filled with today's date, so it will show the form that u need to write it in (u can enter it by hand or use the selector)

For the 1 I agree with syphax, I think account details is better than account settings.

And the 4th one I don't really understand what do you mean @user34ngrau

**Comment by jonquet** [comment]
4th is about adding small indication maybe as a (i) on the email fields to say: "Prefer an institutional email address.".. 
But I don't think we should bother too much on this.
