### ISSUE TITLE
Information popup about datatables

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#512]
This happens on the "Classes" tab on stageportal for WTOTEST.
This ontology mixes owl:Classes and skos:Concepts (no idea if it is related)
![image](https://github.com/agroportal/project-management/assets/18008698/def9e17c-c9d5-4f96-b582-60903ef12ff2)

**Comment by syphax-bouazzouni** [comment]
Can't reproduce the issue, can you (@saubin78 ) give us the link on which this appears? (which concept is selected ?)

**Comment by saubin78** [comment]
It happens after a search : enter "tolerance" in the search box (class tab) and choose "tolerance to extreme termperature"

**Comment by jonquet** [comment]
Just saw it too on stage when browisng the Sumamry page of https://stageportal.lirmm.fr/ontologies/CO_325
<img width="1295" alt="Capture d’écran 2024-04-22 à 22 23 48" src="https://github.com/agroportal/project-management/assets/7379183/9e1dd629-670a-4f5d-ac90-11a7fcdd170b">

**Comment by Bilelkihal** [comment]
Fixed here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/624
