### ISSUE TITLE
False EN prefLabel generated when there is no english label for a concept

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#515]
Go to: 
https://agroportal.lirmm.fr/ontologies/AGROTERMOS?p=classes&conceptid=https%3A%2F%2Fsistemas.sede.embrapa.br%2Fagrotermos%2Fresources%2F2f7fc3250e134e16c53268ba949d79ec&language=all

<img width="410" alt="Capture d’écran 2024-04-16 à 21 26 46" src="https://github.com/agroportal/project-management/assets/7379183/de05dcdd-7e34-4ebf-b8da-d9b3b7e2f17e">

Whereas the source file does not contains this label.

Then this false label "take over" real one int he hierachy (when all languages is selected): 
<img width="392" alt="Capture d’écran 2024-04-16 à 21 29 36" src="https://github.com/agroportal/project-management/assets/7379183/7107442d-a97f-4e47-b4cf-84ea43816789">

**Comment by jonquet** [comment]
Then this false label "take over" real one int he hierachy (when all languages is selected): 
<img width="392" alt="Capture d’écran 2024-04-16 à 21 29 36" src="https://github.com/agroportal/project-management/assets/7379183/7107442d-a97f-4e47-b4cf-84ea43816789">

**Comment by syphax-bouazzouni** [comment]
At the parsing level, if we don't find for a concept a label in English or not tagged, we generate one, with no language tag(see the highlighted line in the screenshot below). 

For the why we show here the generated label and not the portuguese one, in the "all languages" option. it is because Portuguese is not a priority, over the English or no-tagged values.

![image](https://github.com/agroportal/project-management/assets/29259906/f007af4d-eea4-4176-ab1a-72f6b05a8016)

**Comment by jonquet** [comment]
To be discussed again.
The behaviour is not really ok. Using the ID/notation as label is supposed to be a fall back in the UI but not a fallback in the backend (with a false triple generated) which then provoques a weird behaviour in the UI.

**Comment by jonquet** [comment]
Note that with THESAGRO we see this behaviour (within the tree) is not consistent (random pick up a label): 
<img width="171" alt="Capture d’écran 2024-04-27 à 04 48 50" src="https://github.com/agroportal/project-management/assets/7379183/61bde85f-37e2-41e9-9b9e-dfad9d155bf8">

**Comment by syphax-bouazzouni** [comment]
Is it fixed @jonquet, in Stageportal after the latest release, if we select Brazilian we get the label in that language and not our generated ones that are now explicitly tagged as English. 
https://stageportal.lirmm.fr/ontologies/AGROTERMOS?p=classes&language=pt-br

**Comment by jonquet** [comment]
Oui ce que tu decris est ok.
Par contre, je ne vois pas les labels autogénérés "explicitly tagged as English." => https://data.stageportal.lirmm.fr/ontologies/AGROTERMOS/classes/https%3A%2F%2Fsistemas.sede.embrapa.br%2Fagrotermos%2Fresources%2Fa6be24e7693ef30543e329dd3bc971a0?&display=all 
et tant mieux d'ailleurs. 
Et dans l'UI on a pas non plus les tag qui s'affiche pour ce faux label. Donc je pense que c'est mieux. 

A noter que l'issue originale était a propos du comportement de générer automatiquement un label en EN si on en a pas (car c'est le language par défaut du portail). Et sur ca on avait dit qu'on avait pas trop le choix je crois me souvenir.

**Comment by syphax-bouazzouni** [comment]
@jonquet bellow a screenshot showing the generated label 
![image](https://github.com/user-attachments/assets/be1e73f2-2c77-4ee9-9324-e039303b9b56)
Before we didn't generate it 
![image](https://github.com/user-attachments/assets/8a61a72e-474e-4a8e-9d1b-286434e1e105)

**Comment by jonquet** [comment]
Ok merci de ces précisions. We are aligned. 

If we consider we won't fix the fact that we generate "false labels" for the default portal language, then we could close this issue. 
One thing remain : wen we select "All languanges" in the UI, the false non language-tagged label "takes over" one real label in another language. 
See 
https://stageportal.lirmm.fr/ontologies/AGROTERMOS?p=classes&language=all
<img width="248" alt="Capture d’écran 2024-10-29 à 16 37 39" src="https://github.com/user-attachments/assets/0e582b00-80cc-483a-a564-39169062d7e2">

The question is: shall we pick up "another" label for which we have a language info.. in this case "Dicotiledónea"?

**Comment by syphax-bouazzouni** [comment]
> Ok merci de ces précisions. We are aligned.
> 
> If we consider we won't fix the fact that we generate "false labels" for the default portal language, then we could close this issue. One thing remain : wen we select "All languanges" in the UI, the false non language-tagged label "takes over" one real label in another language. See https://stageportal.lirmm.fr/ontologies/AGROTERMOS?p=classes&language=all <img alt="Capture d’écran 2024-10-29 à 16 37 39" width="248" src="https://private-user-images.githubusercontent.com/7379183/381201315-0e582b00-80cc-483a-a564-39169062d7e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyODQ1NzgsIm5iZiI6MTczMDI4NDI3OCwicGF0aCI6Ii83Mzc5MTgzLzM4MTIwMTMxNS0wZTU4MmIwMC04MGNjLTQ4M2EtYTU2NC0zOTE2OTA2MmQ3ZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzBUMTAzMTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzM5MmIwOGZhNTFlZmVlMGI3ODYxODFiMGVkNmU4ZGY2MGE3M2E3NWM2NjNmNGY3NjU4ZDk2MDRmYWU1OTJjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ImP5qYfxrqFSUfzDNhBJntq6dYKWmzt8oma3EAXRcBc">
> 
> The question is: shall we pick up "another" label for which we have a language info.. in this case "Dicotiledónea"?

Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/795 and https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/164
