### ISSUE TITLE
Classe manquante (FCU)

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#517]
Bonjour,

j'ai fait une recherche dans le module Search de l'onglet Concept : chou cabu. Le concept m'est proposé en autocomplétion mais j'aboutis à une 404

![image](https://github.com/agroportal/project-management/assets/18008698/efd4ff0b-5340-447a-bb6e-f98e120d0fb9)

**Comment by syphax-bouazzouni** [comment]
Using the correct URI `https://opendata.inrae.fr/fcu-res/Choux_cabus_verts`, the concept seems to exist https://agroportal.lirmm.fr/ontologies/CROPUSAGE?p=classes&conceptid=https%3A%2F%2Fopendata.inrae.fr%2Ffcu-res%2FChoux_cabus_verts

But the indexed URI is not correct `http://ontology.inrae.fr/frenchcropusage/Choux_cabus_verts`

**Comment by jonquet** [comment]
D'habitude on dit que c'est plutôt "chou blanc" quand ca marche pas ...

**Comment by syphax-bouazzouni** [comment]
It seems to be fixed after the re-index 
![image](https://github.com/agroportal/project-management/assets/29259906/c0d5f0f0-e725-429c-ad29-6b9e53966801)
