### ISSUE TITLE
Lose context when changing the language in the concepts date view

### ISSUE THREAD

**Issue by Bilelkihal** [agroportal/project-management#518]
### Problem Description:
When switching languages in the concepts date view, the app reverts back to the Hierarchy view, causing the loss of context (specific term selection).

### Expected Behavior:
Changing the language in the date view should retain the current view state and selected term.

### Demo
[Capture vidéo du 18-04-2024 21:08:39.webm](https://github.com/agroportal/project-management/assets/61744974/a4046424-e101-4cc1-a6ef-89ba08fe26e6)

**Comment by syphax-bouazzouni** [comment]
Related https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/557

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/642
