### ISSUE TITLE
La recherche de propriété est case sensitive

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#520]
Sur StagePortal, la recherche de propriété (Jump to) est case sensitive ce qui exclu des resultats: 
Testé sur AGROVOC

<img width="335" alt="Capture d’écran 2024-04-22 à 22 46 11" src="https://github.com/agroportal/project-management/assets/7379183/d7e8d3da-53c3-414c-abcc-728a347a9a7c">

tandis que 

<img width="321" alt="Capture d’écran 2024-04-22 à 22 46 30" src="https://github.com/agroportal/project-management/assets/7379183/26df2c29-5fcc-4d0a-b09e-97a48e96cccc">

Seul le "Jump to" des propriétés à l'air affecté. J'ai testé les autres.

**Comment by jonquet** [comment]
Cela affecte aussi la Search ox de la barre de navigation : 
<img width="234" alt="Capture d’écran 2024-04-22 à 22 52 17" src="https://github.com/agroportal/project-management/assets/7379183/40bd9363-9507-4783-9a3e-82d895f4a3f2">

Et a noter que la recherche par label de propriété ne marche pas aussi: essayé avec "Is use of"

**Comment by jonquet** [comment]
Egalement sur la page /search on ne peut pas trouver les propriétés non plus: 
https://stageportal.lirmm.fr/search?q=isUseOf&lang=all
ou 
https://stageportal.lirmm.fr/search?q=isuseof&lang=all
ou 
https://stageportal.lirmm.fr/search?q=%22is+use+of%22&lang=all
Moved to https://github.com/agroportal/project-management/issues/522

**Comment by syphax-bouazzouni** [comment]
it is case-sensitive on IDs, not labels
* Label downcase   -> found 
![image](https://github.com/agroportal/project-management/assets/29259906/cd32a712-9382-42f9-8133-6973378d9710)
* Label up case -> found
![image](https://github.com/agroportal/project-management/assets/29259906/458d8eaa-2a76-47af-a0c0-9c90c1d329ab)
* Label mixed case -> found 
![image](https://github.com/agroportal/project-management/assets/29259906/77c84b9c-d6f5-4a5f-b03e-9e2e50849f2d)

Not sure what is the best approach for IDs, to have exact matches or case insensitive. 
I will make it insensitive for now https://github.com/ontoportal-lirmm/goo/pull/59

**Comment by syphax-bouazzouni** [comment]
fixed in https://github.com/ontoportal-lirmm/goo/pull/59, will work after doing a re-indexation of the ontogies
