### ISSUE TITLE
La recherche de propriété via la Search box de la barre de navigation nous fait atterrir ailleurs

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#521]
Sur StagePortal, tester avec "isUseOf"

<img width="240" alt="Capture d’écran 2024-04-22 à 22 49 54" src="https://github.com/agroportal/project-management/assets/7379183/92db4cf7-0a35-4fd5-98e9-e8fe1516ac81">

Et quand selectionné on atterit sur : Accrual Method
Qui semble être la "premiere" propriété de AGROVOC

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/596
