### ISSUE TITLE
Agents issues

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#523]
### Issues 
* https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/589
* https://github.com/agroportal/project-management/issues/571
* https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/591
* https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/592
* https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/123
* https://github.com/agroportal/project-management/issues/471
* https://github.com/agroportal/project-management/issues/465
* https://github.com/agroportal/project-management/issues/577
* https://github.com/agroportal/project-management/issues/545
* https://github.com/agroportal/project-management/issues/543
* https://github.com/agroportal/project-management/issues/544

**Comment by jonquet** [comment]
Lets remove the constraints that we have related to creator and contributor to be "person" only . .. ;and relax it to "agent"
<img width="1090" alt="Capture d’écran 2024-04-30 à 16 48 59" src="https://github.com/agroportal/project-management/assets/7379183/49bcbf54-2d05-4387-a000-4553f3742041">

I have already experienced 3 situations where it was impossible to actually save change to the ontology ... after editing the contributor (which were organisation) properly. 

- [ ] Fix FOODEX contributors after release of this to get FAO and Tufts U.

**Comment by jonquet** [comment]
Aussi, il faudrait que le popup qui permet de lectionner un agent deja existant ne soit pas limité a 4 proposiiton mais qu'il en inclus au moins 10 avant "create a new"

**Comment by jonquet** [comment]
Aussi, essayer de "curer" les différents agent "FAO" pour voir d'autres problemes de suppression d'agent qui sont difficiel a tracer.

**Comment by jonquet** [comment]
@syphax-bouazzouni ... on vient de discuter ca ce jour avec @Bilelkihal .. on avait bien dit qu'on aller enlever la contrainte que certains agent devait etre de type person ? on a bien des ontologies qui veulent avoir des creator ou contributor qui soit des organisations. 
Est-ce qu'il y a une issue la dessus ?

**Comment by Bilelkihal** [comment]
@syphax-bouazzouni 
You okay with last comment?

**Comment by syphax-bouazzouni** [comment]
> @syphax-bouazzouni You okay with last comment?

Yes, I'm OK with that, less problems to handle. 



> Lets remove the constraints that we have related to creator and contributor to be "person" only . .. ;and relax it to "agent" <img alt="Capture d’écran 2024-04-30 à 16 48 59" width="1090" src="https://private-user-images.githubusercontent.com/7379183/326855354-49bcbf54-2d05-4387-a000-4553f3742041.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzIzNDMsIm5iZiI6MTcyMTEzMjA0MywicGF0aCI6Ii83Mzc5MTgzLzMyNjg1NTM1NC00OWJjYmY1NC0yZDA1LTQzODctYTAwMC00NTUzZjM3NDIwNDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMTIxNDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWEyYTJjZTk0ZjQ4Yjk0MTlmZDA2M2Y5NTY2OTJkY2MzNTMxOWQyZWE3NDExNzgyODU2NmYzZjVjYjZiOWRhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.j6zlkMi5Z2A6BhAnw-o5QXd-NABb-aYPrfoFEQtT5WM">
> 
> I have already experienced 3 situations where it was impossible to actually save change to the ontology ... after editing the contributor (which were organisation) properly.
> 
> * [ ]  Fix FOODEX contributors after release of this to get FAO and Tufts U.

The details are in the comment above, you can create an issue from that.

**Comment by syphax-bouazzouni** [comment]
Close this as most issues are done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/712, the remaining are in https://github.com/agroportal/project-management/issues/598
