### ISSUE TITLE
Automatic assignent of the property "downloadURL" and download button

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#526]
I would suggest to double check we always by default assign the property 
"downloadURL" the value 
https://data.agroportal.lirmm.fr/ontologies/XXX/download?download_format=rdf

It seems to be the case (all last upload have it right). 
- [ ] But I need to curate to harmonize

However, for the download button on the Sumamry page within the General information block... I would not put the "downloadURL" property in the back but the links.download value for XXX whcih will be 
https://data.agroportal.lirmm.fr/ontologies/XXX/download

This means that the "button" visible on the web page will re-distribuute the original source file ... not the RDF/XML one that we generate.

**Comment by syphax-bouazzouni** [comment]
Change the default value to not use `download_format=rdf` in this PR https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/151.

I also migrated all the current ontologies dataDump values to be `ontologies/:ontology/donwload`
