### ISSUE TITLE
Le graphique qui affiche les relations d'ontologies n'affiche pas la propriété bpm:viewOf

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#528]
Voir le chargement recent de https://agroportal.lirmm.fr/ontologies/PPD-OLT
qui est une vue de PPDO

Nous n'affichons pas la vue dans le network des propriétés.

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/716
