### ISSUE TITLE
Erreur au moment de la modification de la version des submission precedentes de STY

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#530]
Le changement de versionInfo des submissions 1 et 2 de STY génère un 404.

**Comment by syphax-bouazzouni** [comment]
Same issue as  https://github.com/agroportal/project-management/issues/397, I will need to do it manually by command line. So @jonquet can you give the correct version to put for submissions 1 and 2.

**Comment by jonquet** [comment]
2015AA => 12 (2015AA)
2021AB => 12 (2021AB)

For the records, right STY versions are displayed there: https://lhncbc.nlm.nih.gov/semanticnetwork/SemanticNetworkArchive.html

**Comment by syphax-bouazzouni** [comment]
Done 
![image](https://github.com/user-attachments/assets/8b0393f4-82ba-4636-bc54-19072afdc9a2)
