### ISSUE TITLE
Direct link to Notes (as included in the notification email) are broken

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#531]
The email (received 27 april 2024 for a notre created in March 23!) contains the following link that does not bring you to the note

https://agroportal.lirmm.fr/notes/http%3A%2F%2Fdata.agroportal.lirmm.fr%2F%2Fnotes%2Fd9dcdc00-ab98-013b-882f-5254006dce65

The note is here: https://agroportal.lirmm.fr/ontologies/SDNDEV?p=classes&conceptid=http%3A%2F%2Fvocab.nerc.ac.uk%2Fcollection%2FL05%2Fcurrent%2F368%2F

Seems direct link to Notes are broken.

**Comment by syphax-bouazzouni** [comment]
fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/606
