### ISSUE TITLE
Changer l'affichage des categories sur la page summary pour lettre les acronymes

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#532]
Avec mouse over les noms. 

La y en a trop... ca prends torp de place et casse le flot de la page
<img width="585" alt="Capture d’écran 2024-04-27 à 12 16 45" src="https://github.com/agroportal/project-management/assets/7379183/b298392f-6011-42a2-b69e-edd76207500a">

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/713
