### ISSUE TITLE
Supprimer une ontologie via le tableau des versions genere un bug. 

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#536]
<img width="722" alt="Capture d’écran 2024-05-02 à 19 13 27" src="https://github.com/agroportal/project-management/assets/7379183/225a9a19-567f-4b29-a544-047a2388981a">

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/585 , just not yet released in production (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/564).
