### ISSUE TITLE
Tout nouveau chargement se retrouve avec une valeur par défaut fausse pour Root of obsolete branch

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#541]
Testé recement avec THESAGRO: 

<img width="453" alt="Capture d’écran 2024-05-07 à 09 44 00" src="https://github.com/agroportal/project-management/assets/7379183/7be77b4d-0192-4a07-ab96-35f2830b17fc">

Ce tte propriété est généralement fausse par defaut: http://www.geneontology.org/formats/oboInOwl#ObsoleteClass

Ne devrait pas être attribuée.

**Comment by jonquet** [comment]
Bon en  fait j'oublié mais cela concerne toutes les autres "Object description properties" aussi pour lequel on doit changer le comportement pare défaut. Sans doute capturé dans un autre issue.

**Comment by syphax-bouazzouni** [comment]
Done in  https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/144
