### ISSUE TITLE
Metadata values to correct after release 2.8

### ISSUE THREAD

**Issue by toineau2007** [agroportal/project-management#543]
Working today with @jonquet on metadata and agent curation, we list here the values to propagate after the constraint (agent of type person only) is removed:

- [x]  AGFOOD creator INIST
- [x]  LANDVOC contributor Henrique Pires dos Santos
- [x]  LANDVOC contributor FAO
- [x] AGRONTOLOGIE creator FAO
- [x] AGROVOC ccreator FAO
- [x] LANDVOC contributor International Center for Agriculturla research dy ares

**Comment by jonquet** [comment]
To be used : 

https://github.com/alanruttenberg

**Comment by jonquet** [comment]
Claus: claus.weiland@senckenberg.de

**Comment by jonquet** [comment]
cyrille.violle@cefe.cnrs.fr

**Comment by jonquet** [comment]
daniel.faria.81@gmail.com

**Comment by jonquet** [comment]
dominique.vachez@inist.fr

**Comment by jonquet** [comment]
e.arnaud@cgiar.org

**Comment by jonquet** [comment]
[erick.antezana@gmail.com](mailto:erick.antezana@gmail.com)

**Comment by jonquet** [comment]
florence.amardeilh@elzeard.co

**Comment by jonquet** [comment]
franck.michel@cnrs.fr

**Comment by jonquet** [comment]
isabelle.mougenot@umontpellier.fr

**Comment by jonquet** [comment]
[james@overton.ca](mailto:james@overton.ca)

**Comment by jonquet** [comment]
jan.top@wur.nl

**Comment by jonquet** [comment]
Jean-Pierre Chanet => iNRAE

**Comment by syphax-bouazzouni** [comment]
Any update on this ? @jonquet

**Comment by jonquet** [comment]
Addressed now, way more easy with recent fixes of agents.
Thanks to @toineau2007
