### ISSUE TITLE
Schema d'identifiant par défault préséléctioné en fonction de l'agent:

### ISSUE THREAD

**Issue by toineau2007** [agroportal/project-management#545]
Il faudrait que lorsque qu'on édite (ou crée) un nouvel agent, l'identifiant par default soit mis en fonction du type d'agent (personne = ORCID et organisation = ROR).
Dans le cas de personne ca fonctionne par défaut mais par pour les organisations.

<img width="1045" alt="Capture d’écran 2024-05-10 à 15 41 43" src="https://github.com/agroportal/project-management/assets/150827945/38cdceec-9e73-4844-8855-f6c5fb407827">

Antoine Jonquet

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/721
