### ISSUE TITLE
Q&A session - 21th of May (Anne Sophie, Sophie, Nina)

### ISSUE THREAD

**Issue by user34ngrau** [agroportal/project-management#546]
1- [submit ontology] : [affichage du bouton vert quand choisi une vue]
<img width="567" alt="image" src="https://github.com/agroportal/project-management/assets/135241416/a20ac9a9-b6f2-466a-9a16-b6383f04ed77">
<img width="567" alt="image" src="https://github.com/agroportal/project-management/assets/135241416/7ca4818b-2347-4788-bda1-526c41cf0aec">

2- [ontology summary page] : [format des dates différents de celui lors de la soumission]
<img width="686" alt="image" src="https://github.com/agroportal/project-management/assets/135241416/29092adf-907a-4f6d-ba6f-c84591620bd1">

3- [Parsing success message] : [Trouver une formulation plus explicite des paramètres décrits dans le message reçu apres Parsing]
Ex: Définir le mot "Parsing"
![image](https://github.com/agroportal/project-management/assets/135241416/ee7393ce-54e1-4d16-9d37-6dc0a7d7bb0f)

4- [Account information] : [Pas d'information sur le statut de l'user]
ex: ne voit pas si admin ou pas
<img width="1239" alt="image" src="https://github.com/agroportal/project-management/assets/135241416/73ae0cfe-af1e-4576-a75d-3b776954b33b">

5- [Page note d'une ontologie] : [message reçu par les administrateurs de l'ontologie ne contient pas toutes les informations envoyées dans la note]
Mail recu: 
![image](https://github.com/agroportal/project-management/assets/135241416/b9440d2c-421c-47ce-9aba-1aa8263aa6af)
Note envoyé
<img width="771" alt="image" src="https://github.com/agroportal/project-management/assets/135241416/19a5d2bd-65bc-436e-86f1-4ddd741c706d">

6- [Page note d'une ontologie] : [l'intitulé "raison du changement" disparait une fois le champs rempli et ne réapparait plus]
<img width="769" alt="image" src="https://github.com/agroportal/project-management/assets/135241416/ee9a79f2-3d76-458a-b855-367a0fac5557">

7- [homepage - section recommender et annotator] : [recherche annotator sur la homepage renvoi lui la page annotator sans avoir effectuer la rechercher et perd le texte rentré] ✅
<img width="1190" alt="image" src="https://github.com/agroportal/project-management/assets/135241416/ee27c161-0346-4942-96c6-fddc5c44c059">

8- [homepage] : [contact us onglet renvoi sur feedback page
<img width="386" alt="image" src="https://github.com/agroportal/project-management/assets/135241416/f6032640-d142-4a89-819a-9ef515b3717d">

9- [homepage en francais] : lien de bas de page vers termes & conditions doivent pointer vers les sections française du document
<img width="1109" alt="image" src="https://github.com/agroportal/project-management/assets/135241416/04951597-f891-4730-8b32-139e5c83b103">

10- [lien sur l'onglet "about us"] : [les contributeurs ne sont pas les meme que les personnes de la team + rendre le lien plus users friendly c'est à dire expliquant ce qu'est agroportal pour les non développeurs ou faire un lien spécial dévelopeur]
<img width="1274" alt="image" src="https://github.com/agroportal/project-management/assets/135241416/2b5ba9f4-c270-4f5a-bcd3-b8318646bb55">

**Comment by jonquet** [comment]
Je complète le (5) en disant que le lien envoyé vers la note dans l'email n'aboutit pas.

**Comment by syphax-bouazzouni** [comment]
Moved to issues 
* https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/899
* https://github.com/agroportal/project-management/issues/648
