### ISSUE TITLE
Le parametre language=all n'est pas activé dans l'appel tant que les langues ne sont pas explicitement specifiées dans la propriété naturalLanguage 

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#547]
Dans l'exemple: 
https://agroportal.lirmm.fr/ontologies/PPD-GV?p=classes
On voit que la selection de "All languages" dans l'UI nous fait passer a l'URL: 
https://agroportal.lirmm.fr/ontologies/PPD-GV?p=classes&language=all

Par contre, dans l'exemple: 
https://agroportal.lirmm.fr/ontologies/PPD-OLT?p=classes
qui n'a pas de langue specifié dans naturalLanguage encore
All languages est selectionné dasn l'UI mais cela n'est pas ce que l'UI affiche.
Si on ajoute explicitement &language=all à l'URL
Cela done: https://agroportal.lirmm.fr/ontologies/PPD-OLT?p=classes&language=all
Est le contenu affiché change

**Comment by jonquet** [comment]
A noter aussi sur cette page... quand on active explictiement &language=all
https://agroportal.lirmm.fr/ontologies/PPD-OLT?p=classes&language=all

Alors l'affichage des altLabel et definiton dans Raw data disparait

<img width="562" alt="Capture d’écran 2024-05-22 à 17 13 40" src="https://github.com/agroportal/project-management/assets/7379183/b7898104-f03f-40e1-8bb9-b032f60c6269">

**Comment by jonquet** [comment]
Tjrs sur cette ontologie, semblerait que tout ne soit pas indexé.
Chercher dans le Jump to: "Makrostadium"
Trouve rien.. 
Meme si ce concept est la: 
https://agroportal.lirmm.fr/ontologies/PPD-OLT?p=classes&language=all&conceptid=https%3A%2F%2Fopendata.inrae.fr%2Fppd-res%2FoliveTree%23bbch_oliveTree_principalStage_BBCH0

**Comment by syphax-bouazzouni** [comment]
done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/729
