### ISSUE TITLE
La création d'une note sur une ontologie rend cette ontologie buggée dans l'UI

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#551]
Attention, on vient de reparer le système de notification à la cr"ation de notes. Super. 
Du coup je viens juste de l'utiliser pour LEXEAU et AGROVOC

Manque de chance: 
- L'email contient un lien corrompu vers la note. Il contient: E.g. https://agroportal.lirmm.fr/notes/https%3A%2F%2Fdata.agroportal.lirmm.fr%2F%2Fnotes%2F1f32d730-ff30-013c-2e2d-5254006dce65 au lieu de E.g. https://agroportal.lirmm.fr/notes/1f32d730-ff30-013c-2e2d-5254006dce65
- Le fait de créer une note rend la page bugée dans l'UI

**Comment by jonquet** [comment]
@Bilelkihal I have assigned you on this as this seems to be critical. Might be our first chance to testy hot-fixes with you ;)

**Comment by jonquet** [comment]
Bon en fait semblerait que ce bug ne soit pas associé a ca. 
On a eu une phase que j'explique pas à partir de 17h ... un vrai delire en terme de page 404... il y en avait preque partout mais pas de maniere consistente... 
Le triple sotre a planté, je l'ai redemarré... vider les caches... 
Ca disparu qu'au redemarage de la machine vers 18h15

**Comment by jonquet** [comment]
L'appliance log est plein de 

<img width="633" alt="Capture d’écran 2024-05-28 à 18 23 39" src="https://github.com/agroportal/project-management/assets/7379183/a9ffd5db-b0a5-42ac-b8bd-2421011bab6a">

**Comment by Bilelkihal** [comment]
This problem is related to the request "/ontologies/:ontology_acronym".
I've looked into the backend but didn't find any clear issues. It's confusing because sometimes it works and sometimes it doesn't. I'll keep investigating to figure out why this is happening.

**Comment by Bilelkihal** [comment]
Pour le problem de lien c'est fixé dans cette PR:
https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/138

**Comment by jonquet** [comment]
> This problem is related to the request "/ontologies/:ontology_acronym". I've looked into the backend but didn't find any clear issues. It's confusing because sometimes it works and sometimes it doesn't. I'll keep investigating to figure out why this is happening.

Exactly what I have experienced too. 
Maybe we should close this issue (if the link notification is addressed) and open another one to follow the "stability" aspect.
