### ISSUE TITLE
Améliorer l'ouverture d'un lien direct vers une note (recu par email) 

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#552]
Le lien recu dans l'email de notiifcation des notes est corrompu. 

E.g. https://agroportal.lirmm.fr/notes/https%3A%2F%2Fdata.agroportal.lirmm.fr%2F%2Fnotes%2F1f32d730-ff30-013c-2e2d-5254006dce65

au lieu de 
E.g. https://agroportal.lirmm.fr/notes/1f32d730-ff30-013c-2e2d-5254006dce65

En outre ce lien (lorsque corrigé) envoie veers une simple page qui n'est pas contextualisée: 
<img width="627" alt="Capture d’écran 2024-05-28 à 17 26 40" src="https://github.com/agroportal/project-management/assets/7379183/d953276f-3447-4bf0-91cb-15168b78bfe4">

Idealement, il faudrait que cela ouvre la page des notes de l'ontologie (ici https://agroportal.lirmm.fr/ontologies/LEXEAU?p=notes) et eventuellement un modal ou qq chose qui ouvre la note.

**Comment by jonquet** [comment]
Dans notre cas, la note qui nous interesse est la:
https://data.agroportal.lirmm.fr/ontologies/LEXEAU/notes?display=all

Il faudrait que l'UI utilise la valeur de relatedOntology pour "ramener" la note conxtextuellemnt dans LEXEAU

**Comment by syphax-bouazzouni** [comment]
Related https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/606

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/143 and https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/606
