### ISSUE TITLE
Format dans adminstration des métadonnées genere une page vide

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#556]
<img width="714" alt="Capture d’écran 2024-05-29 à 12 21 18" src="https://github.com/agroportal/project-management/assets/7379183/ecfa56df-bd84-4f30-9d0b-342dc3f721a9">

**Comment by jonquet** [comment]
"Location" genere la meme erreeur

**Comment by syphax-bouazzouni** [comment]
Duplicate of https://github.com/agroportal/project-management/issues/591
