### ISSUE TITLE
Le selecteur des ontologies, utilisé dans les relation d'ontologies devrait exclure soit meme 

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#557]
Dans la page d'edition de metadonnées > relations... le selecteur d'ontologies pourrait exclure l'ontologie sur laquelle on est... en gros qu'on ne puisse pas mettre "o R o" et que l'on boucle.

**Comment by Bilelkihal** [comment]
Fixed here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/640
