### ISSUE TITLE
Mettre les projets pour les 4 ontologies de Planteome

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#558]
<img width="354" alt="Capture d’écran 2024-05-29 à 13 05 13" src="https://github.com/agroportal/project-management/assets/7379183/b0072251-3dfe-45db-a838-fdd2bf9f94d2">

**Comment by syphax-bouazzouni** [comment]
Any update on this ? @jonquet

**Comment by jonquet** [comment]
Done. Multiple projects created, some updated. 
All assigned to PO, TO, PSO, PECO
