### ISSUE TITLE
"Jump to" search box in the property tab

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#56]
I would be interested by seeing a “Jump to” box at the top of the Property hierarchy in BioPortal UI.
Exactly has we have for classes.

An ontology that is perfect with properties is SIO:
http://bioportal.bioontology.org/ontologies/SIO/?p=properties

There are 208 properties there.
And all the ObjectProperty are in a clean hierarchy, in which it is cumbersome to search without a search box.

In addition, I think the best presentation here will be to have a search box on the top, and then a hierarchy displayed with 3 top level properties: owl:ObjectProperty, owl:AnnotationProperty and owl:DatatypeProperty

And, when a property is selected, then the right part should display the maximum number of things for the property (I mean, all the properties of the Property)… rdfs:label, sio:example, dc:description, sio:hasSynonym and all the classic ones subPropertyOf, range, etc. For the moment, only the rdfs:comment and rdfs:label are displayed.

Other examples of ontologies for which the search box feature will be useful includes all the ones with many properties and sometime some hierarchies:
https://bioportal.bioontology.org/ontologies/GEOSPECIES/?p=properties
https://bioportal.bioontology.org/ontologies/NCIT/?p=properties
https://bioportal.bioontology.org/ontologies/PHARE/?p=properties

**Comment by syphax-bouazzouni** [comment]
Interesting feature request (to add in our side notes for next contributions)

**Comment by jonquet** [comment]
Getting closer to be done. See StagePortal.

**Comment by syphax-bouazzouni** [comment]
Done https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/550
![image](https://github.com/agroportal/project-management/assets/29259906/4865376b-cf88-48b7-abac-76d816a25ba6)

**Comment by jonquet** [comment]
Congrats! always good to close feature request from 2016
