### ISSUE TITLE
Vider l'ensemble des ontologies dans son custom set genere un 404

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#565]
Pour reproduire. 
Prendre un utilisateur non admin. 
Ajouter des ontologies a son custom set. 
Visualiser que cela marche. 
Se deconnecter. 
(peut etre laisser du temps ou changer de navigateur)
Se reconnecter.
Vider son custom set et sauver. 
=> 404 sur l'URL https://agroportal.lirmm.fr/accounts/LOGIN/custom_ontologies

**Comment by jonquet** [comment]
Le fait de re-ouvrir la page montre un custom set qui n'est pas vidé (cache? )
Mais un appel API qui montre un array vide: https://data.agroportal.lirmm.fr/users/LOGIN?display=all

**Comment by syphax-bouazzouni** [comment]
@Bilelkihal does https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/685 include this ?

**Comment by syphax-bouazzouni** [comment]
> @Bilelkihal does [ontoportal-lirmm/bioportal_web_ui#685](https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/685) include this ?

@Bilelkihal I will assume yes
