### ISSUE TITLE
Subscriptions (Watch) does not work sometimes

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#567]
Login with a non admin user. 
Browse multiples ontologies and select a few to "Watch"
I have tried with FOODON, VT, GO, RO, EFO, AGROVOC

The button Watch is sometimes very long to "repsond" but its ok it changes... 
Unfortunlaty the watching did not worked. 

Go to https://data.agroportal.lirmm.fr/users/LOGIN?display=subscription to say what has work.

Go to https://agroportal.lirmm.fr/account to see what the UI show you (I think only the last)

**Comment by Bilelkihal** [comment]
Fixed here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/681
