### ISSUE TITLE
Create Agroportal ncbo_cron docker image  

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#568]
Currently, we are using the BioPortal version of the NCBO cron docker image, which is no longer compatible with our code. So we need to do as the API and UI create our docker image 

### TODO

- [x] Implement/enable the GitHub CI in the ncbo_cron repository to generate the image each time we release a version 
- [x] Update the ontoportal_docker repository to use it instead of the BioPortal version

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/ncbo_cron/commit/e15e2180a0908db94dab2f284845edc60dfdce78

- DockerHub: https://hub.docker.com/repository/docker/agroportal/ncbo_cron
- GitHub packages: https://github.com/ontoportal-lirmm/ncbo_cron/pkgs/container/ncbo_cron

**Comment by jonquet** [comment]
Super. Sur les Docks à la tombée du jour...
