### ISSUE TITLE
AgroPortal Docker 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#569]
Related to https://github.com/ontoportal/ontoportal-project/issues/7

### Goal 
Run an ontoportal instance using docker 

### Requirments 
- [x] Have a CI to build the API docker image on each release (https://github.com/ontoportal-lirmm/ontologies_api/pull/58)
- [x] Have a CI to build the UI docker image on each release (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/384)
- [x] Have a CI to build the CRON docker image on each release   (https://github.com/ontoportal-lirmm/ncbo_cron/commit/e15e2180a0908db94dab2f284845edc60dfdce78)
- [x] Have docker-compose to run the API (https://github.com/ontoportal-lirmm/ontologies_api/pull/59)
- [x] Have docker-compose to run the UI (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/384)
- [x] Have docker-compose to run the CRON (same as the API)
- [x] Have a script/CLI to fetch and run the docker-compose together, running an Ontoportal instance, in API mode or UI mode.  (https://github.com/ontoportal/ontoportal_docker/pull/7)
- [ ] Have a UI to bootstrap an ontoportal instance using Docker
![image](https://github.com/agroportal/project-management/assets/29259906/fecb4990-a739-4101-9eda-f89a38e11f4f)

**Comment by jonquet** [comment]
For this last point (UI) do you think about an independant small web app (ruby I assume) that would be deployed and stable somewhere and would be use to deploy Test/Stage/Agro ?

**Comment by imadbourouche** [comment]
> For this last point (UI) do you think about an independant small web app (ruby I assume) that would be deployed and stable somewhere and would be use to deploy Test/Stage/Agro ?

A small simple web app using html and js where we can host it on github pages and will be used to: 
- Choose docker version : BioPortal or AgroPortal (maybe will add Test/Stage/Master configuration)
- Select ontologies to import at start (example as we did for STY in our tests)
- Choose the mode run:  UI or API, or Both
- Deploy the instance using this interface

And behind the scene it calls the ontoportal script that will do all this

**Comment by syphax-bouazzouni** [comment]
Close this iteration here, will reopen a new issue for the followup.
