### ISSUE TITLE
Permettre de selcetioner les agents de type organization avec l'acronyme

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#571]
Il faudrait  permettre de selectionner les agents organisation avec l'acronyme, le nom et le ror dans le popup de slection. 

<img width="641" alt="Capture d’écran 2024-06-09 à 18 13 21" src="https://github.com/agroportal/project-management/assets/7379183/16aa158c-d24b-47e2-bf81-a476e834af6b">

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/703
