### ISSUE TITLE
Remettre la verison OBO de Multicrop CO_020

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#576]
https://github.com/bioversity/multi-crop-passport-descriptor-ontology/blob/main/FAO-IPGRI_Multi-Crop_Passport_Descriptor.obo

Je sais pas trop comment on ets passé a un eversion OWL a un moment .. et elle ne se parse pas/plus ? 

Voir pourquoi la version OWL ne parse pas.

**Comment by jonquet** [comment]
J'ai remis la verison OBO qui sur GitHub datait de aout 2021... plus recente que celle qu'on avait en OWL. 
Par contre la vrison OWL (voir soumission 4)  ne se parse plus de notre coté tandis qu'elle se parait dans le passé et continue a se parser sur mon Protégé (5.6.1) avec

**Comment by jonquet** [comment]
La version OBO ne semble pas se parser non plus... a regarder.

**Comment by syphax-bouazzouni** [comment]
Semble etre bon maintenant a re-ouvrir @jonquet sinon.
![image](https://github.com/agroportal/project-management/assets/29259906/ab18b00f-7695-4a18-91ef-63e56135b3e4)
