### ISSUE TITLE
Q/A 2.8.1

### ISSUE THREAD

**Issue by user34ngrau** [agroportal/project-management#578]
### Issues

- 5 metadata extraction

JSON download in .nt format
<img width="702" alt="image" src="https://github.com/agroportal/project-management/assets/135241416/320c2748-6ba4-45dd-b944-c658a5d28f82">

- new login with GitHub  
not working - error 404
<img width="852" alt="image" src="https://github.com/agroportal/project-management/assets/135241416/f7743637-4747-4234-b2f9-bc52686d2061">

- login with google 
working but error 404

- new bis search ontology
when look at an ontology in the search bar and I press enter, I don't like the result > option : when enter into the search bar, give me the first term provided
<img width="852" alt="image" src="https://github.com/agroportal/project-management/assets/135241416/3cd3db44-7a3c-461f-b067-b9c0c4e94b3a">

![image](https://github.com/agroportal/project-management/assets/135241416/a53a0fbc-0ef6-47ad-a6c2-64f6f91e7765)

- new bis bis notification epileptic bug on safari
![image](https://github.com/agroportal/project-management/assets/135241416/96d0003c-c666-45e1-b045-9bbd0d43ab1b)

**Comment by Bilelkihal** [comment]
I can reproduce 'new bis bis notification epileptic bug on safari' on my machine,
@syphax-bouazzouni can you try this, open this link on your safari:
https://stageportal.lirmm.fr/ontologies/AGRO

**Comment by syphax-bouazzouni** [comment]
Fixed for most of them.
