### ISSUE TITLE
Federate search 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [agroportal/project-management#593]
### Requirements 
- Have a selector to choose on which portals to run the search 
![image](https://github.com/user-attachments/assets/36d75b61-48eb-430b-8b0a-f8cd3cdc1dba)

- Display the results in the appropriate order 

- Customize the UI to display the result according to the result portal origin 
![image](https://github.com/user-attachments/assets/c5b07f0f-64f3-4576-bc9c-a05439c7f31e)

**Comment by jonquet** [comment]
From notes of the Rome Federation meeting: 

- [x] Assure the local search parameter will be transferred to the other portals (except the ontology list).
- [x] Enable an advance selection of ontologies from other portals with the ontology selector (showing filters based on the other portal)
- [x] Manage duplicate results (i.e., coming from duplicate ontologies)

And concernig the ranking
- First version should be basic e.g., 3 first results from local portal, then 3 from other portal (in alphabetical order, or preferred order if list of federated portal is ordered), then 3 more and etc. 
- Then we will need to think more advance ranking that would merge the results from each portals into one unique search resultset. We may need to change the backend to add some kind of normalized score to the search results.

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/739

**Comment by jonquet** [comment]
Ticked all.
Although ranking has been implemented differently.
