### ISSUE TITLE
FAIR score is 0 for all ontologies in "Browse" page

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#595]
**Describe the bug**
FAIR score is set to 0 for all ontologies in "Browse" page. Yet, visiting the ontologies or the landscape, one can see the FAIR score for selected ontology

**To Reproduce**
1. Go to https://agroportal.lirmm.fr/ontologies 
2. See error : FAIR score is 0 for all ontologies

**Expected behavior**
See the FAIR score of the ontologies in the Browse page

**Screenshots**
![image](https://github.com/user-attachments/assets/7b0edb13-76fd-4446-989e-03bf4c06b2a8)

**Comment by jonquet** [comment]
Il faudrait qu'on ne mette pas les resultats de O'FAIRe dans le cache de la page Browse si on voit que ces resultats sont que zero et donc que O'FAIRe est down a ce moment la. 
Sinon ce cache reste 24h.

**Comment by syphax-bouazzouni** [comment]
fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/745
