### ISSUE TITLE
Cookie banner consent message

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#597]
After discussion and incorporation of the cookie banner consent, this is the proposed message: 
English: 
"AgroPortal uses cookies to help you navigate efficiently and for audience measurement. You will find detailed information about all cookies in the "Privacy policy" link.

The cookies are functional and non-optional. By staying on AgroPortal, you acknowledge the information was delivered to you." 

French: 
"AgroPortal utilise des cookies pour vous aider à naviguer efficacement et pour mesurer l'audience. Vous trouverez des informations détaillées sur tous les cookies dans le lien "Vie privé".

Les cookies sont fonctionnels et non facultatifs. En restant sur AgroPortal, vous reconnaissez que les informations vous ont été transmises."

- [ ] Mettre le bon lien pour chaque langue (EN et FR) sur la page des CG
- [ ] Enlever le bouton deny et centrer le bouton accept.

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/732

>  Mettre le bon lien pour chaque langue (EN et FR) sur la page des CG

It can't be done, as we can not generalize it to any language.
