### ISSUE TITLE
Q&A agents

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#598]
Qq commentaires et améliorations sur les agents avec les changement de la release v2.9.1

- [ ] 1 - Lors qu'on ouvre un agent dans la page d'edition, avec le bouton "stylo" le seul moyen de fermer le formulaire ouvert est de faire "Save" et donc de renvoyer un message au serveur meme si on a rien changé/édité. L'amélioration consisterait a mettre un bouton "Close" a coté de Save pour fermer le formulaire, sans re-soliciter le serveur. C'est d'apre smoi ce qui créera le moins de conflit avec les autres occurences de cette UI e.g. à partir de la page admin (en modal). 
Dans la page edition 
<img width="442" alt="Capture d’écran 2024-08-05 à 15 47 31" src="https://github.com/user-attachments/assets/9069f67e-b48a-4ddc-98d8-a23f5b994570">
Dans la page admin 
<img width="753" alt="Capture d’écran 2024-08-05 à 16 11 11" src="https://github.com/user-attachments/assets/825242f8-956b-471b-b3c6-4ac002d62511">

- [x] 2 - L'identifier ne se charge pas dans le formulaire dans l'UI quand il existe dans le back. Discuté ce matin. Exemple sur INRAE (https://data.stageportal.lirmm.fr/Agents/78b794c0-3017-013c-5eb0-5254007cab39) sur Stage
<img width="417" alt="Capture d’écran 2024-08-05 à 15 50 46" src="https://github.com/user-attachments/assets/aabb38f3-5ca2-4790-86de-fc55ecbe0476">

- [x] 3 - Maintenant qu'on a "re-inforce" l'usage des ORCID et des ROR ... ceux-ci étant des identifiants, en théorie il faudrait que quand on édite un agent on ne puisse pas ajouter d'autres identifiants (au moins via l'UI). Dans le back, on peut rien changer car on a le paramêtre "schemaAgency" qui permet de distinguer les identifiants. 
<img width="474" alt="Capture d’écran 2024-08-05 à 15 54 43" src="https://github.com/user-attachments/assets/35f6e86d-aa30-453b-9fe1-3d0a4e8b6db3">
Side effect: cela va alléger l'UI aussi quand on édite un agent. 

- [x]  4 - Suis pas sur de l'état de cela sur StagePortal actuellement, mais pour le moment je peux saisir un ORCID pour un agent qui soit n'importe quoi. Avec la discussion sur les expressions régulières etc, ca surprends quand meme que le front check pas un minimum avant s'aller enregistrer ca dans la base. 
<img width="763" alt="Capture d’écran 2024-08-05 à 15 58 19" src="https://github.com/user-attachments/assets/64967685-f489-41f9-b8f9-3ff1bd295e47">

A y re-reflechir, j'aurai peut etre juste enlever du code les expressions régulieres de flexibilité (i.e. qui essayent de trouver la sequence de l'ORCID dans ce qui est mis dans le champ) et remplacer ca par un simple ORCID validator regular expression (unique) qui vérifie que le champ respecte ca et alerte (avant meme de clicker sur save) sur le fait que ce champ n'est pas valide. 
En théorie, j'aurai vu ca comme un composant texte (dans le lookbook) qui passe en rouge tant que le texte dedans ne respecte pas une expression réguliere donnée. Pas plus. On a se composant à disposition dans l'UI et à chaque fois qu'on veut faire un check front.. on peut l'utilsier. E.g., piru l'ORCID cela peut etre le meme sur la page d'édition d'un utilisateur.  On devrait en fait avoir un sous type de Input::TextInputComponent dans le lookbook avec comme attributs de plus: un mini icon qu'on met a a gauche du texte et une expression régulier de validation.

- [ ] 5 - La requête https://data.stageportal.lirmm.fr/search/agents?query=INRAE nous renvoie en 4eme position l'INIST qui dans sa description ne contient pas du tout la chaine de caractère "INRAE"...  ni la sous chaine "INRA". Pourtant les 5eme à 8 eme positon contienne cette sous chaine mais sont classés après. 

- [ ] 6 - Dans la recherche: https://data.stageportal.lirmm.fr/search/agents?query=INRAE => Les id, resource_id et creator_t sont préfixées avec le mauvais name space (bioontology.org).

- [ ] 7 - Dans la recherche d'agents via le nouveau endpoint "spécialisé" pourquoi les propriétés JSON ne sont pas les memes que pour les agents eux memes ? En fait par extension, les resultats des "nouveaux" endoints devraient être similaire a ceux du /search endpoint.. entre autre utiliser une description JSON-LD de ce qu'ils renvoient. Par exemple, pour ce resultat: https://data.stageportal.lirmm.fr/search/agents?query=jonquet
<img width="422" alt="Capture d’écran 2024-08-05 à 16 28 44" src="https://github.com/user-attachments/assets/4d002a44-a5d1-43af-999e-66e8e60308ac">

Il s'agirait de renvoyer une collection avec comme elements, une version plus light de la description JSON-LD d'un agent: 
<img width="545" alt="Capture d’écran 2024-08-05 à 16 30 17" src="https://github.com/user-attachments/assets/e65f2a73-846e-4dea-8d9e-8777f2fa6c15">

- [ ] 8 - Similairement à l'appel "https://data.stageportal.lirmm.fr/search" qui renvoie une erreur pour dire comment utiliser cet endpoint, le nouveau endpoint https://data.stageportal.lirmm.fr/search/agents lui aurait pu renvoyer le meme type d'erreur plutot que de basculer sur une recherche "complète" => a voir si cela ne va rien cassé dans le menu appellant cet endpoint. 
<img width="593" alt="Capture d’écran 2024-08-05 à 16 26 24" src="https://github.com/user-attachments/assets/aa909050-a085-4a25-99f1-9a628daf2eef">

- [ ] 9 - Une chance qu'on puisse faire aussi : https://github.com/agroportal/project-management/issues/544 ? cela permettrait de fermer tous les issues ouvertes sur les agent sil me semble: https://github.com/agroportal/project-management/issues/523

- [ ] 10 - Dans un soucis d'harmonisation des UI, la table des agents dans la page admin pourrez utiliser l'icone de poubelle dans la colonne Actions pluot que le mot "delete". Egalement, de la place a droite de "Delete" peut etre recuprée (espace vide) pour le repartir dans d'autres colonnes.

- [ ] 11 - Le classement par la colonne "Usages" de la table des agents dans la page admin ne fonctionne pas. 

- [ ] 12 - La colonne "Identifiers" de la table des agents dans la page admin pourrait juste afficher le logo ORCID ou ROR quand un identifiant est la et faire en sorte que ce lien soit clikcable vers l'extérieur. Cela économiserait pas mal de largeur dans cette table et permettrait de rendre la colonne name plus large (acronym aussi un peu car pour le moment le triangle de tri par cette colonne apparait au dessus du m).

- [ ] 13 - La colonne "First name" de la table des agents dans la page admin doit être renommée "Name"

- [x] 14 - Le bouton d'affichage des organizations devrait s'appuyer sur l'acronyme plutôt que le name de l'agent. Cela permettrait le plus souvent d'éviter les 3 points de suspensions (mettre un fallback si pas d'acronyme alors utiliser le name).
<img width="298" alt="Capture d’écran 2024-08-05 à 16 54 00" src="https://github.com/user-attachments/assets/c6398045-84ba-46c6-8f6d-323aa340599b">

- [x] 15 - Le tooltip d'affichage des organizations devrait afficher l'acronyme quand présent à la fin de la chaine de caractère du nom en utilsiant des parenthèses. Ici: '... Environment (INRAE)"
<img width="623" alt="Capture d’écran 2024-08-05 à 16 50 20" src="https://github.com/user-attachments/assets/4698ecd6-bf76-47fd-bfff-a02874a61e1e">

- [x] 16 - Dans le tooltip d'affichage des agents (pas celui des contacts) il ne faut pas afficher l'email. Nous avions vu que comme c'est une information personnelle, on ne l'affiche pas. En plus, ce tooltip utilise 3 lignes, et l'email qui arrive avant l'organization de l'agent empêche de voir l'organization. 
<img width="388" alt="Capture d’écran 2024-08-05 à 16 59 47" src="https://github.com/user-attachments/assets/0a270d5a-03e2-4cd6-ba51-6c4058c7b9f3">

- [ ] 17 - Bug de changement de type: Sur StagePortal, dans l'edition d'une ontologie, sélectionner "Clément Jonquet" dans un champ agent. Ensuite, ajouter l'affiliation "MISTEA" a Clement en l'éditant.... voir que MISTEA n'est pas de bon type (person au lieu de organisation) alors éditer l'agent MISTEA a l'interieur du formulaire de l'edition de l'agent Clement pour changer son type vers "organisation" => cela ferme le 2eme formulaire et affecte le type "organisation" a Clement au lieu de l'affecter a MISTEA

**Comment by syphax-bouazzouni** [comment]
Moved to issues 

> 1 - Lors qu'on ouvre un agent dans la page d'edition, avec le bouton "stylo" le seul moyen de fermer le formulaire ouvert est de faire "Save" et donc de renvoyer un message au serveur meme si on a rien changé/édité. L'amélioration consisterait a mettre un bouton "Close" a coté de Save pour fermer le formulaire, sans re-soliciter le serveur. C'est d'apre smoi ce qui créera le moins de conflit avec les autres occurences de cette UI e.g. à partir de la page admin (en modal).

=>https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/896

> 17 - Bug de changement de type: Sur StagePortal, dans l'edition d'une ontologie, sélectionner "Clément Jonquet" dans un champ agent. Ensuite, ajouter l'affiliation "MISTEA" a Clement en l'éditant.... voir que MISTEA n'est pas de bon type (person au lieu de organisation) alors éditer l'agent MISTEA a l'interieur du formulaire de l'edition de l'agent Clement pour changer son type vers "organisation" => cela ferme le 2eme formulaire et affecte le type "organisation" a Clement au lieu de l'affecter a MISTEA

=> https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/897

> 5 - La requête https://data.stageportal.lirmm.fr/search/agents?query=INRAE nous renvoie en 4eme position l'INIST qui dans sa description ne contient pas du tout la chaine de caractère "INRAE"... ni la sous chaine "INRA". Pourtant les 5eme à 8 eme positon contienne cette sous chaine mais sont classés après.

> 6 - Dans la recherche: https://data.stageportal.lirmm.fr/search/agents?query=INRAE => Les id, resource_id et creator_t sont préfixées avec le mauvais name space (bioontology.org).

> 7 - Dans la recherche d'agents via le nouveau endpoint "spécialisé" pourquoi les propriétés JSON ne sont pas les memes que pour les agents eux memes ? En fait par extension, les resultats des "nouveaux" endoints devraient être similaire a ceux du /search endpoint.. entre autre utiliser une description JSON-LD de ce qu'ils renvoient. Par exemple, pour ce resultat: https://data.stageportal.lirmm.fr/search/agents?query=jonquet

=> https://github.com/agroportal/project-management/issues/647

>  10 - Dans un soucis d'harmonisation des UI, la table des agents dans la page admin pourrez utiliser l'icone de poubelle dans la colonne Actions pluot que le mot "delete". Egalement, de la place a droite de "Delete" peut etre recuprée (espace vide) pour le repartir dans d'autres colonnes.

> 11 - Le classement par la colonne "Usages" de la table des agents dans la page admin ne fonctionne pas.

> 12 - La colonne "Identifiers" de la table des agents dans la page admin pourrait juste afficher le logo ORCID ou ROR quand un identifiant est la et faire en sorte que ce lien soit clikcable vers l'extérieur. Cela économiserait pas mal de largeur dans cette table et permettrait de rendre la colonne name plus large (acronym aussi un peu car pour le moment le triangle de tri par cette colonne apparait au dessus du m).
> 13 - La colonne "First name" de la table des agents dans la page admin doit être renommée "Name"

=> https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/898
