### ISSUE TITLE
Naviguer les ontologies au format OWL genere une erreur si slash dans l'URL

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#600]
**Describe the bug**
Naviguer les ontologies au format OWL genere une erreur 

**To Reproduce**
Got to https://agroportal.lirmm.fr/ontologies/?format=OWL

**Expected behavior**
L'URL generée par notre page est https://agroportal.lirmm.fr/ontologies?format=OWL
Sans le slash. Donc on est plutot bon ...

**Additional context**
Je ne sais pas trop comment le slash peut apparaitre dans l'URL mais si c'est le cas le bug arrive. 

**Screenshots**
<img width="441" alt="Capture d’écran 2024-09-04 à 16 51 29" src="https://github.com/user-attachments/assets/1fbafcec-e6e4-40dc-92ca-1327f5a0c583">

**Comment by syphax-bouazzouni** [comment]
fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/745
