### ISSUE TITLE
Q&A Page Federated Browse

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#601]
Issues rapportées pas Clement: 

Issues aussi appropriées pour la page Search (#602)
- [x] Ce serait bien de tester si les portails fédérés répondent par un simple oing tres rapide avant de décider d'afficher ou d'activer l'icone du portail en question. Cela permettrait de ne pas activer un portail qui est à ce moment la en erreur. 

- [x] EcoPortal down => la pge Browse ne se charge jamais et reste bloquée tant qu'on ne déactive pas et redemande. 

- [x] Quand on active un portail de plus en sélectionnant le bouton, cela recupère la liste des ontologies, mais cela fait disparaitre la liste actuelle le temps que la nouvelle arrive... on serait moins sensible (en particulier pour les 20s de BioPortal) si on pouvait garder la page web affichée tant que l'autre n'est pas la => pas lié à la fédération visiblement d'apres @Bilelkihal ce serait récent comme problème

**Comment by Bilelkihal** [comment]
- [x] Clicking on a federation result ontology open it in a link with multiple slashes:
<img width="1073" alt="image" src="https://github.com/user-attachments/assets/053e7951-ee9a-43d6-977e-7b1054b4d29b">

**Comment by user34ngrau** [comment]
Q&A session - 20th of September (Nina, Sophie & Anne Sophie)
Template of the answers : Number - [Title of the issue] : [Description of the issue] followed by an example : text and/ or screenshot and/or recording

- [x] 1- [Place of the Portal's icons] : [Place of the Portal's icons is disorganized when there is more than one Portal on display]
<img width="777" alt="image" src="https://github.com/user-attachments/assets/438cb1f8-b65b-4677-ba2b-df457dcc3248">

- [x] 2- [Color of the Portal's icons] : [The color of the Portal's icon didn't correspond to the Portal's color]
<img width="777" alt="image" src="https://github.com/user-attachments/assets/9a60fda2-14f2-4e1c-8e21-ab5798ba8cdd">

- [x] 3- [Color of the Ontology] : [How the color is made the choice of the ontology coloration when the ontology is found into 2 portals?]
e.g. For BIPOM or BIPON. Moreovoer, how is made the choice for the other features like the Year. Is it the year of creation, year of submission in Portal1 or Portal 2?
<img width="858" alt="image" src="https://github.com/user-attachments/assets/5b1e6a32-8eca-42bc-a76a-40cf97ac5ac7">

- [x] 4- [Results ranking] : [The classification and ranking of the results are to complexe to be understandable intuitively]
- Sophie's comment: ordre alphabétique du nom des portails ? pas forcément pertinent → passer tout en gris et utiliser les couleurs juste sur les icones de portail ?. Sinon, je me souviens qu’on avait parlé de portails “master” (je ne sais plus le nom, vs. miroir). Si ça existe vraiment, ça pourrait permettre de décider de la couleur de l’onto.  Sinon, on pourrait choisir la couleur du portail qui présente l’ontologie avec la date de mise à jour  la plus fraîche ?

**Comment by jonquet** [comment]
Sophie's last point (numero 4) mélanger plusieurs aspects (ordre des icones, couleur des icones, portail master) etc.. tout cela a été discuté et est géré désormais.

**Comment by syphax-bouazzouni** [comment]
Seems all feedbacks are done
