### ISSUE TITLE
Q&A Page Federated Search

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#602]
- [x]  Discussion avec @Bilelkihal sur l'affichage des boutons que si la page d'accueil de l'API répond, de facon à ne pas sélectionner un portail qui serait non fonctionne à ce moment la.

- [x] Gestion du time out avec message indiquant qu'un des portails (indiquez lequel) est en erreur. Temps de time out a affiner en fonction du benchmark.

**Comment by user34ngrau** [comment]
Q&A session - 20th of September (Nina, Sophie & Anne Sophie)
Template of the answers : Number - [Title of the issue] : [Description of the issue] followed by an example : text and/ or screenshot and/or recording

- [x] 1- [Coloration of the Icon of the link transferring to the portal] : [The coloration of the icon of the Link that you have to click to go to the ontology isn't corresponding to the color of the portal] 

e.g; "Arbre "is found in AgroPortal (green) and BioPortal (blue) , however the icon of the link that transferring to bioportal is green and not blue)
<img width="1177" alt="image" src="https://github.com/user-attachments/assets/1d01a4a1-1278-4a85-8f3c-5ad573a8ee9c"> ✅

- [x] 2- ["Hand" icon on portal icon] : [A "hand" icon is appearing when the mouse pass over the portal icon but when you click on the portal icon nothing happen] 
![SearchFede_Mouse](https://github.com/user-attachments/assets/865b98ff-8fdb-486c-942b-8c32d49e4782) ✅

- [x] 3- [Result ranking - heterogenous] : [Difficulties to understand the ranking of the results] 
e.g. Search: measurement, in all Portals, and results aren't sorted by Portals. BioPortal, then IndustryPortal, then BioPortal
- Sophie's comment :
1. "Est ce que cest d’abord les exact match (portail par portail) puis un truc comme distance de levenstein croissante? " 
2. Notion “exact match“ : la notion n’est pas claire. Pour moi, “exact” veut dire je cherche “food” je veux que “food” comme résultat. Ni “foods”, ni “food processing”. Il faudrait peut-ête plus d’option : exact (par défaut?), contient, débute par, finit par (cf vocbench)
- All's comment: agreed that the results ranking is too complex to understand at the first glance ("même sans le federated c’est vrai, là ça devient critique") :  
1. Il faudrait des options de tri, de filtre
- filtre : juste les exact match 
- filtre : contient la chaine recherchée
- trier par correspondance avec la chaine recherchée
- trier par portail
- trier par ontologie
3. Il faudrait présenter les résultats autrement
- le terme qui matche (food)
- les ontologies dans où on le trouve (atol, agrovoc…)
- les portails où on trouve les ces ontologies (agro, bio…) : cliquable : on tombe sur la classe dans la bonne ontologie sur le portail choisi

- [x]  4- [Result sorted icons - heterogenous] : [Need a normalisation of the apparition of the icon affiliated to a results] 
e.g. 1st- Portal, 2nd-Details, 3-Visualise, 4-Mapping etc...
- dans le portail local : Détails, Visualisater, Mappings
<img width="1278" alt="image" src="https://github.com/user-attachments/assets/d23bc427-1a6e-44ed-839a-8eb939bb20a8">
-dans la fédération : icone des portails + parfois “X de plus de cette ontologie”
et parfois un texte = une définition (dans plusieurs langue (!) dans GEMET par exemple)
<img width="891" alt="image" src="https://github.com/user-attachments/assets/bc163955-f08a-4067-aed1-75b869187825">

- [x] 5- [Search Portal intersection] : [Would be nice to find a result into 2 portals] 

- [x] 6- [Absence Terms] : [Sentence of the result mentioned Portals that doesn't contain the term] 
e.g. Search: Arbre; Language French; Results : "Match in 4 Ontologies from Portal1, Portal2, Portal3", however, results indicate that not results have been found in Portal2 and Portal3. Would be better if the results sentence mentioned that terms match with the Portal where the term is found
<img width="1216" alt="image" src="https://github.com/user-attachments/assets/b3d7ca6b-9e41-4009-a274-1e845cc6e492">

- [x] 7- [Search options] : [Icon for search option isn't enough visible] 
e.g. Representation of the Option with "square bracket" isnt clear / The localisation of the "Options" would be under the search bar and not at the right
![image](https://github.com/user-attachments/assets/95347cba-e60d-4346-85b0-598cd5f1825d)
- All's comment: Revoir la disposition des options et taille des champs
1. la boite langue est trop longue
2. on dirait que “correspondance exacte”... s’appliquent au choix des ontologies (jaune)
4. Classes obsolètes et Classes avec définitions devraient être à côté l’un de l’autre.
<img width="891" alt="image" src="https://github.com/user-attachments/assets/09a505ef-6d41-4552-a915-6780014ab4b0">

- [x] 8- [Instant search] : [Results appears immediately after clicking on an search option, like for browse] 
e.g. Click on AgroPortal then results start to appears , and then can select another Portal...

**Comment by Bilelkihal** [comment]
- [x] Using ontologies selector and activating federation in the same time throw an error,

**Expected behavior**
- Short term: Don't pass selected ontologies in the federated call (keep it only for the current portal)
- Later: Make the ontologies selector federated and pass ontologies for each portal separately.

**Comment by jonquet** [comment]
@user34ngrau Pourriez vous nous reformuler le 4

Le 2 et le 7 sont déplacés ici: https://github.com/agroportal/project-management/discussions/614 
C'est des feedbacks sur la page Search

8 est impossible et pas preferable d'un point de vue technique et performance.

**Comment by syphax-bouazzouni** [comment]
6 done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/870
