### ISSUE TITLE
Q&A: Federated categories

### ISSUE THREAD

**Issue by Bilelkihal** [agroportal/project-management#604]

**Comment by user34ngrau** [comment]
Q&A session - 20th of September (Nina, Sophie & Anne Sophie)
Template of the answers : Number - [Title of the issue] : [Description of the issue] followed by an example : text and/ or screenshot and/or recording

1 - [Category & group] : [Category & group]
-Comment: les filtre “catégorie” et “groupe” ne contiennent que les choix pour le portail local j’ai l’impression. Du coup, quand on clique sur un de ces filtre, tous les résultats des autres portails disparaissent. Est-ce qu’à terme, les catégories et les groupes des autres portails s’ajouteront à la liste ? (ça nécessite d’avoir harmonisé les catégories d’un portail à l’autre mais je comprends que c’est un objectif)

**Comment by syphax-bouazzouni** [comment]
Fixer avec la federation des categories
