### ISSUE TITLE
Upload Agrovoc mappings

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#61]
Caterina gave us an export of the Agrovoc mappings (cf. local file) in July 2016.
Once Agrovoc will be in, we need to put them in also.

Here are the provenance information: 

date: 2012
type de propriete: skos exact/close match qui les a fait - Ashan Morshed (no longer in fao)
contact: agrovoc@fao.org, aims@fao.org
process de generation: semi-automatic candidate extracted automatically + manual validation

ref: Caterina Caracciolo, Armando Stellato, Sachit Rajbahndari, Ahsan Morshed, Gudrun Johannsen, Yves Jaques and Johannes Keizer. Thesaurus maintenance, alignment and publication as linked data: the AGROVOC use case. International Journal of Metadata, Semantics and Ontologies, 2012, vol. 7, n. 1, pp. 65-75. [Journal article]

list of pubs on agrovoc: http://aims.fao.org/standards/agrovoc/publications

Exact Match:
Asfa: http://aims.fao.org/aos/asfa/c_6603
dbpedia: http://dbpedia.org/resource/
dewey: http://dewey.info/class/
eurovoc: http://eurovoc.europa.eu/
gemet: http://www.eionet.europa.eu/gemet/concept/
geonames : http://sws.geonames.org/878675/
geopol: http://www.fao.org/countryprofiles/geoinfo/geopolitical/resource/
lcsh: <http://id.loc.gov/authorities/sh90003079#concept
NAL: http://lod.nal.usda.gov/nalt/
RAMEAU: http://stitch.cs.vu.nl/vocabularies/rameau/ark:/12148/
STW : http://zbw.eu/stw/descriptor/
The SOZ: http://lod.gesis.org/thesoz/concept/q
SWD: http://d-nb.info/gnd/
CAT: http://www.caas.net.cn/caas/cat/
Deutch National Bibliothek: http://d-nb.info/gnd/
Earth:  http://linkeddata.ge.imati.cnr.it:2020/resource/EARTh/62830

Close Match
asfa:  http://aims.fao.org/aos/asfa/c_6603
biotech: http://aims.fao.org/aos/biotechglossary/
dbpedia: http://dbpedia.org/resource/
dewey: http://dewey.info/class/
nalt: http://lod.nal.usda.gov/nalt/
dnb: http://d-nb.info/gnd/

**Comment by syphax-bouazzouni** [comment]
@jonquet Maybe outdated and can be closed?

**Comment by syphax-bouazzouni** [comment]
> @jonquet Maybe outdated and can be closed?

I assume it is outdated, please re-open if that is not the case @jonquet

**Comment by jonquet** [comment]
File provided by FAO is here in our local GDrive: https://drive.google.com/drive/u/0/folders/1_lLpzClBU9KWPjMvp8Ryig_2F7kPI2yF

After verification, these mappings seems to now be included in the distribution of AGROVOC we expose in AgroPortal. Some mappings then display in the UI. 

I shall just be sure that all the targets listed above do have a least a couple of mappings inside the repo and than the metadtaa (isAlignedto) is right. 

Will re-close the issue then.

**Comment by jonquet** [comment]
Those are the target for which I have expliclitly found mappings:
 
- [x] Asfa: http://aims.fao.org/aos/asfa/c_6603
- [x] dbpedia: http://dbpedia.org/resource/
- [x] eurovoc: http://eurovoc.europa.eu/
- [x] gemet: http://www.eionet.europa.eu/gemet/concept/
- [x] geonames : http://sws.geonames.org/878675/
- [x] lcsh: <http://id.loc.gov/authorities/sh90003079#concept
- [x] NAL: http://lod.nal.usda.gov/nalt/
- [x] STW : http://zbw.eu/stw/descriptor/
- [x] The SOZ: http://lod.gesis.org/thesoz/concept/q
- [x] Deutch National Bibliothek: http://d-nb.info/gnd/

Will update now the "isalinedTo" metadata property

**Comment by jonquet** [comment]
Done. Closing the issue now :)
Another one from Oct. 2016!
