### ISSUE TITLE
Q&A Prerelease 3.0

### ISSUE THREAD

**Issue by Bilelkihal** [agroportal/project-management#619]

**Comment by saubin78** [comment]
Fixed here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/783  ✅
> Page d'accueil --> Soumettre une ontologie (https://stageportal.lirmm.fr/ontologies/new) --> erreur 404

**Comment by saubin78** [comment]
Fixed here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/782 ✅
> sur une page d'ontologie / Concepts : fonctionnalité "Jump to/Aller à" ne fonctionne pas: recherche ne donne jamais de résultat
> ![image](https://github.com/user-attachments/assets/3b4d8682-ec60-4190-a8ef-33f5e2f81491)
> Dans https://stageportal.lirmm.fr/ontologies/BIODIVTHES2 il existe un concept "espèce envahissante" qui devrait être proposé
> https://stageportal.lirmm.fr/ontologies/BIODIVTHES2
> Même test, même résultat avec Agrovoc.

**Comment by saubin78** [comment]
Durée excessive pour déplier une branche de la hiérarchie pour https://stageportal.lirmm.fr/ontologies/AGROVOC
par ex, plusieurs secondes pour déplier une branche avec seulement 4 enfants
![image](https://github.com/user-attachments/assets/c493a3ff-2360-4dd5-98c6-65fc9ebf6418)

Je ne remarque pas trop ça sur d'autres vocabulaires

**Comment by jonquet** [comment]
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/760 See final comment.
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/774 See final comment.
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/784 See final comment.
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/754 See final comment.
- [x] https://github.com/ontoportal-lirmm/ontologies_api/pull/95 See final comment.



- [x] - Browse page does not show MILKOLIGOTH which is private and a view here https://stageportal.lirmm.fr/ontologies?search=milk&private_only=true&show_views=true
- [x] - Advanced Ontology selector still has the sentence weird  before the list of ontlogies "missing interpolation argument :portals ..."
- [x] - https://stageportal.lirmm.fr/ontologies/INRAETHES/?p=collections has an error

**Comment by syphax-bouazzouni** [comment]
### Important
- [ ] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/788
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/819
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/818
- [ ] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/809
- [ ] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/808
- [ ] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/807
- [ ] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/805
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/804
- [ ] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/803
- [ ] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/801
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/799
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/796
- [ ] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/787
- [ ] https://github.com/agroportal/project-management/issues/626

### Not important

- [ ] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/816
- [ ] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/815
- [ ] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/814
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/812
- [ ] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/811
- [ ] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/810
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/806
- [x] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/802
- [ ] https://github.com/agroportal/project-management/issues/625
- [ ] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/800
- [ ] https://github.com/agroportal/project-management/issues/624
- [ ] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/792
- [ ] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/789
- [ ] https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/785

**Comment by syphax-bouazzouni** [comment]
> - Browse page does not show MILKOLIGOTH which is private and a view here https://stageportal.lirmm.fr/ontologies?search=milk&private_only=true&show_views=true

@jonquet I think MILKOLIGOTH is not private? 
![image](https://github.com/user-attachments/assets/e298a7ab-9918-4046-868f-1c20ae3b7f6f)

**Comment by jonquet** [comment]
> > * Browse page does not show MILKOLIGOTH which is private and a view here https://stageportal.lirmm.fr/ontologies?search=milk&private_only=true&show_views=true
> 
> @jonquet I think MILKOLIGOTH is not private? 
En effet, erreur de mon côté. On est bon. Je supprime le commentaire

**Comment by syphax-bouazzouni** [comment]
Close as moved  to issues
