### ISSUE TITLE
Issue while displaying a deep hierarchy (NCBITAXON)

### ISSUE THREAD

**Issue by naouelkaram** [agroportal/project-management#632]
When trying to display the class "Musa" in the NCBI Taxonomy, the name is displayed on multiple lines. 
![grafik](https://github.com/user-attachments/assets/00b53004-d0e7-4084-b754-b711b69f8778)

Enlarging the hierarchy display does not work:
![grafik](https://github.com/user-attachments/assets/98afec8a-d4b9-470d-87df-f881c283f2d4)

Browser used: Firefox

**Comment by jonquet** [comment]
Oui c'est pas terrible. Faut qu'on regarde une optimisation graphique avec @Bilelkihal

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/855 and deployed in stageportal for now,

**Comment by Bilelkihal** [comment]
> Fixed in [ontoportal-lirmm/bioportal_web_ui#855](https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/855) and deployed in stageportal for now,

We don't have NCBITAXON ontology on stage, so we can't really see the fix
