### ISSUE TITLE
Export mappings from original ontology file when defined as "Mappings" in our model

### ISSUE THREAD

**Issue by saubin78** [agroportal/project-management#66]
Mon ontologie contient nativement des mappings skos. Ces mappings apparaissent bien sur la page des concepts concernés de mon ontologie mais pas dans l'onglet "Mappings" (sans doute réservé aux mappings calculés par AgroPortal).
Proposition :  inclure les mappings déclarés dans mon ontologies à l'onglet "Mappings" avec un statut particulier peut-être.

Sujet (pas super sexy) pour un hackathon?

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/agroportal/project-management/issues/302
