### ISSUE TITLE
Upload the AgroLD vocab to AgroPortal ontologies mappings

### ISSUE THREAD

**Issue by jonquet** [agroportal/project-management#94]
Bon voila les cght :

-	[] pour relation
-	J’ai inversé les classes car tu avais mis les sources (dans AgroPortal) en 2eme et précédé avec ext tandis que c’était les destination (dans AgroLD) qu’il fallait en 2eme et avec ext
-	On a pas OBI pour le moment donc 2 mappings vont foirer…*
-	J’ai changé les nom de propriétés court en URI AgroLD pour identifier le vocab exterieur

Normalement c’est bon. Voir fichier : 
https://drive.google.com/open?id=0B3YdLwNsVEvnMTFyLXBFMUxmSFE

**Comment by syphax-bouazzouni** [comment]
@jonquet  is this still relevant?  if not please close it.

**Comment by syphax-bouazzouni** [comment]
> @jonquet is this still relevant? if not please close it.

Assume outdated, please re-open if that is not the case @jonquet
